import fs from 'node:fs';
const dir='profile-audit/reports/authority-liberty-2026-10-06/';
const contexts=JSON.parse(fs.readFileSync(dir+'retained-context.json'));
const changed=JSON.parse(fs.readFileSync(dir+'question-changes.json')).questions;
const data=contexts.map(c=>{
 const draft=dir+'prepared/'+c.catalogue+'/'+c.id+'.json';
 const a=JSON.parse(fs.readFileSync(fs.existsSync(draft)?draft:'profile-audit/answers/'+c.catalogue+'/'+c.id+'/'+(c.revision+1)+'.json'));
 const old=JSON.parse(fs.readFileSync('profile-audit/answers/'+c.catalogue+'/'+c.id+'/'+c.revision+'.json'));
 return {key:c.catalogue+'/'+c.id,name:a.metadata.name,catalogue:c.catalogue,revision:a.revision,period:a.metadata.period,path:`audits/${c.catalogue}/${c.id}/${a.revision}.json`,answers:changed.map(q=>({...q,answer:a.axes.flatMap(ax=>ax.answers).find(a=>a.questionId===q.id),oldValue:old.axes.flatMap(ax=>ax.answers).find(a=>a.questionId===q.id).value})),sources:a.sources,notes:a.review.notes,concurrent:c.id==='united-kingdom'};
});
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Authority–Liberty assessment review</title><style>body{margin:0;background:#f5f4ef;color:#242927;font:16px/1.6 system-ui,sans-serif}main{max-width:960px;margin:auto;padding:32px 20px}h1{font-size:clamp(1.8rem,5vw,2.8rem);line-height:1.15}select{max-width:100%;padding:12px;font:inherit;background:white;border:1px solid #aaa;border-radius:8px}article{background:white;border:1px solid #ddd;border-radius:12px;padding:20px;margin:18px 0}h2{font-size:1.15rem;line-height:1.4}details{margin-top:12px}a{color:#275d49;overflow-wrap:anywhere}p,li{overflow-wrap:anywhere}.meta{color:#535b56}summary{cursor:pointer}footer{margin-top:32px;border-top:1px solid #aaa}</style><main><h1>Review the revised Authority–Liberty answers</h1><p>Nine reviewed question records: four familiar statements moved to improve coverage and five new statements distinguish ordinary enforcement from broader control. Scoring and the axis definition are unchanged.</p><p>Exact new responses are educated assumptions grounded in retained subject evidence and selected supplementary research. Historical analogies, source-access limits and implementation differences remain. This is a distinct same-agent review, with no external peer review or empirical calibration claimed.</p><label for="subject">Choose an assessment</label><br><select id="subject"></select><p id="status" class="meta"></p><p id="download"></p><section id="answers" aria-label="Changed question assessments"></section><footer><p>All other 231 answer records and 14 axes are preserved for the 208 focused revisions. A concurrent full UK re-audit using this exact bank is retained separately; its broader changes are not attributed to this migration.</p></footer></main><script>
const data=${JSON.stringify(data).replaceAll('<','\\u003c')};
const labels={'-2':'Strongly disagree','-1':'Disagree','0':'Neutral','1':'Agree','2':'Strongly agree'};
const element=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
const select=document.querySelector('#subject');for(const p of data){const o=element('option',p.catalogue+' · '+p.name);o.value=p.key;select.append(o);}
function render(){const p=data.find(p=>p.key===select.value);document.querySelector('#status').textContent=p.name+' · revision '+p.revision+' · 240/240 answered · bank 3.0.0 · '+p.period+(p.concurrent?' · concurrent full re-audit retained':'');const download=element('a','Download permanent complete assessment');download.href=p.path;download.download='';document.querySelector('#download').replaceChildren(download);const container=document.querySelector('#answers');container.replaceChildren();for(const q of p.answers){const article=element('article');article.append(element('h2',q.id+': '+q.text),element('p','New: '+labels[q.answer.value]+' · Previous response at this ID: '+labels[q.oldValue]),element('p','Previous wording: '+q.previousText));const details=element('details');details.append(element('summary','Evidence, reasoning and uncertainty'),element('p',q.answer.rationale));const list=element('ul');for(const id of q.answer.sources){const source=p.sources.find(s=>s.id===id);const li=element('li');const a=element('a',source.title+' — '+source.publisher);a.href=source.url;a.rel='noopener noreferrer';li.append(a);list.append(li);}details.append(list);article.append(details);container.append(article);}}
select.addEventListener('change',render);render();</script></html>`;
fs.writeFileSync('frontend/public/profiles/authority-liberty-review.html',html);
console.log('Generated review artifact for '+data.length+' complete assessments.');
