import fs from 'node:fs';
import path from 'node:path';
import {root,bankHash,latest} from '../../../frontend/scripts/profiles.ts';
import {questions} from '../../../frontend/src/quiz/model.ts';
import {validateAudit,neighbourReview} from '../../../frontend/src/profiles/audit.ts';
const report=path.dirname(new URL(import.meta.url).pathname);
const specs=JSON.parse(fs.readFileSync(path.join(report,'subjects.json'),'utf8'));
// Literal policy choices used in the separate review, in bank order. The second
// interest is a substantive qualification for a mixed response, not uncertainty.
const issues=[
`competitive electoral accountability|continuity of leadership;expert selection|equal political participation;universal adult suffrage|historical qualifications for active citizenship;executive initiative|parliamentary legislative consent;equal opposition access|constitutional limits on political organisation;opposition financial oversight|executive control of scrutiny;independent constitutional review|government discretion;organised labour selection|the general electorate's authority;exclusion of political opponents|equal competitive access;popular repeal|representative deliberation;sole leadership discretion|shared institutional authority;constitutional removal for abuse|continuity and limits on resistance;unilateral electoral delay|independent control of elections;recall accountability|stable representative terms;freedom from electoral accountability|government answerability;military replacement of civilians|constitutional civilian control`,
`adult self-regarding freedom|paternal moral or health protection;court-supervised investigation|private communication;peaceful disruptive protest|public access and order;offensive institutional criticism|deference and public cohesion;mandatory personal protection|adult autonomy;general long-term movement records|privacy without suspicion;random intoxication testing|individual suspicion standards;court-found future danger|movement before a completed offence;access to morally objectionable material|public moral restraint;anonymous communication|state identification and enforcement;suspicionless searches during a serious threat|individual legal protection;credible-disorder prevention|freedom of public assembly;home warrants with an emergency exception|executive search discretion;disclosure of misconduct|confidentiality and security;screened defensive firearm ownership|risks and collective policing;executive terrorism detention|independent judicial review`,
`national cultural priority|recognition of migrant practices;funded cultural accommodation|common-service cost and cohesion;adopting national customs|continuing personal cultural identity;retention of foreign identity|shared civic integration;national-language priority|multilingual public access;Indigenous ceremonial recognition|a uniform public identity;predominant cultural funding|support for minority expression;distinct-identity priority|a shared national culture;one public calendar|accommodation of different celebrations;plural national traditions|a singular inherited cultural identity;participation in the wider community|cultural separation;foreign-language local signage|common-language accessibility;shared family national identity|distinct community affiliation;covering exemptions|consistent general covering rules;plural cultural ways of life|a uniform national culture;shared integration customs|maintaining community-specific customs`,
`strict numerical admission limits|flexible migration and humanitarian claims;settlement for improved living conditions|receiving-state capacity;skills-only ordinary admission|non-economic and family grounds;dependent-family reunion|managed admission capacity;permanent refugee protection independent of skills|state admission conditions;regularisation after unlawful entry|enforcement and deportation;limits despite employer demand|workforce recruitment freedom;lower arrivals for housing and services|economic gains from migration;one family-and-other quota|special protection for family unity;entry with a job offer|other admission requirements;sponsorship requirements|independent migration grounds;no graduate pathway by itself|retaining educated entrants;persecution protection beyond quotas|ordinary numerical controls;culturally similar admission priority|equal individual treatment;migrant welfare and social housing|eligibility and public capacity;diversity-driven expansion|other migration purposes and integration`,
`force for un-attacked interests|restraint against offensive war;diplomacy despite delay|rapid force-backed leverage;costly military superiority|other public priorities;pre-emption with imminent-attack evidence|waiting for a completed attack;force limited to responding to attacks|broader collective or preventive missions;mandatory male service|voluntary service and civilian choice;concessions to avert war|national strategic position;autonomous weapons efficiency|human responsibility for lethal decisions;repelling attack|overseas campaigns;absolute avoidance even for attacked allies|collective defence;prolonged overseas combat capacity|territorial defensive focus;unresolved territory rather than war|enforcing a territorial claim;threats for concessions|de-escalation;lower war risk|demonstrated military resolve;military espionage despite tension|stable diplomatic relations;negotiated capability reductions|retaining deterrent strength`,
`final national lawmaking authority|accepted external legal obligations;binding international decisions over objection|national consent;final national judicial authority|international adjudication;durable restrictive alliances|independent action;withdrawal without external approval|binding cooperative duties;international adjudication of officials|domestic legal independence;national-interest priority|shared international goals;shared ecological decision authority|national environmental autonomy;avoiding common-foreign-policy blocs|coordinated diplomatic power;externally required human-rights reform|national lawmaking autonomy;national currency control|shared monetary coordination;pooled decisions and finance|independent public budgets;sole national border authority|shared migration management;negotiated common trade rules|independent tariff discretion;national policy rather than federation|a common political authority;collective rule enforcement at cost|immediate national advantage`,
`mostly private businesses|general public economic ownership;public utility networks|private provision with public safeguards;private preference at equal performance|public accountability and social purpose;public competitive enterprises|space for independent private enterprise;private healthcare ownership|public control separate from public funding;public railway infrastructure|private ownership with regulation;lower-cost private contracting at equal quality|direct public provision;public banks alongside private banks|exclusively private finance;sale of commercial public businesses|retained public economic capacity;substantial public rental housing|private housing with assistance;regulated private security businesses|public control of strategic assets;public resource extraction|private investment with regulation;routine private service contracting|public workforce and control;strategic retention despite sale revenue|immediate fiscal returns;sale of subsidised public businesses|maintaining socially useful capacity;public national broadcaster|plural private broadcasting only`,
`protective tariffs|competitive imports;most barriers removed despite losses|sheltering domestic incumbents;domestic procurement despite extra cost|best-priced foreign supply;best-terms sourcing|national sourcing obligations;costly essential import restrictions|consumer cost and foreign supply;unilateral liberalisation|reciprocity;temporary infant-industry shelter|immediate competition;equal foreign-investor entry|domestic firm protection;farm import restrictions|cheaper or varied foreign food;competitive adjustment|public trade protection;retaliatory tariffs|avoiding escalation;equal product taxation|domestic fiscal preference;restrictions on subsidised foreign competition|consumer access and exchange;tariff removal with dependency|domestic productive resilience;domestic strategic control|foreign investment capacity;foreign online services|national restrictions on exchange`,
`private production decisions|public production direction;compulsory strategic targets|independent output choices;market pricing|administrative price determination;planned investment sectors|decentralised investment judgment;demand-led expansion or closure|production-plan continuity;essential price controls|supplier pricing and availability;free industry entry|administrative need assessment;directed bank lending|independent credit allocation;capital movement without approval|national financial control;selected industrial subsidies|investor-led development;private currency competition|public monetary authority;statutory minimum wage|wholly negotiated lowest wages;negotiated wages|public wage schedules;central-bank plan support|independent monetary objectives;market rental pricing|affordability controls;ordinary national coordination|individual business production decisions`,
`substantial income equalisation|preserving differential earnings;income differences insufficient for more tax|redistribution as an independent goal;stronger minimum despite taxes|lower fiscal burdens;basic-only benefits|narrower living-standard differences;progressive tax shares|equal-rate treatment;retaining earnings despite inequality|more redistribution;inheritance tax for support|familial transfers and retained wealth;time limits despite continued low income|continuing material support;wealth-funded transfers|retaining accumulated property;modest benefits for lower tax|adequate social participation;support beyond survival|a narrow basic-needs floor;tax cuts over cash benefits|more material assistance;low-paid worker supplements|less public income support;no higher marginal rates|progressive contributions;compensated land redistribution|existing ownership security;basic-needs-only cash eligibility|a broader low-income guarantee`,
`religion-independent legal reasons|official religious normative authority;religious teaching as law source|civil justification independent of doctrine;no required clerical approval|formal religious oversight;constitutional religious foundation|religiously neutral state identity;non-proselytising religion education|cultivation of a designated faith;faith-cultivating state-school instruction|freedom from public proselytism;civilly enacted court law|authority-issued religious rulings;official clerical law review|independent civil legislation;no organised official worship|ceremonial public faith;public spending to strengthen belief|equal secular civic funding;no endorsed religious symbols|inherited religious public identity;religious festival recognition|a religiously neutral public calendar;no ex-officio clergy seats|religious institutional representation;extra religious tax exemptions|equal charitable tax treatment;no marriage religious approval|religious control of civil status;binding religious family courts|uniform civil jurisdiction`,
`substantial customary change|inherited continuity;tradition over new preference|revisable social expectations;equal nontraditional family recognition|a privileged married-parent model;distinct traditional gender roles|role autonomy;same-sex marriage|traditional sex-specific marriage;preferred married-parent family|equal status for household forms;early abortion acceptance|traditional protection of prenatal life;parental sexual-curriculum veto|common education and children’s autonomy;equal same-sex adoption acceptance|traditional sex-specific parenting;traditional modesty|individual public dress choices;identity-responsive language|inherited conventions;transmitting established morals|encouraging new customs;equal cross-sex role acceptance|traditional role expectations;gradual institutions despite popular demand|rapid democratic change;inclusive sexuality education|parental traditional objections;ancestral customs despite lost purpose|practical revisability`,
`early-benefit deployment|unknown long-term harms;small trials until strong risk evidence|speed and scale of access;beneficial infrastructure with habitat loss|ecological preservation;long-term medical safety before access|earlier treatment and choice;AI productivity despite job replacement|employment continuity;habitat preservation despite benefits|public development needs;early cultivated meat|uncertain ecological effects;research-only enhancement implants|adult enhancement choice;unproven climate technology priority|reducing material demand;construction delay for unknown ecology|timely public infrastructure;enhancement after basic safety only|remaining long-term harms;supervised diagnostic trials|earlier broad medical use;embryo enhancement trials|life, consent and heritable intervention limits;long-term crop ecosystem evidence|early agricultural gains;housing and transport expansion|undeveloped land preservation;delay for irreversible harms|early technological benefits`,
`protected regional self-rule|national policy consistency;national final jurisdiction|regional constitutional protection;majority regional secession|a continuing civil union;overriding a locally popular obstruction|regional democratic preference;regional constitutions within rights|uniform institutional structure;single national police command|separate local policing;retaining most local taxes|national redistribution and provision;national compulsory curriculum|regional educational choice;different regional tax rates|uniform fiscal treatment;national employment law|regional labour autonomy;local council restructuring without approval|national institutional safeguards;national treatment coverage|regional healthcare choices;Indigenous territorial self-government|uniform national administration;national tax-competition limits|regional fiscal autonomy;regional land decisions without spillovers|central environmental authority;national multi-region emergency command|regional response autonomy`,
`upbringing over inheritance|biological dispositions;national IQ heredity priority|education and measurement context;social gender explanation|biological sex differences;biological stress differences|lived experience;experienced interests|inherited predispositions;inherited risk-taking|learned risk judgment;social cooperative habits|inherited tendencies;inherited empathy|social formation;experienced attention|biological capacities;biological moral intuitions|moral education;learned threats|biological predispositions;biological temperament|social experience;cultural attractiveness|inherited preferences;racial biology for violence|social conditions and the unestablished racial premise;learned self-control|inherited racial claims;sex-based economic value for pay|social expectations and the question’s failure to isolate inheritance`
].map(row=>row.split(';').map(item=>item.split('|')));
if(issues.some(row=>row.length!==16))throw Error('Review issue map must cover all 240');
const labels=['Strongly disagree','Disagree','Neutral','Agree','Strongly agree'];
const reviewed=[];
for(const spec of specs){
 const file=path.join(root,'profile-audit/drafts/ideology',spec.id+'.json');
 const audit=JSON.parse(fs.readFileSync(file,'utf8'));
 const corrections=[];
 // Literal review correction: body-covering exemption is not simply freedom to
 // wear a veil; the statement expressly keeps other full coverings prohibited.
 if(['classical-liberalism','republicanism','progressive-liberalism','meritocracy','environmentalism'].includes(spec.id)){
  const a=audit.axes[2].answers[13]; if(a.value!==0){corrections.push({id:a.questionId,before:a.value,after:0,reason:'Balance religious/cultural liberty with consistent nonreligious covering rules; not a general prohibition on veils.'});a.value=0;}
 }
 for(let i=0;i<15;i++){
  const axis=audit.axes[i];
  axis.counterEvidence=spec.limits+' Axis-specific qualification reviewed: '+spec.briefs[i]+' The scope is a selected interpretation; no uniform position across every adherent is claimed.';
  for(let j=0;j<16;j++){
   const a=axis.answers[j], [proposal,qualification]=issues[i][j];
   const decision=a.value===0?`Here ${proposal} has a legitimate role, but ${qualification} also carries material weight in this scope. A categorical choice would overstate either priority; this is the reason for a mixed response.`:a.value>0?`On this specific trade-off, ${proposal} is more consistent with the scoped principle than giving priority to ${qualification}.`:`On this specific trade-off, ${qualification} is more consistent with the scoped principle than giving priority to ${proposal}.`;
   const q=questions.find(q=>q.id===a.questionId);
   const gap=i===14?' The sources are philosophical or institutional context, not genetic findings. Racial premises are not accepted as established empirical facts; the pay-gap question does not isolate biological inheritance.':i===12?' Modern applications are inferred; general technological support does not automatically settle embryo ethics or long-term medical safety.':'';
   a.rationale=`Educated assumption: ${axis.brief} For “${q.text}”, the most likely response is ${labels[a.value+2]}. ${decision} ${Math.abs(a.value)===2?'The strong intensity expresses a core conflict or commitment; it remains an interpretive estimate.':Math.abs(a.value)===1?'The qualified intensity allows exceptions and competing considerations.':''}${gap} Contextual sources: ${a.sources.join(', ')}. They do not document an exact five-point answer to this statement. This application and its intensity remain provisional within ${audit.metadata.period}.`;
  }
 }
 const assumptions=audit.axes.flatMap(a=>a.answers.map(q=>q.questionId));
 const neutralIds=audit.axes.flatMap(a=>a.answers.filter(q=>q.value===0).map(q=>q.questionId));
 const limits=spec.limits+' Sources described as indexed excerpts or abstracts were reviewed only to that extent; inaccessible full texts were not read. Contextual sources for other schools are comparative evidence, not assertions that those writers endorsed this subject.';
 audit.review={reviewer:'Codex (GPT-6), same agent performing a distinct evidence and wording review; no external reviewer',reviewedAt:'2026-10-05',notes:`Reviewed all 240 literal statements against the scoped briefs, response choices, agreement directions and cited contextual evidence. ${limits} All 240 responses are disclosed educated assumptions, including exact intensities; every ID is enumerated in the separate JSON review. Neutral responses were reviewed as the explicit competing priorities in their rationales, not substituted for uncertainty. ${corrections.length?corrections.map(c=>c.id+': '+c.reason).join(' '):'No response was changed in this review.'} No profile was copied and no answers were adjusted to meet a score or reduce similarity.`,similarity:[]};
 reviewed.push({spec,audit,file,review:{id:spec.id,reviewer:audit.review.reviewer,date:'2026-10-05',answered:240,revision:audit.revision,educatedAssumptionIds:assumptions,neutralIds,corrections,limitations:limits,axisReview:audit.axes.map(a=>({id:a.axisId,brief:a.brief,counterEvidence:a.counterEvidence,answers:a.answers.map(q=>({questionId:q.questionId,value:q.value,rationale:q.rationale,sources:q.sources}))}))}});
}
const existing=latest(root).map(e=>({audit:e.audit,profile:validateAudit(e.audit,bankHash).profile})).filter(e=>e.profile);
const newProfiles=reviewed.map(e=>{const check=validateAudit(e.audit,bankHash);if(check.errors.length)throw Error(e.spec.id+': '+check.errors);return check.profile});
for(const entry of reviewed){
 const p=newProfiles.find(p=>p.id===entry.spec.id);
 const neighbours=neighbourReview(p,[...existing.map(e=>e.profile),...newProfiles],[]).neighbours;
 for(const n of neighbours.filter(n=>n.similarity>=95)){
  const other=reviewed.find(e=>e.spec.id===n.id)?.audit||existing.find(e=>e.profile.id===n.id)?.audit;
  entry.audit.review.similarity.push({id:n.id,revision:n.revision,reason:`Retain both after evidence review: ${entry.audit.metadata.name} is scoped as ${entry.spec.scope} The neighbour ${other.metadata.name}, revision ${n.revision}, is scoped as ${other.metadata.scope} Similar axis totals do not make these institutional commitments, intellectual traditions or organising aims identical. The scorer averages distinct question choices and does not measure every doctrinal distinction. Neither answers nor intensities were changed to reduce resemblance.`});
 }
 entry.review.similarity=entry.audit.review.similarity;
 const validation=validateAudit(entry.audit,bankHash);
 entry.review.validation={errors:validation.errors,warnings:validation.warnings,neighbours};
 fs.writeFileSync(entry.file,JSON.stringify(entry.audit,null,2)+'\n');
 fs.writeFileSync(path.join(report,entry.spec.id+'-review.json'),JSON.stringify(entry.review,null,2)+'\n');
 console.log(entry.spec.id+': '+validation.errors.length+' errors; '+validation.warnings.length+' warnings; '+entry.audit.review.similarity.length+' close-neighbour decisions');
}
