import fs from 'node:fs';const dir='profile-audit/reports/personality-additions-second-2026-10-06';
const notes={
'robert-mugabe':'Later rule takes precedence over early reconciliation and ESAP. Coalition and constitutional provisions qualify executive repression. Farm redistribution to private beneficiaries is not universal public ownership. Catholic identity is separate from clerical authority; racial rhetoric does not by itself establish genetic IQ or criminality.',
'ludwig-von-mises':'The classical-liberal programme is assessed independently of Hayek and generic minarchism. Recorded qualified praise of fascism is counter-evidence rather than omitted. Migration freedom differs from public welfare eligibility. Adult agnosticism differs from Jewish ancestry. Praxeology and rejection of race-specific logic do not settle each behavioural genetic causal share.',
'helen-zille':'Provincial strategic plans are not compulsory private production plans. Constitutional opposition and liberal institutional commitments coexist with crime control. Parliamentary criticism of transgender comments is attributed as criticism, not fabricated as her quotation. Church membership is assessed independently of secular government. Immigration estimates have limited exact personal evidence.',
'constand-viljoen':'Use 1994–2001 parliamentary leadership, retaining earlier military coercion and mobilisation as counter-evidence. Read the Freedom Front constitutional memorandum: independent courts and accountable government coexist with community autonomy. Party submissions are contextual, not a personal completed questionnaire. Cultural self-determination is not proof of racial biology or personal religious faith.',
'joseph-de-maistre':'Inherited political legitimacy, Catholic authority and historical social formation are assessed separately. Admiration for the British constitution and context-dependent republics qualifies blanket monarchy claims. Papal jurisdiction is not routine clerical administration of all secular policy. Sovereign authority does not entail command production. Historical modern-policy analogies are particularly uncertain.',
'francisco-franco':'The scope is 1959–1975: private investment and indicative plans replace an undifferentiated early-autarky account. Catholic privilege and 1967 freedom changes do not require blanket clergy approval. Preserved strategic public industries and railways qualify privatisation. Military rule is not evidence for each later foreign war; biological group claims are not supplied from nationalism.',
'engelbert-dollfuss':'Distinguish parliamentary accession from the assessed emergency dictatorship. Agrarian corporatism includes private property, cooperatives and public railways. Opposition to Nazis is not equal party freedom, but also is not Nazi racial biology. Catholic concordat commitments differ from personal religious identity. Do not infer technical stagnation from agricultural interests.',
'jose-antonio-primo-de-rivera':'Read the 27-point 1934 programme: banking nationalisation, private family property, tariffs, producer prices, land redistribution and reforestation are distinct mechanisms. Party abolition and pre-military formation contradict the supplied suggestion of peaceful politics. Church powers are bounded by national integrity. Do not backdate Franco’s later compulsory Falange institutions.',
'antonio-de-oliveira-salazar':'Later EFTA economic opening is included with continuing licensing and corporative direction. Private conglomerates are not all publicly owned. The concordat preserved civil marriage and school opt-outs while privileging Catholic institutions. Colonial war differs from Second World War neutrality. Rejection of Nazi-style racial doctrine does not erase colonial inequality.',
'giovanni-gentile':'Actual idealism and educational formation receive their own Culture–Nature assessment, independently of fascist biological labels. Central school examination and elite selection differ from universal voting or equal-income policy. Personal Catholic identification in 1943 coexists with rejection of independent Church sovereignty. State primacy is not a fully specified public-ownership programme.',
'oswald-mosley':'The 1932–1940 BUF scope excludes later Europe-a-Nation federalism. The primary advocacy archive is identified as interested and checked against contemporaneous JTA and academic research. Opposition to war with Germany does not establish general pacifism. Private firms and profits coexist with corporative production and imperial protection. Christian rhetoric does not establish personal faith.',
'eric-campbell':'Identity is the Australian New Guard leader. Military hierarchy and business interests coexist with later explicit corporative fascism. The National Archives records claims of individual liberty; actual disruption of Communist meetings is counter-evidence. A 1970 Presbyterian funeral does not establish 1931–1935 religious identity. NSW activity is not evidence of federal decentralism.',
'thomas-rousseau':'Identity is the Patriot Front founder. His direct interview’s consent rhetoric is retained alongside racial exclusion; internal regional networks are not public federalism. Opposition to overseas wars differs from domestic martial mobilisation. Economic, biomedical and several privacy mechanisms have particularly weak personal evidence. Christian group symbolism does not establish personal faith. Do not label charges as convictions.',
'giorgia-meloni':'Current governing scope supersedes early Russia and vaccine rhetoric where changed. The 2026 referendum defeat was accepted; constitutional participation is not inferred merely from a label. Lawful worker entry qualifies irregular-entry restriction. Private enterprise coexists with state strategic holdings, energy measures and targeted benefits. Regional autonomy does not imply secession. Personal Christianity does not establish a clergy veto.',
'ernst-rohm':'SA leadership ends before the later world war. Second-revolution anti-capitalism is not a precise complete Marxist economic programme. SA autonomous command does not establish public decentralisation. His same-sex relationships do not establish equal marriage or a general LGBT-rights position; SA repression remains counter-evidence. Religion remains undisclosed.'};
for(const[id]of JSON.parse(fs.readFileSync(dir+'/requested.json'))){const p='profile-audit/drafts/personality/'+id+'.json',d=JSON.parse(fs.readFileSync(p));for(const s of d.sources)if(!/^\d{4}-\d{2}-\d{2}$/.test(s.date))s.date='undated';
 const ids=d.axes.flatMap(a=>a.answers.map(x=>x.questionId));if(ids.length!==240||new Set(ids).size!==240)throw Error(id+' count');
 d.changeNote='Owner-requested addition: 240 current-bank answers completed from scoped evidence, with explicitly inferred estimates and a distinct evidence-review pass.';
 d.review={reviewer:'Codex (GPT-6), distinct self-review pass; not an independent human review',reviewedAt:'2026-10-06',notes:notes[id]+' Reviewed all 240 literal statements and directions, all 15 independent axis briefs, contradictory evidence, sources, period, metadata and educated assumptions. Corrected readings of cultural plurality, unconditional refugee settlement and Catholic embryo-enhancement analogies where applicable. All 240 responses remain conservatively inferred, with exact IDs in the separate review. Neutral responses express qualified or competing positions, not a default for uncertainty. Technical checks do not certify historical or political estimates.',similarity:[]};
 fs.writeFileSync(p,JSON.stringify(d,null,2)+'\n');fs.writeFileSync(dir+'/'+id+'-review.json',JSON.stringify({id,revision:d.revision,answered:240,...d.review,educatedAssumptionIds:ids,neutralResponses:d.axes.flatMap(a=>a.answers.filter(x=>x.value===0).map(x=>({questionId:x.questionId,rationale:x.rationale}))),axes:d.axes.map(a=>({axisId:a.axisId,checkedQuestionIds:a.answers.map(x=>x.questionId),evidence:a.brief,counterEvidence:a.counterEvidence})),sourceAccessCaveat:'Local source capture records successes and failures separately. Previously read web content or indexed source excerpts were used where the direct local fetch failed; no failed fetch is represented as a full-text capture.'},null,2)+'\n');}
console.log('Distinct evidence reviews saved for all 15 profiles.');
