import fs from 'node:fs';
import {subjects,dir} from './research.mjs';
import {sources} from './sources.mjs';
import {specs1} from './specs1.mjs';
import {specs2} from './specs2.mjs';
const specs={...specs1,...specs2};
const bank=JSON.parse(fs.readFileSync('frontend/src/data/questions.v1.json'));
const images=JSON.parse(fs.readFileSync(`${dir}/images.json`));
const labels={'2':'Strongly agree','1':'Agree','0':'Neutral','-1':'Disagree','-2':'Strongly disagree'};
const mechanisms=[
 'competitive electoral renewal|expert appointment|universal adult franchise|legislation against parliament|equal opposition campaigning|opposition financial scrutiny|independent constitutional courts|union appointment|political exclusion of parties|binding popular repeal|sole national policy authority|constitutional removal|unapproved election postponement|popular recall|absence of representative accountability|military replacement of civilians',
 'self-regarding drug choices|court-authorised serious-crime surveillance|peaceful temporary obstruction|offensive institutional criticism|primarily self-protective health mandates|long-term suspicionless tracking|random intoxication checks|court-supervised preventive movement limits|morally objectionable media|anonymous online communication|area-based suspicionless searches|credible-disorder gathering bans|home-search warrants|misconduct-related disclosures|screened personal firearm ownership|detention without independent review',
 'national-cultural precedence|funded cultural accommodation|adoption of cultural customs|retaining foreign identity|national-language priority|Indigenous ceremonial recognition|predominant-tradition funding|separate identity overriding shared culture|one common calendar|several recognised traditions|wider civic participation|community-language signage|shared identity in families|unequal exceptions for full coverings|plural national ways of life|shared-custom integration programmes',
 'strict housing/workforce ceilings|settlement for improved living conditions|skills-only permanent entry|family reunification|permanent refugee protection|remaining after irregular migration|limits despite employer demand|housing-related reductions despite gains|family entry inside the cap|job-offer work entry|required settlement sponsorship|graduate settlement routes|protection beyond ordinary quotas|culturally preferential entry|non-citizen welfare access|cultural difference as a reason for more migration',
 'unattacked national-interest force|slower diplomacy first|costly military superiority|evidence-based pre-emption|attack-only military response|male military service|substantial peace concessions|autonomous lethal target selection|territorial defensive focus|avoiding war even for attacked allies|prolonged overseas combat|leaving territorial disputes unresolved|coercive military threats|war-risk reduction over resolve|provocative military espionage|negotiated capability reductions',
 'final domestic legislative authority|opposed binding international decisions|national versus international courts|constraining long-term alliances|unilateral treaty withdrawal|binding official-focused international litigation|national-interest priority|international environmental authority|common foreign-policy blocs|internationally required rights-law change|national currency control|shared international budgets|sole border-entry authority|common negotiated trade rules|international political federation|costly enforcement of collective rules',
 'private ownership of most firms|public utility networks|private preference at equal performance|public firms in competitive industries|private facilities with public health funding|public passenger-rail infrastructure|lower-cost private contracting|public and private banks together|commercial-asset privatisation|substantial public rental housing|regulated private strategic firms|public resource extraction|private routine-service contracting|strategic ownership despite sale revenue|sale of persistently subsidised firms|a publicly owned broadcaster',
 'protective import tariffs|removing barriers despite domestic losses|costlier domestic procurement|best-terms international sourcing|essential-goods import restrictions|unilateral barrier reductions|temporary infant-industry protection|equal foreign-investor terms|agricultural import restrictions|adjustment instead of protection|retaliatory tariffs|equal domestic/foreign product taxes|anti-subsidy import restrictions|tariff-removing agreements despite dependence|strategic foreign-control restrictions|foreign online-service access',
 'independent business production|compulsory industrial targets|supply-and-demand pricing|planned sectoral investment|demand-led business closure|essential-goods price controls|entry without a needs test|directed bank credit|unapproved outward capital movement|development subsidies|competing private currencies|a legal minimum wage|negotiated versus scheduled wages|government-directed central-bank policy|market rents|ordinary-condition national production coordination',
 'substantial disposable-income equalisation|rejecting inequality alone as a tax reason|a stronger taxed minimum income|a basic rather than equalising safety net|higher proportional taxes on high earners|earnings retention despite inequality|inheritance-funded support|time-limited working-age support|wealth-funded transfers|modest benefits for lower taxes|support for ordinary social participation|tax cuts over cash-benefit increases|low-paid worker supplements|flat additional-income rates|compensated land redistribution|needs-only benefit eligibility',
 'nonsectarian legal justification|religious teachings as official law|policy without clerical approval|a constitutionally foundational faith|non-proselytising religious education|state-faith instruction|civil rather than religious court law|official clerical legislative review|worship-free state ceremonies|belief-strengthening public expenditure|religion-endorsing building symbols|official religious festival holidays|religious-office parliamentary seats|religion-specific tax exemptions|removal of religious marriage approval|binding religious family courts',
 'substantial custom change|traditional continuity before adaptation|equal household recognition|distinct conventional sex roles|same-sex marriage|preferred married-parent families|early-abortion social acceptance|parental sexual-curriculum vetoes|same-sex adoptive-parent recognition|traditional public modesty|identity-responsive language|inherited morals before new customs|equal acceptance across sex-associated roles|gradual institutional change|orientation and identity education|ancestral customs without clear utility',
 'early-benefit adoption despite unknown risks|small trials pending long-term evidence|infrastructure despite permanent habitat loss|long-term medical safety evidence|job-displacing productivity AI|undisturbed habitat before public development|early cultivated-meat substitution|research-only enhancement implants|unproven climate technology before consumption cuts|construction delays for environmental evidence|basic-safety enhancement implants|diagnostic AI supervised reliability trials|ability-enhancing embryo trials|long-term GM ecosystem evidence|housing/transport before undeveloped land|delaying irreversible-risk technologies',
 'protected regional affairs|final national authority disputes|majority-referendum secession|overriding popular regional obstruction|regional constitutions within national rights|one nationally directed police force|local retention of most taxes|national compulsory curriculum|regional tax-rate choices|national employment rules|locally changed council powers/boundaries|national medical coverage|Indigenous local self-government|limits on interregional tax competition|local-effect regional wildlife policy|national multi-region disaster command',
 'upbringing versus inherited behaviour|inherited national IQ differences|social versus biological sex behaviour|biological stress sensitivity|experienced versus inherited interests|inherited risk tolerance|socially learned cooperation|inherited empathy|experienced attention capacity|biological immediate moral reactions|learned perceptions of threat|biological temperament|culturally formed attractiveness preferences|racial biology as the better violence explanation|learned versus inherited racial self-control|economic value versus social expectations in the pay gap',
].map(s=>s.split('|'));
const corrections={
 'robert-menzies':{'public-private-08':{value:2,reason:'The Commonwealth Bank remained publicly owned alongside private banks during this period; the evidence supports this precise mixed-banking arrangement.'}},
 'kim-jong-un':{'democracy-autocracy-03':{value:1,reason:'Formal universal adult voting is retained even though elections lack genuine alternatives; the literal franchise question is distinct from competitive elections.'},'democracy-autocracy-16':{value:-2,reason:'The armed forces remain subordinate to party leadership; military power does not imply endorsement of a military-led replacement on its own judgement.'}},
 'hugo-chavez':{'democracy-autocracy-04':{value:0,reason:'Delegated decree powers and pressure on the legislature weigh toward executive autonomy, but delegation is not proof of authority to legislate against an explicit parliamentary rejection.'},'democracy-autocracy-11':{value:1,reason:'Executive dominance supports some agreement, but surviving constitutional, electoral and assembly mechanisms qualify sole authority.'},'democracy-autocracy-15':{value:-1,reason:'Elections, the recall referendum and acceptance of the 2007 referendum defeat provide real accountability, despite serious institutional constraints.'}},
};
for(const [id,name,lifespan,period,role,category] of subjects){
 const audit=JSON.parse(fs.readFileSync(`profile-audit/drafts/personality/${id}.json`));const spec=specs[id];
 audit.researchedAt='2026-10-05';audit.author='Codex (GPT-6; research and individual question assessment)';audit.changeNote='Initial sourced assessment of the requested individual; all 240 questions answered with disclosed contextual inferences.';
 audit.metadata={name,description:spec.description,category,period,scope:`Public positions and conduct during ${period}; positions outside this period are contextual only. Modern mechanisms are explicit historical/contextual inferences, not attributed quotations.`,role,lifespan,image:images[id]};audit.sources=sources[id];
 audit.axes.forEach((axis,i)=>{
  const row=spec.axes[i];if(row.values.length!==16||mechanisms[i].length!==16)throw Error(`${id}/${axis.axisId}: incorrect count`);
  axis.brief=row.brief;axis.counterEvidence=row.counterEvidence.replace('troubling contextual evidence','contextual evidence');
  axis.answers.forEach((a,j)=>{
   const q=bank.questions.find(q=>q.id===a.questionId);const change=corrections[id]?.[a.questionId];a.value=change?.value??row.values[j];a.basis='inferred';a.sources=row.refs;
   if(id==='benjamin-netanyahu'&&i===0)a.sources=[...new Set([...a.sources,'knesset'])];
   const strength=a.value===0?`Neutral is a substantive mixed/conditional judgement on ${mechanisms[i][j]}: the supported commitments above pull in different directions when applied to this specific mechanism. It is not a missing-evidence placeholder.`:Math.abs(a.value)===2?`${labels[a.value]} is more likely than a qualified or neutral response to ${mechanisms[i][j]} because this claim ${a.value>0?'reinforces':'runs against'} the central institutional or moral commitment described above.`:`${labels[a.value]} is more likely on ${mechanisms[i][j]}, but the qualification in the evidence makes an absolute response less plausible.`;
   a.rationale=`Educated assumption: ${axis.brief} Applying that record to the exact claim “${q.text}”, ${strength} ${change?.reason??axis.counterEvidence} The sources support the context, not a personal answer to this questionnaire; the precise strength and any contemporary institutional translation remain uncertain.`;
   if(a.sources.some(ref=>!audit.sources.some(s=>s.id===ref)))throw Error(`${id}: missing source`);
  });
 });
 audit.review={reviewer:'Codex (GPT-6; same-agent distinct evidence review pass)',reviewedAt:'2026-10-05',notes:`Separate review checked the 240 literal claims against the current bank, agreement directions, period, actual institutional conduct and counter-evidence. No target scores or neighbour responses were used to choose answers. All 240 answers are labelled inferred conservatively: these are contextual predictions, not answers supplied by the subject. Exact inferred IDs are ${audit.axes.flatMap(a=>a.answers.map(q=>q.questionId)).join(', ')}. Neutral answers were reviewed as conditional positions rather than automatic defaults. Modern technology and specific institutional mechanisms have particularly indirect support; Culture vs Nature is a causal assessment, not environmental policy or an inference from party/religion alone. Personal faith was separated from religious government, ownership from spending, assimilation from migration volume, and wartime measures from ordinary powers. ${Object.values(corrections[id]??{}).map(c=>c.reason).join(' ')} Publisher labels do not guarantee independent evidence: duplicated RFK speech transcriptions count as one primary document; contextual biography supplies a cross-check. Some sites restrict direct download; accessible browser text/search excerpts and saved access records identify those limitations. Similarity review is diagnostic and does not adjust evidence-supported answers.`,similarity:[]};
 fs.writeFileSync(`profile-audit/drafts/personality/${id}.json`,JSON.stringify(audit,null,2)+'\n');
 fs.writeFileSync(`${dir}/${id}-review.json`,JSON.stringify({id,revision:1,reviewer:audit.review.reviewer,reviewedAt:audit.review.reviewedAt,period,answered:240,inferredQuestionIds:audit.axes.flatMap(a=>a.answers.map(a=>a.questionId)),neutralQuestionIds:audit.axes.flatMap(a=>a.answers.filter(a=>a.value===0).map(a=>a.questionId)),axisReviews:audit.axes.map(a=>({axisId:a.axisId,evidence:a.brief,counterEvidence:a.counterEvidence})),corrections:corrections[id]??{},notes:audit.review.notes},null,2)+'\n');
 console.log(id,'240/240');
}
