// Explicit question-by-question choices, in current bank order. No pole-vector conversion.
export const subjects={
 'matt-canavan':{
 name:'Matt Canavan',role:'Australian senator for Queensland and leader of the Nationals',lifespan:'1980–present',period:'2021–5 October 2026; emphasis on 2026 leadership positions',category:'National conservative',
 description:'Australian Nationals senator for Queensland. His 2026 agenda combines selective industry protection, energy and infrastructure expansion, lower immigration and socially conservative positions.',
 sources:[
 ['patriot','The Patriot’s Agenda for our National Economic Revival','https://mattcanavan.com.au/press_club_address_2026/','Matt Canavan','2026-04-08'],
 ['abc-economy','Canavan’s Australia on steroids economic plan','https://www.abc.net.au/news/2026-04-08/nationals-matt-canavan-national-press-club-australia-on-steroids/106538718','ABC News','2026-04-08'],
 ['nightly','Inside Canavan’s patriot agenda','https://thenightly.com.au/politics/baby-boom-nuclear-space-ports-and-new-cities-inside-nationals-leader-matt-canavans-patriot-agenda-c-22107000','The Nightly','2026-04-08'],
 ['christian','Our Christian Principles','https://mattcanavan.com.au/our_christian_principles/','Matt Canavan','2021-03-05'],
 ['speech-liberty','Canavan questions hate speech laws','https://www.abc.net.au/news/2026-01-22/matt-canavan-coalition-split-attacks-asio-government-ley/106259282','ABC News','2026-01-22'],
 ['acl','Senator Canavan Becomes Leader of the Nationals','https://www.acl.org.au/blog/senator-canavan-becomes-leader-of-the-nationals/','Australian Christian Lobby','2026-03-13'],
 ['senate','Selection of Bills Committee – proposal to refer a bill','https://mattcanavan.com.au/selection-of-bills-committee-proposal-to-refer-a-bill-to-a-committee/','Matt Canavan','2026-02-05']
 ],
 axes:[
 [[2,-2,2,-2,2,2,2,-2,-2,1,-2,2,-2,0,-2,-2],'Electoral parliamentary opposition and Senate scrutiny support representative accountability, not executive rule.','senate speech-liberty','Binding referendums and recall are extrapolations; advocacy of strong policy leadership is not permission to bypass Parliament.'],
 [[-1,1,0,2,-1,-1,1,1,1,1,0,1,2,1,0,-2],'Opposition to broad hate-speech restrictions supports expressive liberty alongside ordinary criminal enforcement.','speech-liberty','Free-speech advocacy does not establish drug, firearm or warrant policy. Public safety exceptions are assessed separately.'],
 [[1,0,1,1,1,1,1,-1,1,1,1,0,1,0,1,1],'Christian heritage and a shared Australian identity matter in his argument, alongside acknowledgement of a more diverse society.','christian patriot','The Christian-principles article explicitly accepts non-Christian Australia. It does not support excluding every distinct culture.'],
 [[2,-1,1,1,0,-2,2,2,1,0,0,1,1,1,0,-1],'The 2026 agenda explicitly seeks to end mass migration; regional development is preferred to population growth through current arrivals.','patriot abc-economy','He does not reject every migrant. Family and persecuted refugees require distinct consideration, rather than automatic rejection.'],
 [[0,1,1,1,1,-1,0,-1,1,-2,1,1,0,1,1,0],'Sovereign industrial capacity, defence supply and security feature in the national revival agenda.','patriot nightly','Defence-industrial self-sufficiency does not prove support for offensive war, conscription or autonomous lethal decisions.'],
 [[2,-1,2,1,2,0,2,-1,1,0,2,1,2,1,2,0],'National sovereignty and domestic capability take priority, with continued use of WTO rules and external trade.','patriot','His tariff proposals are described as compatible with WTO responsibilities. National preference is not rejection of all international cooperation.'],
 [[1,1,1,0,1,1,1,0,1,0,1,-1,1,1,0,1],'Private enterprise is retained; public infrastructure and strategic capacity receive government support.','patriot abc-economy','A national works programme is not comprehensive public ownership. Ownership questions are distinguished from subsidies and regulation.'],
 [[2,-1,1,0,2,-2,1,0,1,-1,1,1,2,0,1,1],'Selective tariffs and anti-dumping protection are proposed for strategically important domestic production.','patriot','He says free trade brought benefits and is still desirable in better conditions. Selective protection does not imply banning ordinary imports.'],
 [[1,-1,1,1,1,0,1,0,1,1,-1,1,1,-1,1,-1],'Industry strategy and infrastructure investment coexist with lower business costs and ordinary private production.','patriot abc-economy','Investment coordination is not compulsory output allocation. No comprehensive price-control or bank-command programme was found.'],
 [[0,1,0,1,1,1,-1,0,-1,1,1,1,1,0,-1,1],'Lower taxes and family support are central, while the agenda supports public investment rather than extensive income equalisation.','patriot abc-economy','Pronatalist family support can expand transfers. Tax reduction does not imply removing every safety net or progressive rate.'],
 [[1,-1,2,0,1,-1,2,-2,-1,1,-1,1,2,1,0,-1],'Christian ethical inheritance is defended within a society that may cease to be predominantly Christian.','christian','Personal faith and Christian heritage are not evidence for clerical approval of legislation or religious courts. Ceremonial accommodation differs from theocracy.'],
 [[0,1,0,1,-1,1,-2,1,0,0,-1,1,1,1,-1,1],'His Christian-principles essay criticises self-defined gender and sexuality, and recent advocacy favours births and family continuity.','christian acl','The born-alive bill concerns infants after delivery and alone cannot determine early-abortion policy; that response is explicitly contextual. Traditionalism does not imply rejection of all equal treatment.'],
 [[1,-1,2,1,1,-2,-1,1,2,-1,0,1,-1,-1,2,1],'Energy expansion, dams, new cities and space infrastructure receive priority over broad net-zero restrictions.','patriot abc-economy nightly','Construction enthusiasm is not proof of permissive embryo editing or brain implants. Irreversible medical interventions are assessed more cautiously.'],
 [[1,0,-1,0,1,-1,1,-1,1,1,1,1,0,-1,1,1],'Regional development and relocation are prominent, alongside a federally coordinated national works programme.','patriot abc-economy','A regional constituency does not establish secession rights or Indigenous institutional autonomy. National investment can coexist with local delivery.'],
 [[1,-1,-1,1,1,0,1,0,0,0,1,1,0,-1,1,1],'The essay treats moral formation and shared culture as learned influences while criticising unlimited self-definition.','christian','No quantitative heredity doctrine was found. Biological sex arguments do not establish inherited national IQ, racial violence or general temperament claims.']
 ]},
 'angus-taylor':{
 name:'Angus Taylor',role:'Australian Liberal Party leader and Leader of the Opposition',lifespan:'1966–present',period:'2025–5 October 2026; emphasis on 2026 leadership programme',category:'Liberal conservative',
 description:'Australian Liberal Party leader and MP for Hume. His 2026 programme favours private enterprise, lower taxes, stronger defence and reduced immigration with enforceable integration requirements.',
 sources:[
 ['migration','Address to the Menzies Research Centre','https://www.liberal.org.au/2026/04/14/leader-of-the-oppositions-address-to-the-menzies-research-centre','Liberal Party of Australia','2026-04-14'],
 ['economy','Address to the Sydney Institute','https://www.angustaylor.com.au/media/address-to-the-sydney-institute','Angus Taylor','2026-07-09'],
 ['budget','Coalition Budget in Reply','https://www.angustaylor.com.au/our-budget','Angus Taylor','undated'],
 ['defence','Submarine Institute of Australia address','https://www.angustaylor.com.au/media/submarine-institute-of-australia---20-august-2025','Angus Taylor','2025-08-20'],
 ['abc','Taylor bets on migration politics','https://www.abc.net.au/news/2026-02-17/migration-social-cohesion-language-support-division-policy/106348608','ABC News','2026-02-17'],
 ['guardian','Reaction to Taylor’s immigration speech','https://www.theguardian.com/australia-news/2026/apr/14/angus-taylor-immigration-speech-australia-backlash-ntwnfb','The Guardian','2026-04-14'],
 ['bio','Meet Angus Taylor','https://www.angustaylor.com.au/meet-angus','Angus Taylor','undated']
 ],
 axes:[
 [[2,-2,2,-2,2,2,2,-2,-2,0,-2,2,-2,0,-2,-2],'The leadership programme invokes democracy, rule of law and parliamentary scrutiny of future tax increases.','migration budget','The migration platform expands administrative enforcement; that is not evidence of abolishing electoral opposition. Recall and citizen repeal are institution-specific extrapolations.'],
 [[-1,1,-1,2,-1,0,1,1,1,0,1,1,2,0,-1,-2],'Individual choice and speech are affirmed, but immigration enforcement includes enhanced intelligence screening and compulsory social-media disclosure.','migration','Screening foreign applicants differs from surveilling every citizen. His anti-nanny-state rhetoric does not settle every drug, firearms or health question.'],
 [[2,-1,2,1,2,1,1,-2,1,1,2,0,2,0,1,2],'Binding values and English requirements emphasise integration into a common civic culture.','migration abc','He explicitly rejects race and faith discrimination and welcomes the Chinese diaspora. Cultural plurality remains compatible with civic requirements.'],
 [[2,-1,1,1,-1,-2,2,2,1,0,1,2,0,1,-1,-1],'The budget programme links migration limits to housing supply, removes overstayers and limits future non-citizen welfare eligibility.','budget migration','Humanitarian and compassionate visa holders are exempted from some proposed benefit restrictions; family routes are not categorically abolished.'],
 [[1,1,2,1,0,-1,-1,-1,1,-2,2,1,1,0,1,0],'AUKUS, higher defence spending and offensive and defensive capabilities serve deterrence and regional security.','defence budget','His defence speech also prioritises diplomacy and repairing trade with China. Deterrence is not a commitment to war at every opportunity.'],
 [[2,-1,1,2,1,0,2,1,-1,0,2,1,2,1,2,1],'National interests and border control coexist with long-term allied security and economic cooperation.','migration defence','AUKUS places real value on cooperation. Alliance commitments are considered independently from supranational legislative supremacy.'],
 [[2,0,2,-1,1,1,2,-1,1,-1,2,-1,2,0,1,1],'Private-sector enterprise is the main economic engine; essential services and infrastructure remain publicly supported.','economy budget','Medicare, pensions and a housing infrastructure fund limit a blanket privatisation interpretation. Public funding alone does not establish public ownership.'],
 [[-1,1,0,1,0,0,0,1,0,1,0,1,1,1,1,1],'Trade repair and competition are supported, with strategic security exceptions rather than a broad tariff revival.','defence economy','The programme seeks domestic capability and protection from coercion. This can constrain strategic investment without requiring economy-wide import protection.'],
 [[2,-2,2,-1,2,-1,2,-1,1,0,-1,1,1,-2,2,-2],'Deregulation, individual enterprise and private investment are preferred over routine government economic direction.','economy migration','Temporary emergency intervention is expressly accepted, and infrastructure funding remains. Neither establishes compulsory production targets in ordinary conditions.'],
 [[-1,2,-1,1,1,2,-2,0,-2,1,1,2,1,-1,-2,1],'Tax indexation and opposition to new wealth-related taxes accompany retention of pensions and Medicare.','budget economy','Existing progressive brackets are retained. A safety net is not equivalent to an agenda of substantial income equalisation.'],
 [[2,-2,2,-1,1,-2,2,-2,0,0,0,1,2,1,1,-2],'Freedom of religion, civil rule of law and rejection of parallel legal systems establish civic rather than clerical government.','migration','This does not imply eliminating religious holidays, ceremonial worship or charitable tax treatment. Those details are inferred separately.'],
 [[0,1,1,0,1,1,0,1,1,0,0,1,1,1,0,1],'The programme emphasises established Australian values, equal opportunity and continuity of institutions.','migration economy','No detailed current programme on abortion, gender curricula or modest dress was found. Moderate choices reflect civic equality with gradual institutional change, not an assumed party-wide position.'],
 [[1,-1,2,1,1,-1,0,1,1,-1,0,1,-1,0,2,1],'Productivity, cheaper power, construction-code reform and faster housing investment favour economic development.','budget economy','Deregulation in building does not establish endorsement of irreversible biomedical experimentation. Safety-dependent items receive separate treatment.'],
 [[1,0,-1,0,1,-1,1,-1,1,1,1,1,0,-1,1,1],'The Sydney Institute speech invokes local knowledge and criticises bureaucratic displacement of local land management.','economy budget','National defence and housing funding are retained. Local knowledge does not establish an unconditional secession right or exclusive regional taxation.'],
 [[1,-1,0,1,1,0,1,0,0,0,1,1,0,-1,1,1],'Self-determination, opportunity and learned civic values are important to the programme.','economy migration','These are contextual clues about social formation, not evidence of a heredity model. No racial-biological doctrine was found; anti-discrimination language is not a scientific finding.']
 ]},
 'zohran-mamdani':{
 name:'Zohran Mamdani',role:'Mayor of New York City; former New York State assemblymember',lifespan:'1991–present',period:'2021–5 October 2026; 2025 campaign and 2026 mayoralty',category:'Democratic socialist',
 description:'New York City mayor and former state assemblymember. His agenda includes rent stabilisation, public housing investment, affordable public services, immigrant protections and civil-rights protections.',
 sources:[
 ['housing','Block by Block housing plan: mayoral transcript','https://www.nyc.gov/mayors-office/news/2026/05/transcript--mayor-mamdani-releases--block-by-block--the-housing-','NYC Mayor’s Office','2026-05-26'],
 ['stewart','Mayor Mamdani on The Weekly Show','https://www.nyc.gov/mayors-office/news/2026/07/transcript--mayor-mamdani-appears-on-the-weekly-show-with-jon-st','NYC Mayor’s Office','undated'],
 ['ap-rent','Rent board fulfils Mamdani’s rent-freeze vow','https://apnews.com/article/28e6f1bdd100af1e176ede569aab20fb','Associated Press','2026-06-25'],
 ['ap-hate','Mamdani releases antisemitism plan','https://apnews.com/article/zohran-mamdani-combat-antisemitism-jewish-e633e3343d23d2f32aa5784851aeca3b','Associated Press','2026-09-29'],
 ['time','Zohran Mamdani Isn’t Done','https://time.com/7308924/zohran-mamdani-interview-time/','TIME','2025-08-14'],
 ['paris','Mamdani and Paris mayor discuss housing and climate','https://www.lemonde.fr/en/politics/article/2026/09/20/new-york-and-paris-mayors-mamdani-and-gregoire-meet-to-advocate-for-housing-access-and-climate-solutions_6757742_5.html','Le Monde','2026-09-20'],
 ['positions','Political positions of Zohran Mamdani (secondary research index)','https://en.wikipedia.org/wiki/Political_positions_of_Zohran_Mamdani','Wikipedia contributors','undated'],
 ['sanctuary','Public advocate hearing on sanctuary policies','https://advocate.nyc.gov/press/in-council-hearing-nyc-public-advocate-argues-for-strong-sanctuary-policies-to-protect-new-yorkers','NYC Public Advocate','2026-03-09']
 ],
 axes:[
 [[2,-2,2,-2,2,2,2,-2,-2,1,-2,2,-2,1,-2,-2],'Electoral participation, resident input and accountable city institutions are prominent in the public programme.','housing time','Union support does not establish government selection by union leaders. The rent board is appointed, with disputed independence; it is not the national legislature.'],
 [[1,1,2,2,0,-2,1,0,2,2,-1,0,2,2,-1,-2],'Sanctuary privacy and protest activity favour civil liberty, alongside continued protection against violence and hate crime.','sanctuary ap-hate positions','Earlier defund-police advocacy does not mean abolition of all policing. Synagogue security and hate-crime prevention qualify a wholly anti-enforcement reading.'],
 [[-2,2,-1,2,-1,2,-2,0,-1,2,1,2,0,1,2,-1],'Immigrant protection and recognition of multiple communities support a plural city identity.','sanctuary ap-hate','Shared civic participation remains important. Protecting a minority identity does not imply prioritising it over every common legal duty.'],
 [[-1,2,-1,2,2,1,-1,-1,-1,1,-1,-1,2,-2,2,1],'Sanctuary policy protects immigrant residents and limits cooperation with federal removals.','sanctuary positions','City sanctuary administration is not national open-border legislation. Employer sponsorship, annual caps and university routes are explicit extrapolations.'],
 [[-2,2,-1,0,1,-2,1,-2,2,-1,-1,2,-1,2,0,1],'Ceasefire advocacy and opposition to destabilising foreign military action favour negotiation and limits on force.','positions time','Opposition to particular wars is not unconditional pacifism in the face of attacks on allies. No full national defence procurement doctrine was found.'],
 [[0,1,-1,1,0,2,-1,1,0,2,0,2,0,1,0,1],'International-law arguments and cooperation with other cities support cross-border commitments.','positions paris','A local mayor has no demonstrated position on monetary union or world federation. Those mixed answers distinguish cooperation from wholesale sovereign transfer.'],
 [[0,2,0,2,-1,2,-1,1,-2,2,0,1,-1,2,-1,2],'Public housing investment and municipal service provision favour public options alongside existing private businesses.','housing positions','He continues working with private and nonprofit housing owners. City-owned groceries do not establish that most national businesses should be state-owned.'],
 [[0,0,1,0,1,0,1,0,1,0,0,1,1,0,1,1],'Labour standards and locally accountable provision support selective conditions on commerce.','housing positions','No developed national tariff programme was found. Worker protection and affordability can conflict with high consumer tariffs, supporting mixed rather than blanket protection.'],
 [[1,-1,0,1,1,1,1,0,0,1,-1,2,1,0,-2,-1],'Rent stabilisation, affordable housing and labour standards support selective planning within a mixed economy.','housing stewart','Rent control is not comprehensive output control. Fiscal discipline and private construction constrain an inference of command economics.'],
 [[2,-2,2,-1,2,-1,1,-2,2,-1,2,-2,2,-2,0,-2],'Redistributive taxation and affordable public provision are central to the campaign and mayoral programme.','positions housing paris','Services and housing subsidies are not identical to cash benefits. Fiscal care constrains unlimited spending; land redistribution has not been established.'],
 [[2,-2,2,-2,2,-2,2,-2,0,-1,1,0,2,0,2,-1],'Civil-rights protection and equal treatment of faith communities support civil law rather than a religious state.','ap-hate positions','Personal Muslim faith is not a scoring proxy. Participation in worship and support for community security do not establish religious legal supremacy.'],
 [[2,-2,2,-2,2,-1,2,-1,2,-1,2,-1,2,0,2,0],'LGBTQ protections, reproductive autonomy and anti-discrimination positions support social change and equal recognition.','positions','Protection of faith communities and religious-school autonomy limits an inference that all traditions should disappear. Speed of institutional change is separately assessed.'],
 [[0,1,1,1,0,1,1,1,0,1,0,2,-1,1,2,2],'Housing construction and transport improvement coexist with climate policy, public health and protections against irreversible harm.','housing paris positions','Development support is not a blanket preference against habitat preservation. No specific brain-implant, embryo-editing or cultivated-meat policy was found.'],
 [[2,-1,-1,-1,1,-2,1,-1,1,2,1,1,1,1,1,1],'Sanctuary administration defends local discretion while housing and labour goals depend on state and federal cooperation.','sanctuary housing','Local resistance to immigration enforcement does not imply opposing national civil-rights or employment floors. Federal funding is actively sought.'],
 [[1,-2,1,0,1,-1,2,-1,1,-1,1,0,1,-2,2,-1],'Structural housing barriers, opportunities and discrimination feature in his explanations of social disadvantage.','housing positions','No quantitative biological theory of attention, stress or temperament was found. Structural policy arguments support social influence, not denial of all inheritance.']
 ]}
};
