import fs from 'node:fs';
const dir='profile-audit/reports/personality-additions-2026-10-06';
const notes={
'kevin-rudd':'Retained the 2013 PNG settlement restriction alongside family and humanitarian pathways. Party-room leadership changes are constitutional replacement, not unaccountable rule. The marriage essay separates Christian identity, civil marriage and innate sexuality from racial causal claims. Numerous neutral mechanisms were checked against the explicitly recorded competing objectives.',
'malcolm-turnbull':'Used governing-period data-retention policy rather than treating his earlier opposition as the final position. The marriage survey is consultation followed by parliamentary enactment, not a general citizen initiative. Private enterprise coexists with NBN, Snowy Hydro and the ABC.',
'olaf-scholz':'Separated lawful skilled entry and easier citizenship from irregular-entry deportations. Defence expansion does not remove escalation restraint. Church departure establishes personal nonreligion, not hostility to private faith. Minimum-wage and energy interventions do not establish comprehensive production planning.',
'mark-carney':'Assessed the dated 2025–2026 programme, with promises distinguished from implementation. Immigration capacity limits coexist with continuing family and humanitarian routes. Canadian procurement and retaliation qualify general trade openness. Catholic identity is not clerical policy approval.',
'dominik-tarczynski':'Distinguished electoral participation and constitutional claims from restrictions on totalitarian advocacy. Voter identification is not used as evidence of autocracy. Opposition to Muslim immigration differs from treatment of Ukrainians. Christian identity and traditional sex roles do not establish racial genetic crime claims.',
'leon-trotsky':'Used the exile-period critique of bureaucracy while retaining revolutionary coercion as counter-evidence. Soviet parties and class-franchise proposals do not equal unrestricted all-adult liberal pluralism. Democratic economic planning is distinct from eliminating every monetary transaction. Modern mechanisms remain disclosed analogies.',
'julius-malema':'Distinguished the speaker’s manifesto programme from an implemented national government. Pan-African migration and LGBTQ consultation qualify racial-national and social-conservative shortcuts. The 2014 Christian statement supports a qualified period-continuity identity inference; it does not imply religious law. Land question 15 literally includes compensation, unlike his uncompensated land programme.',
'josip-broz-tito':'Separated actual lifelong presidency, repression and security practice from the idealised self-management doctrine. Social ownership can include market exchange and enterprise wage negotiation. Non-alignment does not mean pacifism or obedience to an international political authority. Adult nonreligion is distinct from Catholic upbringing.',
'adam-bandt':'Retained ordinary private enterprises alongside public housing and strategic provision. Opposition to AUKUS is not opposition to all defensive force. Climate precaution differs from Culture–Nature, which uses social-opportunity explanations. Personal faith remains undisclosed rather than inferred from party secularism.',
'friedrich-ebert':'Universal adult suffrage and republican institutions coexist with emergency powers and repression of unrest. The Freikorps record limits a purely libertarian interpretation. Reformist labour compromise is distinct from command collectivisation. Historical sexual, vaccine and enhancement questions are estimates, not invented contemporary declarations.',
'allegra-spender':'Taxing investment earnings is not taxing unrealised wealth balances or increasing total tax. Private market investment and equal-rights policy are independently supported. Similarity with Steggall was examined as shared contextual evidence, not grounds to force different scores. Religious identity remains undisclosed.',
'zali-steggall':'Retained earlier investment-tax reservations as counter-evidence to later housing affordability and rent-cap proposals. Criticism of unchecked visa powers does not imply removing every security check. Her equality and housing evidence was assessed independently of Spender; no Community Strong ideology is created.',
'charlie-kirk':'Stopped the personal period at his September 2025 death; later reporting is retrospective. Later tariff support qualifies free-market rhetoric. Anti-vaccine mandates and firearms rights remain distinct from sexual restrictions. Christian public-government advocacy does not require clerical office. Race-related cultural generalisations are not converted automatically into inherited IQ or crime claims.',
'otto-von-bismarck':'Universal male voting is not universal adult suffrage. Socialist associations were restricted while socialist candidates could still contest elections. Public railways and social insurance coexist with private firms and the 1879 tariff turn. Kulturkampf opposes church control but does not establish an atheist state.',
'alice-weidel':'Verified adult agnosticism separately from AfD Christian-cultural claims. Civil partnerships and adoption qualifications differ from endorsement of same-sex marriage. Pandemic views changed over time. National sovereignty and EU reform or exit proposals do not establish rejection of all alliances or trade.',
'ian-smith':'The racial voting rolls and majority-rule resistance, not mere election administration, justify democracy limitations. Sanctions-induced import substitution differs from an unconstrained preferred tariff programme. His civilisational and education claims do not directly document biological racial crime causation. Removed an unsupported Methodist identity: the current supplement records undisclosed.',
'heinrich-himmler':'Used actual SS repression, racial conquest and heredity programme rather than a generic Nazi score. Conditional private enterprise is not general public ownership. Racially restricted benefits are not universal equality. Adult Germanic God-belief differs from Catholic upbringing; political control differs from independent church authority. Coercive experimentation is not endorsement of voluntary modern treatment.',
'thomas-sewell':'Resolved identity as the Australian organiser, never Thomas Sowell. Electoral registration and judicial appeals coexist with anti-democratic and Hitler-identification statements. Economic and vaccine questions have particularly weak personal evidence and remain qualified assumptions; they are not labelled direct or copied from historical Nazi policy. Charges are not described as convictions. Faith is undisclosed.',
'capitalism':'The published scope explicitly uses a constitutional mixed-economy market-capitalist variant. Economic mechanisms rest on ownership and allocation doctrine; noneconomic answers are low-confidence institutional estimates, not necessary characteristics of every capitalist regime. No religious prerequisite is imposed.',
'leninism':'Separated the 1902–1923 revolutionary doctrine from later Stalinist institutionalisation. Workers’ councils and recall coexist with excluded exploiting classes. NEP private trade is transitional counter-evidence to immediate complete command allocation. Compensated land redistribution is distinct from expropriation.',
'titoism':'Reviewed the 1974 constitutional text against doctrine and practice, including civil liberties, federalism, associated labour and religious freedom. Corrected authority-liberty-16 from Agree to Strongly disagree: Articles 177–178 require legal grounds, court review and detention time limits. Doctrinal safeguards remain distinct from Tito’s personal repressive practice.',
'neo-nazism':'Reviewed postwar currents independently of Himmler and Sewell. Electoral tactics, speech-right claims, religious variants and economically divergent factions qualify a single historical Nazi template. Christian Identity, Odinist and secular currents make a single faith prerequisite inappropriate. Racial beliefs are described, not endorsed.',
'marxism-leninism':'Distinguished codified party-led planned socialism from Lenin’s NEP period, Trotsky’s exile critique and Titoist market self-management. Formal councils and national self-determination coexist with restricted pluralism. Family and sexual policy vary substantively; neutral responses record that conflict, not missing evidence.',
'fanonism':'Fanon’s opposition to bourgeois single-party intimidation and extreme decentralisation are not replaced with a generic Leninist institutional model. Cooperative nationalisation differs from a corrupt central bureaucracy. Anti-colonial violence does not establish racial heredity or unrestricted conquest. EFF material establishes reception, not the whole foundational doctrine.',
'christian-nationalism':'Distinguished Christian public identity from personal Christian faith, clerical government and biological racial hierarchy. Scoped to the contemporary US tradition; economic and modern medical mechanisms are disclosed low-confidence extensions. Conceptual scholarship qualifies broad survey definitions. A Christian comparison prerequisite follows this explicitly faith-specific scope.'
};
for(const file of fs.readdirSync(dir).filter(x=>x.endsWith('-spec.json'))){
 const s=JSON.parse(fs.readFileSync(dir+'/'+file)),p=`profile-audit/drafts/${s.catalogue}/${s.id}.json`,d=JSON.parse(fs.readFileSync(p));
 // Partial historical publication dates are not fabricated as exact calendar dates.
 for(const source of d.sources)if(!/^\d{4}-\d{2}-\d{2}$/.test(source.date))source.date='undated';
 if(s.id==='titoism') {const a=d.axes.find(a=>a.axisId==='authority-liberty').answers[15];a.value=-2;a.rationale='Educated assumption: Strongly disagree is most likely for indefinite terrorism detention without independent court review. The 1974 constitutional programme, Articles 177–178, requires statutory grounds, court oversight and time-limited detention. This doctrinal safeguard outweighs a generic revolutionary-security inference; actual Yugoslav repression remains counter-evidence, and the exact modern terrorism formulation is an analogy rather than a documented questionnaire answer.';a.sources=['source-1','source-2'];}
 const inferred=d.axes.flatMap(a=>a.answers.filter(x=>x.basis==='inferred').map(x=>x.questionId));
 const neutrals=d.axes.flatMap(a=>a.answers.filter(x=>x.value===0).map(x=>({questionId:x.questionId,rationale:x.rationale})));
 d.changeNote='Owner-requested addition; all 240 current-bank answers completed from scoped research, with disclosed contextual inferences and a distinct evidence-review pass.';
 d.review={reviewer:'Codex (GPT-6), distinct self-review pass; not an independent human review',reviewedAt:'2026-10-06',notes:notes[s.id]+' Checked all 240 literal statements and agreement directions, the 15 independent axis briefs, counter-evidence, source references, period, metadata and inferred uncertainty. All 240 responses remain conservatively marked inferred; exact IDs are in the separate review. Technical validation cannot certify the historical or political estimates. Similarity decisions are added only after checking calculated neighbours.',similarity:[]};
 fs.writeFileSync(p,JSON.stringify(d,null,2)+'\n');
 fs.writeFileSync(`${dir}/${s.id}-review.json`,JSON.stringify({catalogue:s.catalogue,id:s.id,revision:d.revision,reviewer:d.review.reviewer,reviewedAt:d.review.reviewedAt,answered:240,notes:d.review.notes,educatedAssumptionIds:inferred,neutralResponses:neutrals,axes:d.axes.map(a=>({axisId:a.axisId,checkedQuestionIds:a.answers.map(x=>x.questionId),evidence:a.brief,counterEvidence:a.counterEvidence})),sources:d.sources,similarity:[]},null,2)+'\n');
 console.log(s.id+' distinct review saved; '+inferred.length+' inferred question IDs disclosed');
}
