import {save,source} from './assessment-helper.mjs';
save({id:'heinrich-himmler',name:'Heinrich Himmler',period:'Nazi state and SS leadership, 1933–1945',lifespan:'1900–1945',role:'Reichsführer-SS and chief of German police',description:'Nazi official assessed through his SS command, racial programme, police institutions and wartime actions.',religion:{value:'other',refs:[2],reason:'His 1942 speech explicitly professed Germanic God-belief and rejected Christianity; Catholic upbringing is not used as his mature identity.'},sources:[source('Heinrich Himmler','https://encyclopedia.ushmm.org/content/en/article/heinrich-himmler','United States Holocaust Memorial Museum'),source('Himmler on Christianity and religion','https://germanhistorydocs.org/en/nazi-germany-1933-1945/ghdi:document-1573','German Historical Institute','1942-06-09'),source('Heinrich Himmler — SS administration and beliefs','https://en.wikipedia.org/wiki/Heinrich_Himmler','Wikipedia'),source('Ideology of the SS','https://en.wikipedia.org/wiki/Ideology_of_the_SS','Wikipedia')],rows:[
[[-2,2,-2,2,-2,-2,-2,2,2,-2,2,-2,2,-2,2,1],'Direct Führer authority, elimination of electoral competition and extra-legal SS power rejected democratic accountability.','Rival Nazi offices and delegated initiative constrained personal control internally, not through equal public suffrage.',[1,3]],
[[-2,2,-1,-2,2,2,2,2,-2,-2,2,1,-2,-2,-2,2],'Police power without independent review, indefinite incarceration and political repression subordinated personal freedom to the racial state.','Firearms access and health measures were racially selective; modern digital mechanisms are disclosed analogies rather than historical technology claims.',[1,3],{12:'Selective policing of speech is not universal protection of racial and religious equality.'}],
[[2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,-2,2],'Germanisation, forced population removal and racial belonging rejected equal multicultural public identity.','He classified ancestry above mere cultural assimilation; adopting customs alone would not qualify everyone for membership.',[1,2,3]],
[[2,-2,2,1,-2,-2,2,2,2,-1,1,2,-2,2,-2,-2],'Settlement policy privileged selected ethnic Germans while excluding and removing populations considered racially undesirable.','Ethnic German resettlement and family reproduction were promoted; ordinary skilled visas and numerical capacity limits are analogies to selective control.',[1,3]],
[[2,-2,2,2,-2,2,-2,2,-2,-2,2,-2,2,-2,2,-1],'Waffen-SS expansion, occupation and racial conquest supported armed power far beyond self-defence.','Late 1945 surrender feelers qualify never negotiating; they do not characterise most of this expansionist scope.',[1,3]],
[[2,-2,2,1,2,-2,2,-1,2,-2,2,1,2,-1,2,-1],'Racial imperial sovereignty and conquest rejected external legal limits.','Tactical alliances and international coordination could serve Nazi goals without granting independent supranational authority.',[1,2,3]],
[[1,1,1,2,1,2,1,1,-1,1,1,1,1,2,-1,2],'SS enterprises and forced-labour administration coexisted with private firms subordinated to state and war priorities.','Nazi anti-Marxism and retained private ownership mean coercive control must not be equated with public ownership of every business.',[1,3,4]],
[[2,-2,2,-1,2,-2,2,-1,2,-1,2,0,2,-1,2,-1],'Strategic self-sufficiency, conquest of resources and controlled external economic relations served national war aims.','Private industrial exchange and tactical supplies could continue; equal foreign taxes conflict with discriminatory national treatment.',[1,3,4],{12:'Administrative product taxation and nationality-based economic discrimination give competing indications.'}],
[[-1,2,-1,2,-1,2,-1,2,-2,2,-2,1,1,2,-1,2],'War production, forced labour and directed investment privileged state objectives over voluntary market allocation.','Private contracts and business initiative persisted under coercion; support for a minimum-wage floor is an uncertain in-group welfare analogy, not a claim about camp labour.',[1,3,4],{12:'In-group worker protection does not extend to forced labour or persecuted groups.',13:'Employer wage decisions operated within overriding state labour controls.'}],
[[1,1,1,1,0,1,-1,1,-1,1,1,1,1,1,1,1],'Selective support and settlement redistribution benefited the racially defined national community rather than universal income equality.','Property confiscation and forced dispossession are not compensated egalitarian transfers; advantages to selected settlers coexist with opposition to class socialism.',[1,3,4],{5:'National solidarity and preservation of elite property compete.',15:'Settlement redistribution shares the transfer mechanism but rejected compensation and universal eligibility.'}],
[[0,1,2,1,-1,1,2,-2,-2,1,-1,-1,2,0,-1,-1],'He promoted Germanic God-belief and ritual while subordinating churches to political SS authority.','Anti-Christianity is not atheism or equal secular neutrality; no independent clergy were to control the state.',[2,3,4],{1:'Civil political supremacy coexists with religious-racial justification.',14:'Favoured spiritual institutions and hostility to established churches compete.'}],
[[-1,2,-2,2,-2,1,-2,2,-2,2,-2,2,-2,1,-2,2],'Pronatalist racial family policy and repression of homosexuality imposed prescribed sex and reproductive roles.','He considered extra-marital reproduction and polygamy for selected SS men, qualifying a simple endorsement of conventional Christian monogamy.',[1,2,3,4]],
[[2,-1,2,-1,2,-2,1,0,2,-2,2,-1,2,-1,2,-1],'Military-industrial ambition and coercive racial experimentation privileged capability over informed-consent safeguards.','Agrarian romanticism and pseudoscience complicate modern technology analogies; support for particular experimental enhancements is not directly documented.',[1,2,3,4],{8:'Bodily control by the state and technical military advantage compete.'}],
[[-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-1,2],'He centralised police and security power, subordinating regional and occupied institutions to the Reich and SS.','Competing Gauleiter and other offices remained administrative rivals, not constitutional guarantees of local autonomy.',[1,3]],
[[-2,2,-2,2,-1,2,-1,2,-1,2,-1,2,-1,2,-2,2],'His racial breeding and ancestry programme treated purported hereditary traits as governing intelligence, character and sex roles.','SS education and ideological conditioning still mattered; support for biological explanations records his beliefs, not scientific endorsement of racial claims.',[1,2,3,4]]
]});
