import {save,source} from './assessment-helper.mjs';
save({id:'josip-broz-tito',name:'Josip Broz Tito',period:'Self-management and non-alignment, 1950–1980',lifespan:'1892–1980',role:'President of Yugoslavia',description:'Yugoslav leader assessed during his mature system of one-party government, federalism and worker self-management.',religion:{value:'none',refs:[1],reason:'Adult communist atheist identity is distinguished from Catholic upbringing.'},sources:[source('Josip Broz Tito — biography and reforms','https://en.wikipedia.org/wiki/Josip_Broz_Tito','Wikipedia'),source('State visit briefing — self-management, diplomacy and defence','https://history.state.gov/historicaldocuments/frus1977-80v20/d252','US Department of State','1978'),source('Josip Broz dit Tito','https://www.larousse.fr/encyclopedie/personnage/Josip_Broz_dit_Tito/146915','Larousse'),source('The Soviet intervention that never happened','https://www.wilsoncenter.org/blog-post/the-soviet-intervention-never-happened','Wilson Center'),source('Neighbors in Non-Alignment: Tito–Kim correspondence','https://www.wilsoncenter.org/blog-post/neighbors-non-alignment-tito-kim-correspondence-1973-1979','Wilson Center')],rows:[
[[-2,2,1,2,-2,-1,-2,2,2,-1,2,0,2,-1,2,-1],'He retained one-party leadership and became president for life; participation occurred within socialist institutions.','Worker participation and collective federal institutions qualify personal command but do not establish free national party competition.',[1,2,3],{12:'Internal institutional removal and entrenched lifelong leadership give opposing considerations.'}],
[[-1,2,-2,-1,2,2,2,2,-1,-1,2,2,-2,-2,-1,2],'Security police and repression of political challenges limited civil freedom, despite later easing of some controls.','Relative openness, travel and consumer culture compared with other socialist states qualify blanket censorship of all entertainment.',[1,2,3,4]],
[[-1,2,0,2,1,1,-1,-2,0,2,2,2,2,1,2,1],'He promoted brotherhood and unity with recognised nationalities and languages in a multinational federation.','Repression of nationalist movements and insistence on Yugoslav unity qualify allowing distinct identities to trump the shared state.',[1,2,3,4],{3:'Shared Yugoslav participation and retained national customs coexist.',9:'Federal common purposes and multiple recognised traditions compete.'}],
[[1,1,-1,1,1,-1,0,1,1,1,0,1,1,-1,1,1],'Non-aligned international exchange and labour mobility suggest regulated openness rather than ethnic migrant exclusion.','Domestic immigration is less explicit than emigration and diplomacy; modern visa mechanisms are contextual analogies.',[1,2,3],{7:'Labour mobility and economic capacity both matter.',11:'Administrative permission need not imply compulsory employer sponsorship.'}],
[[1,2,2,2,1,2,1,-1,2,-2,1,2,1,1,2,1],'He maintained substantial armed deterrence and citizen defence while mediating disputes and supporting negotiated disarmament.','Liberation-war experience and anti-colonial solidarity qualify a strict ban on all non-defensive military action.',[1,2,5]],
[[2,-1,2,-1,2,1,2,1,2,0,2,2,2,1,2,1],'Sovereign independence and non-alignment coexist with active UN engagement and international economic cooperation.','Cooperation and universal safeguards do not entail domination by either superpower or an external political federation.',[1,2,5],{10:'Human-rights diplomacy and one-party domestic sovereignty conflict under externally required law changes.'}],
[[-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2],'He favoured social ownership and worker-controlled enterprises rather than ordinary private capitalist ownership.','The bank’s binary public/private questions cannot directly express social ownership; public is used as the closer collective category, not a claim that all enterprises were state-administered. Small private farms and businesses remained.',[1,2,3]],
[[1,1,1,1,1,1,1,1,1,1,0,1,1,1,2,1],'International market participation and foreign joint ventures developed alongside protection of Yugoslav economic independence.','Quasi-market trade openness remained regulated and did not give foreign investors unlimited control over socially owned strategic firms.',[1,2,3],{11:'Retaliation and maintaining diverse trading relationships provide competing considerations.'}],
[[1,1,1,2,1,1,1,2,-1,2,-2,1,2,1,-1,1],'Enterprises had meaningful production and wage discretion under broader social planning and investment priorities.','This is neither complete ministerial production command nor laissez-faire; worker ownership is assessed separately from price and production coordination.',[1,2,3]],
[[2,-2,2,-2,2,-1,2,-1,1,-1,2,-1,2,-2,1,-1],'Social rights, public services and equalising regional development were major purposes of the socialist federation.','Self-management produced earnings differences and regional inequality; compensation mechanisms are modern analogies where no exact position is documented.',[1,2,3]],
[[2,-2,2,-2,2,-2,2,-2,1,-2,2,-1,2,-1,2,-2],'Civil socialist institutions governed independently of clerical authority and religious teaching.','Later accommodation with religious communities and Catholic diplomatic ties qualify assuming all private worship was prohibited.',[1,2,3]],
[[1,-1,1,-1,1,1,2,-1,1,1,0,-1,1,1,0,0],'Women’s public participation and reproductive reform accompanied modernising socialist institutions and some retained family conventions.','Contemporary same-sex marriage and identity curricula were outside the explicit programme; estimates should not conflate socialist modernisation with every present-day reform.',[1,3],{11:'Social equality and conventional historical terminology give conflicting indications.',15:'Education and equality are plausible but specific modern curricula are undocumented.',16:'Inherited national cultures and socialist reform give competing reasons.'}],
[[2,-1,2,1,2,-2,1,1,2,-1,1,1,1,1,2,1],'Industrialisation, infrastructure and nuclear energy show substantial technological ambition with negotiated safeguards.','Modern enhancement technologies are analogies; access to nuclear technology did not imply rejection of all safety controls.',[1,2,3]],
[[2,1,-2,2,2,-1,-1,1,1,1,1,1,1,1,2,2],'He decentralised economic and constitutional responsibilities to republics while enforcing unity and repressing separatist challenges.','The 1974 settlement significantly expanded republic autonomy; personal leadership and party control must not erase that change.',[1,2,3,4]],
[[2,-2,1,1,2,-1,2,-1,1,-1,1,1,1,-2,2,-1],'Anti-racial international solidarity and socialist education support a social account of cooperative habits and opportunity.','His political programme does not quantify each temperament or attention mechanism; recognition of national cultures is not an inherited-race theory.',[1,2,3]]
]});
