import {save,source} from './assessment-helper.mjs';
save({id:'thomas-sewell',name:'Thomas Sewell',period:'Australian neo-Nazi organising, 2017–2026',lifespan:'1993–',role:'Australian neo-Nazi organiser',description:'Australian neo-Nazi organiser assessed through his stated racial programme, political organising and public actions.',religion:{value:'undisclosed',refs:[1],reason:'Reviewed biographical evidence does not establish a personal faith. Neo-Nazi identity and cross imagery are not sufficient to infer Christianity or pagan identity.'},sources:[source('Thomas Sewell — views and organising','https://en.wikipedia.org/wiki/Thomas_Sewell_(neo-Nazi)','Wikipedia'),source('Sewell’s threatened violence and racial programme','https://www.abc.net.au/news/2024-11-13/neo-nazi-issues-rise-in-rhetoric-threats-thomas-sewell/104585008','Australian Broadcasting Corporation','2024-11-13'),source('Neo-Nazi groups announce disbandment','https://www.sbs.com.au/news/article/national-socialist-network-disbanding-hate-speech-laws/szhltr6lp','SBS News','2026-01-16'),source('Sewell seeks bail change to organise a political party','https://www.abc.net.au/news/2025-04-10/neo-nazi-thomas-sewell-starting-political-party/105160428','Australian Broadcasting Corporation','2025-04-10'),source('Sewell’s legal challenge and Mason appearance','https://www.abc.net.au/news/2026-05-16/thomas-sewell-appears-with-us-extremist-james-mason/106683510','Australian Broadcasting Corporation','2026-05-16'),source('Sewell’s continued broadcasting','https://www.abc.net.au/news/2026-06-03/neo-nazi-thomas-sewell-broadcasting-hate-on-instagram/106754856','Australian Broadcasting Corporation','2026-06-03')],rows:[
[[-1,1,-2,2,-1,-1,-1,2,2,-1,2,-1,2,-1,1,1],'He rejected democracy in revolutionary organising and professed Hitler as leader, while later seeking electoral registration and court protection.','Using elections and legal appeals tactically is evidence of some procedural engagement, not proof of an equal pluralist programme.',[1,4,5]],
[[1,1,1,-1,1,1,-1,1,-1,2,1,-2,1,1,1,1],'He demands speech, anonymity and protest rights for his movement while promoting coercive racial exclusion and threatened violence.','Rights asserted against his current prosecution do not establish rights for all under his proposed racial state; vaccination response is weak contextual opposition to intrusion, not an attributed vaccine statement.',[1,2,3,4,5],{7:'Opposition to coercive restrictions on his community is the context; no direct vaccine declaration is established.',13:'He uses obstructive marches but threatens opponents; universal peaceful protest remains qualified.'}],
[[2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,-2,2],'His explicit white-Australia goal excludes equal multicultural institutional membership.','Ancestry matters beyond adoption of customs; selected European traditions can differ without equal inclusion of all cultures.',[1,2,6]],
[[2,-2,2,1,-2,-2,2,2,2,-1,1,2,-2,2,-2,-2],'He advocates white-only national belonging and removal of other racial populations.','His own cross-border origin shows selected European migration can be accepted; numerical skills and housing criteria are contextual analogies.',[1,2,6]],
[[1,-1,1,1,-1,1,-1,1,1,-2,1,-1,1,-1,1,-1],'Political-soldier language and conditional threats of violence support coercive force for racial goals.','Domestic street violence does not document every foreign military policy; overseas force, autonomous weapons and conscription are uncertain extensions of militant national organisation.',[1,2,5]],
[[2,-2,2,1,2,-2,2,-1,2,-2,2,1,2,-1,2,-1],'White national sovereignty and rejection of globalism suggest opposition to externally imposed multicultural or human-rights limits.','International white-nationalist contacts show cooperation among selected groups rather than submission to universal institutions.',[1,2,5,6]],
[[1,1,1,1,1,1,1,1,-1,1,1,1,1,2,-1,1],'His national-socialist identification and recruitment of marginalised workers suggest conditional private enterprise alongside strategic collective provision.','No detailed personal ownership programme is established; these weaker estimates derive from his racial-national community goals, not copied historical Nazi economics.',[1,2,6]],
[[1,-1,1,-1,1,-1,1,-1,1,-1,1,1,1,-1,2,-1],'National self-preservation and opposition to globalism suggest protecting domestic strategic production.','International contacts and online organising do not settle trade tariffs; economic mechanisms remain low-confidence contextual estimates.',[1,2,5]],
[[1,1,1,1,1,1,1,1,-1,1,-1,1,1,1,-1,1],'National community priorities suggest overriding selected market outcomes while retaining routine enterprise decisions.','His public record is mainly race and organising rather than economic coordination; neither comprehensive planning nor universal deregulation is established.',[1,2,6]],
[[1,-1,1,1,1,-1,1,1,-1,1,1,-1,1,-1,-1,1],'Recruitment of economically marginalised white workers suggests targeted national solidarity rather than universal egalitarianism.','Racial exclusion and community hierarchy qualify broad redistribution; no precise tax or inheritance platform was established.',[1,2,6]],
[[1,-1,2,1,-1,1,2,-1,-1,1,-1,1,2,1,1,-1],'Political racial authority is more explicit than clerical rule, while inherited spiritual traditions may receive privileged public recognition.','Cross imagery is not personal faith evidence or a documented religious-law proposal; every religious-government mechanism is a contextual estimate.',[1,2,6]],
[[-2,2,-1,2,-2,2,-1,2,-2,2,-2,2,-2,1,-2,2],'Anti-trans mobilisation and family-racial reproduction rhetoric favour restrictive sex and family conventions.','Protecting his own children does not document exact abortion exceptions or a complete marriage code; those choices are disclosed estimates.',[1,2,6]],
[[1,1,1,1,1,-1,-1,1,1,1,0,1,1,1,1,1],'Technical communication and organised physical capability suggest practical adoption under racial-national priorities.','No detailed environmental or biotechnology programme is established; racial enhancement and bodily-risk caution compete, with substantial uncertainty.',[1,2,5,6],{11:'Individual enhancement and concerns about bodily control compete.'}],
[[-1,2,-2,2,-1,1,-1,2,-1,2,-1,2,-2,2,-1,2],'A single white national political programme suggests central authority over conflicting regional or indigenous claims.','Local training clubs are organisational decentralisation, not evidence of protected constitutional regional autonomy.',[1,2,5,6]],
[[-1,2,-2,1,-1,1,1,1,-1,1,1,1,-1,2,-1,2],'Bloodline and racial membership rhetoric imply inherited group traits, alongside emphasis on training young men and changing their habits.','The genetic IQ and crime mechanisms are contextual extrapolations with uncertainty; recording his racial beliefs does not endorse their scientific validity.',[1,2,6],{7:'His actual training and recruitment demonstrate an important learned component.',11:'Perceived external threats are also cultivated through propaganda.'}]
]});
