import {save,source} from './assessment-helper.mjs';
save({id:'charlie-kirk',name:'Charlie Kirk',period:'Mature advocacy, 2021–September 2025',lifespan:'1993–2025',role:'Founder of Turning Point USA',description:'American conservative activist assessed during his later advocacy of Christian national identity, private enterprise and restrictive immigration.',religion:{value:'christian',refs:[1,2],reason:'He explicitly described himself as an evangelical Christian; this identity does not alone determine religious-government answers.'},sources:[source('Charlie Kirk’s political views','https://abcnews.com/US/charlie-kirks-political-views-conservative-activist/story?id=125626091','ABC News','2025-10-14'),source('Mission and founder record','https://tpusa.com/about/','Turning Point USA'),source('The origins of the new right and its future','https://americanmind.org/memo/the-origins-of-the-new-right-and-its-future/','The American Mind','2022'),source('Charlie Kirk — positions and changes','https://en.wikipedia.org/wiki/Charlie_Kirk','Wikipedia'),source('Trump tariffs and domestic manufacturing','https://www.charliekirk.com/news/trumps-new-tariffs-trigger-manufacturing-boom-for-u-s-companies','Charlie Kirk','2025-05-07'),source('No Forced Vax campaign and Kirk statement','https://www.breitbart.com/tech/2021/07/09/no-forced-vax-turning-point-usa-launches-campaign-against-medical-apartheid-on-college-campuses/','Breitbart','2021-07-09')],rows:[
[[1,-2,1,1,1,-1,1,2,-1,-1,2,1,1,-1,-1,-2],'Electoral mobilisation and constitutional republican institutions were core methods, with strong elected executive leadership.','His 2020-election claims and support for Trump qualify confidence in equal opposition; voter ID alone is not autocratic evidence.',[2,3,4]],
[[2,-1,2,-1,-2,-1,-2,0,-1,2,1,-2,0,1,2,-1],'He strongly defended firearms, opposed vaccination mandates and rejected legal penalties for hate speech.','Support for law enforcement and regulating platforms conflicts with unrestricted liberty; parental censorship of sexual material qualifies adult media freedom.',[1,3,4,6],{8:'Crime prevention and opposition to pre-emptive state restriction compete.',13:'Freedom of protest and objection to obstructive demonstrations compete.'}],
[[2,-2,2,-1,2,-1,2,-2,2,-1,2,-1,2,-1,-1,2],'His later advocacy prioritised English, Christian national culture and assimilation over plural institutional accommodation.','He welcomed individual gay conservative allies and described Christian Indian majority as compatible with America; cultural membership is not solely ancestry.',[1,3,4]],
[[2,-2,2,0,-1,-2,2,2,2,-1,1,2,-1,2,-1,-2],'He called for major immigration restriction, opposing illegal migration and some legal work visas.','Earlier acceptance of lawful migration and family life qualify a claim that every entrant was always rejected.',[1,4],{4:'Family unity and later proposals to halt immigration compete.'}],
[[1,2,2,1,1,-1,1,-1,2,-2,1,1,1,1,2,1],'Strong national defence and deterrence coexist with opposition to Ukraine aid and US involvement in Iran’s 2025 war.','Support for Israel and border force mean opposition to selected wars is not unconditional pacifism.',[1,4]],
[[2,-2,2,1,2,-1,2,-1,2,-1,2,-1,2,0,2,-1],'National sovereignty and resistance to globalism were explicit, while allied cooperation remained possible.','Free-market international exchange and support for Israel qualify isolation from all agreements.',[2,3,4],{14:'Commercial exchange and sovereign discretion over tariffs compete.'}],
[[2,-1,2,-2,1,-1,2,-2,2,-2,2,-2,2,-1,2,-2],'Free enterprise and private property were explicit institutional aims.','Support for state intervention against ideological opponents and strategic protection does not establish universal privatisation of every network.',[2,3]],
[[2,0,2,1,1,-1,1,1,1,1,2,1,2,0,2,1],'Later support for Trump’s tariff strategy and domestic production modifies earlier free-market rhetoric.','Voluntary international trade remained valuable; tariffs were presented partly as leverage toward reciprocal exchange rather than permanent closure.',[2,5,4],{2:'Free-market exchange and protection of domestic production compete.',14:'Negotiated barrier removal and reduced strategic dependence compete.'}],
[[2,-2,2,-1,2,-1,2,-1,2,-1,1,-1,2,-1,2,-2],'Limited economic government, enterprise competition and market prices were stated priorities.','His call for government regulation of large technology firms is a material exception to laissez-faire.',[2,3]],
[[-2,2,-1,2,-1,2,-1,1,-2,2,-1,2,-1,2,-1,2],'He emphasised earnings, fiscal restraint and personal responsibility over redistribution to equalise incomes.','Basic assistance and family priorities can coexist with this orientation; opposition to equality programmes is not proof that all welfare should vanish.',[2,3,4]],
[[-1,1,1,2,-1,1,1,0,-2,1,-2,2,1,1,-1,-1],'Later advocacy rejected separation of church and state and sought Christian renewal in national institutions.','He used constitutional civil institutions rather than explicitly assigning all lawmaking or courts to clergy.',[1,3,4],{8:'Christian policy influence is clear; a formal clerical veto is not.',3:'Civil elected government can pursue his Christian policy goals.',7:'Biblically influenced legislation is not identical to religious courts.'}],
[[-2,2,-1,2,-2,2,-2,2,-1,2,-2,2,-1,2,-2,2],'He promoted marriage, distinct sex roles and nearly complete abortion prohibition, opposing LGBT school curricula.','Acceptance of gay political allies qualifies claims of complete social exclusion without reversing his traditional marriage definition.',[1,4]],
[[1,1,2,1,1,-2,-1,2,1,-1,0,1,-1,1,2,1],'Economic growth and infrastructure coexist with religious bioethical limits and scepticism about medical interventions.','Climate scepticism is not itself evidence about every technology; reproductive enhancement conflicts with his conception-based ethics.',[2,3,4,6],{11:'Personal freedom and caution about altering human capacities compete.'}],
[[1,1,-2,1,2,-1,1,1,1,-1,1,0,-1,-1,1,2],'Constitutional federalism and local self-government coexist with national border, security and culture priorities.','A national culture campaign can support nationwide interventions against local policy; he did not endorse unconditional state secession.',[2,3,4],{12:'State policy freedom and a national pro-life programme compete.'}],
[[1,0,-2,1,1,1,1,0,1,1,1,1,1,0,1,1],'He treated sex differences as natural while also attributing behaviour and inequality to culture, family and welfare incentives.','Racial generalisations and anti-DEI claims alone do not establish a genetic theory of racial crime or IQ; those mechanisms have conflicting contextual indications.',[1,3,4],{2:'Culture and individual aptitude claims do not specify national inherited IQ differences.',8:'Moral character can be understood as both cultivated and natural.',14:'His documented cultural incentive account qualifies racial rhetoric; inherited violence is not explicitly established.'}]
]});
