import {save,source} from './assessment-helper.mjs';
save({id:'julius-malema',name:'Julius Malema',period:'EFF leadership, 2013–2026',lifespan:'1981–',role:'Leader of the Economic Freedom Fighters',description:'South African opposition leader advocating land redistribution, nationalisation and pan-African solidarity.',religion:{value:'christian',refs:[4],reason:'He explicitly called Jesus Christ and God his inspiration in a 2014 interview. Continuing identity is inferred; church attendance and secular policy are separate.'},sources:[source('Malema’s local-government manifesto launch speech','https://effonline.org/wp-content/uploads/2024/09/26-09-2021-EFF-PRESIDENT-AND-COMMANDER-IN-CHIEF-JULIUS-MALEMA-SPEECH-ON-THE-EFF-LOCAL-GOVERNMENT-ELECTIONS-MANIFESTO-LAUNCH.pdf','Economic Freedom Fighters','2021-09-26'),source('Julius Sello Malema','https://sahistory.org.za/people/julius-sello-malema?page=1','South African History Archive'),source('Malema’s political plan to become SA’s number two','https://www.dailymaverick.co.za/article/2024-05-11-congeniality-campaign-eff-leader-julius-malemas-political-plan-to-become-sas-number-two/','Daily Maverick','2024-05-11'),source('Malema: God is my inspiration','https://www.news24.com/malema-god-is-my-inspiration-20140501','News24','2014-05-01'),source('Julius Malema — EFF programme and controversies','https://en.wikipedia.org/wiki/Julius_Malema','Wikipedia')],rows:[
[[2,-1,2,1,2,1,1,2,-1,1,1,2,1,1,-2,-2],'EFF contests competitive elections, parliamentary scrutiny and coalitions, seeking accountable government.','Revolutionary rhetoric and disciplined party leadership qualify direct citizen control; earlier ANC attacks on judges precede this scope.',[1,2,3,5]],
[[1,-1,-1,1,1,-1,1,1,1,1,1,0,2,1,2,-2],'Accountable administration and mass protest coexist with enforcement against violent crime and public-health obligations.','His defence of controversial liberation songs suggests resistance to expansive speech prohibitions; that is not a defence of all racial hatred.',[1,2,5],{12:'Anti-racism and opposition to bans on struggle songs pull in different directions.'}],
[[-1,2,-1,2,1,2,-1,-1,0,2,1,1,-1,1,2,-1],'Pan-African solidarity and recognition of indigenous languages and diverse communities support plural inclusion.','An African decolonial common identity is prominent; plural recognition does not make all community practices override national equality.',[1,2,5],{9:'A common public calendar and recognition of multiple communities have competing practical claims.'}],
[[-2,2,-2,2,2,1,-2,-2,-1,2,-1,-1,2,-2,2,1],'He rejects xenophobic exclusion and advocates African freedom of movement and protection of migrants.','Exact sponsorship and graduate-residency mechanisms are contextual estimates, not personal questionnaire answers.',[1,5]],
[[1,1,1,1,-1,0,1,-1,1,-2,1,1,1,1,1,1],'Anti-colonial solidarity and strong African capacity coexist with opposition to imperial intervention.','Militant liberation rhetoric does not prove willingness to wage every foreign war; conscription has countervailing defence and liberty considerations.',[1,2,5],{6:'Military readiness and opposition to coercive colonial institutions give mixed indications.'}],
[[1,-1,1,2,1,1,1,1,-1,1,1,2,0,1,-1,1],'African integration and solidarity favour shared institutions while resisting Western domination of national policy.','Continental integration is stronger than universal delegation to any international organisation; border sovereignty conflicts with pan-African openness.',[1,5],{13:'National control and continental freedom of movement compete.'}],
[[-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2],'His programme explicitly nationalises mines, banks and strategic industries and replaces outsourced public services.','Small producers and businesses remain important; collective control does not document abolishing every private enterprise.',[1,2,5]],
[[2,-1,2,0,2,-1,2,-1,2,-1,1,1,2,-1,2,1],'Protected industrial development and local procurement accompany continental economic exchange.','Pan-African trade and modern productive inputs qualify autarky; unrestricted lowest-price sourcing conflicts with local development.',[1,5],{4:'Access to productive inputs and domestic procurement obligations compete.'}],
[[-1,2,-1,2,-1,2,-1,2,-1,2,-2,2,1,2,-2,2],'National economic direction, public finance, minimum wages and rent affordability are central redistributive tools.','Workers’ bargaining and smaller businesses leave some decentralised decisions; modern currency competition is inferred from public monetary control.',[1,2,5]],
[[2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,1,-2],'Redistribution, free basic services and improved worker incomes are central to economic emancipation.','Land expropriation without compensation differs from the statement’s compensated redistribution; agreement estimates shared distributive aim without claiming the compensation proposal is his.',[1,2,5],{15:'His explicit no-compensation demand qualifies this compensated proposal.'}],
[[2,-1,2,-1,2,-1,2,-1,-1,0,1,1,2,0,2,-1],'Constitutional government and equal public rights are inferred to outweigh binding clerical control.','His personal Christianity and customary traditional leadership do not establish a religious-law programme; public ceremonies can retain religious practices.',[1,4,5],{10:'Faith-informed community practice and secular public equality compete.',14:'Religious freedom and equal treatment of charities compete.'}],
[[2,-1,2,-1,2,0,2,-1,2,-1,1,-1,2,0,2,1],'EFF consultation explicitly included LGBTQ communities and opposition to homophobia and gender violence.','Traditional leaders and family customs remain part of its constituency; modern language conventions are less precisely stated than equal protection.',[1,5],{6:'Family stability and equal recognition of other households coexist.',14:'Structural transformation and social consensus provide competing timing considerations.'}],
[[1,1,2,1,0,-1,1,1,1,1,0,1,0,1,2,1],'Industrial development and expanded infrastructure are favoured with public health, environmental and worker protections.','Productive technology is not an endorsement of untested enhancement or unrestricted job displacement.',[1,5],{5:'Productivity and employment protection compete.',11:'Innovation and uncertain neurological harms compete.',13:'Scientific capacity and limits on enhancement compete.'}],
[[0,2,-2,2,1,2,-1,2,1,2,1,2,1,2,1,2],'A national redistribution programme coexists with accountable municipal service delivery and local participation.','Consultation with traditional leaders does not imply independent hereditary vetoes or unconditional secession.',[1,5],{1:'Local responsiveness and uniform national redistribution compete.'}],
[[2,-2,2,-1,2,-1,2,-1,1,-1,2,0,1,-2,2,-2],'Colonial dispossession, unequal resources and structural discrimination explain persistent social differences in his programme.','African identity and revolutionary language are not evidence of inherited racial IQ or violent tendencies; individual temperament is less specified.',[1,2,5],{12:'Individual biology and social experience both remain plausible within his structural account.'}]
]});
