import {save,source} from './assessment-helper.mjs';
save({id:'mark-carney',name:'Mark Carney',period:'Federal leadership, March 2025–October 2026',lifespan:'1965–',role:'Prime Minister of Canada',description:'Canadian prime minister assessed through his programme of economic investment, social protection and national sovereignty.',religion:{value:'christian',refs:[1],reason:'The biography identifies him as a practising Catholic; identity is separated from the civil foundations of policy.'},sources:[source('Mark Carney — biography and political positions','https://en.wikipedia.org/wiki/Mark_Carney','Wikipedia'),source('Canada Strong — 2025 election platform','https://liberal.ca/wp-content/uploads/sites/292/2025/04/Canada-Strong.pdf','Liberal Party of Canada','2025-04'),source('Prime Minister Carney launches Build Canada Homes','https://www.pm.gc.ca/en/news/news-releases/2025/09/14/prime-minister-carney-launches-build-canada-homes','Prime Minister of Canada','2025-09-14'),source('Canada’s first Defence Industrial Strategy','https://www.pm.gc.ca/en/news/news-releases/2026/02/17/prime-minister-carney-launches-canadas-first-defence-industrial','Prime Minister of Canada','2026-02-17'),source('Canada’s Liberals choose Mark Carney to replace Trudeau','https://apnews.com/article/1547a81c8c3ff498438f10bddd178116','Associated Press','2025-03-09')],rows:[
[[2,1,2,1,2,-1,2,2,-2,-1,2,2,1,-1,-2,-2],'He sought an electoral mandate and a parliamentary government with institutional accountability and delegated expert administration.','Central-bank experience supports professional delegation but does not establish rejection of elections or parliamentary removal.',[1,2,5]],
[[2,1,-2,0,1,0,1,1,1,1,1,2,1,0,2,-2],'The programme combines firearms restrictions, additional police capacity and protections against hate with civil rights and due process.','Security funding does not establish endorsement of unlimited tracking, indefinite detention or censorship of ordinary institutional criticism.',[1,2],{4:'Existing legal personal choices and public-health limits coexist; a general unrestricted drug-use claim extends beyond his programme.',6:'Crime prevention and privacy place conflicting demands on storing nonsuspects’ movements for years.',14:'Accountability and protection of confidential information conflict when disclosure procedures are unspecified.'}],
[[-1,2,-1,2,1,2,-1,-1,-1,2,2,1,1,2,2,0],'His programme recognises Indigenous cultures, French-language identity and Canada’s plural society while strengthening a shared Canadian public culture.','Promoting Canadian content and francophone migration qualifies cultural neutrality; plural identities do not override all common institutions.',[1,2],{16:'Shared participation and preservation of distinct identities both receive explicit support, with neither an exclusive integration goal.'}],
[[2,1,-1,2,1,-2,2,2,2,1,1,1,1,-1,1,1],'He proposed reduced immigration totals linked to capacity while maintaining lawful skills, family and humanitarian pathways.','Capacity-based restrictions differ from racial or blanket cultural exclusion; removals of failed asylum claims follow process.',[1,2]],
[[1,1,2,1,0,-1,-1,-1,1,-2,1,1,1,0,1,1],'Expanded defence investment and domestic defence industry support credible deterrence and cooperation with allies.','Strategic autonomy is not a general permission for aggressive war; negotiated diplomacy and defence capability remain concurrent objectives.',[2,4],{5:'Protecting sovereignty supports defensive action, but the programme does not restrict every possible mission solely to responding to an attack.',14:'Deterrence and avoiding escalation are both important; neither universally takes precedence.'}],
[[1,1,0,2,1,1,1,2,-1,1,2,2,1,2,2,1],'He defends Canadian sovereignty against US pressure while supporting negotiated international cooperation and diversified trade.','Retaining a national currency and sovereign border administration coexist with alliances and agreed international rules.',[1,2,5],{3:'Domestic constitutional authority and treaty obligations can conflict; no categorical ordering of every international court case is established.'}],
[[2,1,2,-1,-2,1,1,0,1,2,1,-1,1,1,1,2],'The programme retains a mainly privately owned economy with public broadcasting, public infrastructure and a federal affordable-housing agency.','Public investment and procurement should not be mistaken for public ownership of every recipient firm or of all natural resources.',[2,3,4],{8:'Public financing institutions and private banking coexist, but the programme does not establish a general commercial public-bank commitment.'}],
[[1,1,2,1,1,-1,1,1,1,1,2,2,1,1,2,1],'He combines trade diversification and open internal commerce with Canadian procurement, strategic resilience and retaliatory tariffs.','Retaliation against the US does not demonstrate opposition to all international trade; preferences differ for strategic goods and ordinary commerce.',[2,4,5]],
[[2,-2,2,1,2,0,2,1,2,2,-1,1,2,-1,1,-2],'Private market production is combined with targeted industrial investment, competition policy and major public projects.','Directed public spending does not constitute ordinary compulsory production quotas; his former central-bank role qualifies political direction of monetary policy.',[1,2,3,4],{6:'Cost-of-living relief and competitive pricing coexist; subsidies are not generally mandatory essential-goods price ceilings.'}],
[[1,-1,1,0,2,1,-1,-1,0,0,1,1,1,-2,-1,-1],'Targeted benefits and fair taxation coexist with middle-income tax reductions and growth-oriented investment.','This is not an unconditional tax-and-transfer equalisation programme; no general inheritance, wealth or land transfer programme is established.',[1,2],{4:'Basic protection and meaningful participation both matter, making a restriction to a minimal safety net too narrow.',9:'Fairness supports sharing burdens but a broad accumulated-wealth transfer tax is not an explicit policy.',10:'Spending restraint and sufficient benefits pull in opposite directions.'}],
[[2,-2,2,-1,2,-2,2,-2,-1,-1,0,1,2,1,2,-1],'Policy is articulated through civil institutions and public purposes rather than approval by Catholic authorities.','Personal Catholic faith and inherited public traditions are distinct from religious control of legislation.',[1,2],{11:'Public neutrality and inherited cultural symbols can coexist; a categorical removal requirement is stronger than the documented programme.'}],
[[1,-1,2,-1,2,-1,2,-1,2,-1,1,-1,2,0,2,0],'The platform protects equal citizenship and reproductive and sexual-minority rights while accommodating cultural continuity.','Liberal rights commitments do not imply that every tradition must change immediately or that historical customs have no value.',[1,2],{14:'Reform and predictable institutions both matter under a broad gradualism rule.',16:'Inherited culture can be valued without making preservation unconditional.'}],
[[2,-1,2,1,2,-1,1,1,2,-1,0,1,0,1,2,1],'His programme promotes faster major-project decisions, AI investment and technology-led growth, with environmental and medical safeguards.','Technology support is more direct than his position on irreversible neurological or embryo enhancements, which remain uncertain extrapolations.',[1,2,3],{11:'Personal choice and irreversible neurological risk give opposing considerations beyond the infrastructure programme.',13:'Research innovation and embryo ethical concerns are both plausible; no specific enhancement endorsement is documented.'}],
[[2,1,-2,1,2,-1,1,-1,2,1,1,1,2,0,2,2],'He proposes a more integrated national economy through cooperation with provinces, territories and Indigenous governing bodies.','Federal coordination does not abolish provincial constitutional responsibilities or establish one central police authority.',[1,2,3],{14:'Common economic rules and provincial tax autonomy both have weight; tax competition is not specifically prohibited.'}],
[[1,-2,1,1,1,1,1,-1,1,-1,1,1,1,-2,1,-1],'Education, inclusion and opportunity support a qualified account of socially learned behaviour alongside individual biological variation.','The programme supplies contextual evidence, not a quantified theory of the inherited and learned causes of every psychological trait.',[1,2]]
]});
