import {save,source} from './assessment-helper.mjs';
save({id:'allegra-spender',name:'Allegra Spender',period:'Federal parliamentary positions, 2022–October 2026',lifespan:'1978–',role:'Australian Member of Parliament for Wentworth',description:'Australian parliamentarian assessed through tax reform, climate policy, public integrity and civil equality.',religion:{value:'undisclosed',refs:[1],reason:'The public biography reviewed does not establish a declared religious identity. Constituency religion and school history are not substituted for her own identity.'},sources:[source('Allegra Spender — biography and political positions','https://en.wikipedia.org/wiki/Allegra_Spender','Wikipedia'),source('Tax reform proposals','https://www.allegraspender.com.au/tax','Allegra Spender'),source('Economy policy','https://www.allegraspender.com.au/economy_1','Allegra Spender'),source('Refugees policy','https://www.allegraspender.com.au/refugees_policy','Allegra Spender'),source('LGBTIQ+ policy','https://www.allegraspender.com.au/LGBTQi','Allegra Spender'),source('Integrity policy','https://www.allegraspender.com.au/integrity_1','Allegra Spender'),source('AUKUS parliamentary statement','https://www.allegraspender.com.au/aukus','Allegra Spender','2026-06-04'),source('Climate-focused independents and Australia’s election','https://time.com/6181345/climate-independents-australia-election/','TIME','2022'),source('Natural environment policy','https://www.allegraspender.com.au/natural_environment','Allegra Spender'),source('Anti-vilification law and free expression','https://www.allegraspender.com.au/12_jan','Allegra Spender','2026-01-12')],rows:[
[[2,1,2,1,2,1,2,2,-2,1,1,2,1,1,-2,-2],'Her programme emphasises competitive representation, transparent donations, parliamentary accountability and expert-informed policy.','Community consultation and independent advice do not establish that every issue must be decided by binding public vote.',[1,6]],
[[2,-1,-2,1,1,-1,1,1,2,1,1,2,2,2,2,-2],'She expressly defends disagreement, protest, criticism and offence alongside prohibiting intentional serious vilification and protecting whistleblowers.','Protecting expression does not repeal bounded safety rules; support for strong border laws is qualified by objections to rushed restrictions on asylum rights.',[4,5,6,10]],
[[-1,2,-1,2,-1,2,-1,-1,-1,2,1,1,-1,2,2,-1],'She supports diverse communities, equal recognition and Indigenous respect within a shared Australian civic life.','Representation of Wentworth’s Jewish community is not evidence that a single religion should dominate national culture.',[1,4,5,6]],
[[1,1,-1,2,2,-1,0,0,1,1,-1,0,2,-2,2,1],'She supports stronger humanitarian intake, permanent protection and community sponsorship while explicitly retaining secure borders and law.','More humane asylum policy is not unconditional residence for every irregular entrant; housing capacity and lawful pathways remain relevant.',[1,4],{7:'Labour needs and capacity-based administration both matter; no blanket employer-demand rule is documented.',8:'Economic and housing benefits must be balanced; the record does not establish a general reduction regardless of benefit.',12:'Education and regulated visas both matter; graduation alone is not a fully specified entitlement.'}],
[[0,2,1,1,1,-1,1,-1,2,-2,1,2,0,1,1,1],'She values defence capability but questions AUKUS cost, strategic purpose and delivery and seeks public scrutiny.','Her statement that some submarines are preferable to none is direct counter-evidence to treating her as an absolute pacifist.',[1,7],{1:'Defensive national interests and opposition to unexamined escalation make the broad non-attack force permission conditional.',13:'Credible deterrence and diplomacy conflict under a general threat-for-concessions rule.'}],
[[1,1,0,1,1,1,0,2,-1,1,2,2,1,2,1,1],'Climate cooperation and humanitarian principles accompany independent Australian decision-making and scrutiny of security alliances.','International cooperation does not transfer every domestic law, monetary decision or entry decision to external institutions.',[4,7,8,9],{3:'Domestic law and accepted international obligations provide competing responsibilities.',7:'National prosperity and common obligations both matter, making an unconditional hierarchy too broad.'}],
[[2,1,2,-1,-1,1,2,0,1,1,2,-1,1,1,1,2],'She encourages private business, investment and competition while supporting public infrastructure and affordable housing institutions.','Support for public funding is not necessarily public ownership; no programme to nationalise banks or extractive industry is documented.',[1,2,3],{8:'Public financing capacity and private commercial banking offer different tools; no general public-bank programme is established.'}],
[[-1,2,-1,2,0,1,0,2,0,2,0,2,1,2,1,2],'Her business and productivity programme suggests open competition and trade with proportionate security and environmental safeguards.','Domestic transition investment is not itself an import tariff; trade-specific answers beyond the programme remain contextual estimates.',[2,3,8,9],{5:'Supply resilience and import affordability compete.',7:'New-industry support and lower consumer costs give opposing reasons for import restrictions.',9:'Agricultural resilience and competition provide competing considerations.',11:'Retaliation may defend access but can increase costs.'}],
[[2,-2,2,1,2,-1,2,-1,2,1,-1,1,2,-1,1,-2],'She proposes a competitive business environment and productive capital allocation with selective climate investment and accountable public expenditure.','Tax incentives and guardrails are distinct from compulsory national production or government control of all bank lending.',[2,3,6,9]],
[[1,0,1,1,2,1,-1,0,-1,0,1,1,1,-2,-1,1],'Her tax proposal shifts burden from work toward investment income while retaining fiscal neutrality and lowering income tax rates.','Reducing concessions on asset earnings is not a tax on wealth balances; she explicitly opposes taxation of unrealised gains and does not propose higher total taxation.',[1,2,3],{2:'Income fairness and reward for effort are both purposes, rather than either unlimited equalisation or rejection of redistribution.',8:'Targeted welfare and humane assistance do not establish arbitrary expiry for all capable recipients.',10:'Budget restraint and adequate social provision pull in opposing directions.'}],
[[2,-2,2,-1,2,-2,2,-2,0,-1,1,1,2,0,2,-1],'Civil equal-rights policy and protection against discrimination apply independently of religious approval.','Opposing discrimination in religious schools does not prohibit personal faith or erase all religious holidays and community traditions.',[1,5,6],{9:'Civic inclusion and freedom of religious expression give competing considerations for every official ceremony.',14:'Religious and charitable institutional purposes may overlap; no specific tax-exemption programme is documented.'}],
[[2,-1,2,-1,2,-1,2,-1,2,-1,2,-1,2,0,2,0],'She supports LGBTQ equality, gender-affirming care and freedom from religious-school exclusion alongside wider civic inclusion.','Equal recognition does not require every inherited custom to be immediately discarded.',[1,5],{14:'Change and institutional stability both have value.',16:'Traditions may be freely retained without a universal preservation obligation.'}],
[[1,1,1,2,1,1,1,2,2,1,0,2,-1,2,2,2],'Her programme combines business innovation and clean-energy development with environmental protection and evidence-informed safeguards.','Infrastructure support qualifies blanket habitat preservation; human enhancement is less directly documented and remains a cautious analogy.',[2,3,8,9],{11:'Autonomy and uncertain irreversible neurological effects give opposing considerations.'}],
[[2,0,-1,1,2,-1,1,-1,2,1,2,1,2,0,2,2],'Constituency consultation and protected communities coexist with national climate, tax and social programmes.','Local participation is not unlimited secession authority; federal coordination does not establish one centrally directed police system.',[1,3,6,9],{2:'Constitutional allocation and national programme delivery divide responsibility.',14:'Fair national taxation and regional fiscal discretion give competing considerations.'}],
[[1,-2,1,1,2,1,1,-1,1,-1,1,1,1,-2,1,-1],'Her education and opportunity work and explanations of systemic disadvantage emphasise social circumstances while allowing individual biological variation.','Fiscal and equality arguments do not quantify every psychological trait; the specific culture–nature answers are educated contextual assumptions.',[1,2,5]]
]});
