import {save,source} from './assessment-helper.mjs';
save({id:'ian-smith',name:'Ian Smith',period:'Rhodesian premiership, 1964–1979',lifespan:'1919–2007',role:'Prime Minister of Rhodesia',description:'Rhodesian prime minister assessed during minority-rule government, unilateral independence and the later internal settlement.',religion:{value:'undisclosed',refs:[3],reason:'Reviewed evidence does not establish personal religious identity; public Christian traditions do not establish personal faith.'},sources:[source('Rhodesia’s 1969 constitutional proposals','https://history.state.gov/historicaldocuments/frus1969-76v28/d3','US Department of State','1969-02-18'),source('Interview with Ian Smith','https://magill.ie/archive/interview-ian-smith','Magill','1969'),source('Ian Smith — premiership, religion and policy','https://en.wikipedia.org/wiki/Ian_Smith','Wikipedia'),source('US policy review of the Rhodesian settlement','https://history.state.gov/historicaldocuments/frus1977-80v16/d264','US Department of State','1977')],rows:[
[[1,1,-2,2,-1,-1,-1,2,2,-1,2,1,2,-1,-1,-1],'He retained elections and parliament for a racially unequal restricted franchise and resisted majority rule for most of this period.','Acceptance of transition and the 1978–79 internal settlement qualify permanent refusal to change; the 1969 constitution entrenched racial voting rolls.',[1,2,3,4]],
[[-1,2,1,-1,1,2,1,2,-1,-1,2,1,-2,-1,-1,2],'Emergency security, censorship and detention privileged counter-insurgency over general personal freedom.','Civilian institutions and some lawful speech persisted; legal arms ownership did not extend equal practical freedom to all racial groups.',[2,3,4],{12:'Public-order censorship is inferred to include divisive expression; it was not equal anti-racist protection.'}],
[[2,-1,2,-1,2,-1,2,-2,2,-1,2,-1,2,-1,-1,2],'A settler national identity and European institutional predominance shaped policy.','Separate African traditional institutions and later recognition of majority participation do not establish equal cultural influence throughout the scope.',[1,2,3]],
[[1,-1,1,1,-2,-2,1,1,1,1,1,1,-1,2,-1,-2],'Selective immigration favoured European settlement and economic capability over unrestricted equal entry.','Growth needs encouraged selected migration; exact modern annual limits and university routes are explicit analogies.',[2,3]],
[[2,1,2,2,-1,1,-1,1,1,-2,2,-1,2,-1,2,0],'He sustained counter-insurgency and cross-border operations while pursuing negotiations that preserved security and political interests.','He accepted negotiated changes under external pressure; military resolve did not eliminate every diplomatic concession.',[2,3,4],{16:'Negotiated settlement and insistence on continued security capacity compete.'}],
[[2,-2,2,1,2,-2,2,-1,2,-2,2,1,2,0,2,-1],'Unilateral independence and resistance to international sanctions asserted domestic final authority.','Seeking recognition and economic access shows willingness to cooperate when sovereignty and the settlement were accepted.',[1,2,3,4],{14:'Trade access and resistance to externally imposed conditions compete.'}],
[[2,1,2,-1,1,1,1,1,1,-1,2,-1,1,1,1,1],'Private farming and business coexisted with publicly organised networks and security-related enterprises.','Sanction-driven public intervention did not nationalise the entire economy; modern broadcasting and utilities are contextual extensions.',[2,3]],
[[2,-1,2,-1,2,-1,2,-1,2,-1,1,1,2,-1,2,1],'Sanctions encouraged protected domestic production and import substitution.','Much restriction was imposed from outside rather than chosen; willingness to resume trade qualifies inference of principled autarky.',[2,3,4]],
[[1,1,1,1,1,1,1,2,-1,1,-2,-1,1,2,1,1],'Private production continued under foreign-exchange controls and state coordination during sanctions and war.','Emergency intervention and import substitution must not be treated as socialist comprehensive ownership.',[2,3,4]],
[[-1,1,-1,2,-1,1,-1,1,-2,1,-1,1,-1,1,-2,2],'Preserving property and a limited welfare hierarchy were more prominent than equalising all citizens’ income and land.','Some services and later settlement reforms qualify absolute rejection of public support; racially unequal provision remains important.',[1,2,3]],
[[1,-1,2,1,0,1,2,-1,-1,1,-1,2,2,1,1,-1],'Christian public traditions operated through civil state institutions rather than a clerical government.','Public Christian traditions and ceremonies do not establish religious leaders’ legal veto or religious family courts.',[2,3],{5:'Religious schooling traditions and comparative education give competing indications.'}],
[[-1,2,-1,2,-2,2,-1,2,-1,1,-1,2,-1,2,-1,2],'Conservative settler social conventions favour traditional family and gradual reform.','Modern same-sex and gender curricula were not personally answered; historical cultural inference is disclosed rather than documented.',[2,3]],
[[1,1,2,1,1,-1,0,1,1,1,0,1,0,1,2,1],'Domestic industrial adaptation and infrastructure support productive innovation under scarcity.','Exact advanced biotechnologies are outside his record; practical adoption and safety concerns provide competing indications.',[2,3],{7:'Food security and untested production compete.',11:'Personal capability and unknown safety compete.',13:'Scientific capacity and irreversible bodily changes compete.'}],
[[-1,2,-2,2,1,2,-1,2,-1,2,-1,2,1,2,1,2],'Central security and national government predominated with some delegated provincial and traditional institutions.','African chiefs’ representation and local administration were constrained by national minority rule, not unrestricted community sovereignty.',[1,2,3]],
[[1,0,-1,1,1,1,1,1,0,1,1,1,1,0,1,1],'He explained franchise and governance through claimed civilisation, education and readiness as well as traditional sex differences.','Racially unequal institutions alone do not establish genetic theories of IQ or violence; his readiness argument was substantially cultural and paternalistic.',[1,2,3],{2:'Education-based rhetoric and racial essentialism give conflicting causal indications.',9:'Schooling and individual natural capacity both appear relevant.',14:'Institutional racism must not automatically become a claim of biologically inherited violence.'}]
]});
