import {save,source} from './assessment-helper.mjs';
save({id:'leon-trotsky',name:'Leon Trotsky',period:'Left Opposition and exile writings, 1923–1940',lifespan:'1879–1940',role:'Russian revolutionary and political theorist',description:'Revolutionary socialist assessed through his opposition to Stalinist bureaucracy and advocacy of international revolution.',religion:{value:'none',refs:[1],reason:'His adult atheism is explicitly identified in the biographical record, distinct from Jewish family origin.'},sources:[source('Leon Trotsky — biography','https://en.wikipedia.org/wiki/Leon_Trotsky','Wikipedia'),source('The Revolution Betrayed, chapter 11','https://www.marxists.org/archive/trotsky/1936/revbet/ch11.htm','Marxists Internet Archive','1936'),source('The Revolution Betrayed, chapter 7','https://www.marxists.org/archive/trotsky/1936/revbet/ch07.htm','Marxists Internet Archive','1936'),source('Proletarian culture','https://www.marxists.org/archive/trotsky/1923/art/tia23c.htm','Marxists Internet Archive','1923'),source('Dewey Commission, tenth session','https://www.marxists.org/archive/trotsky/1937/dewey/session10.htm','Marxists Internet Archive','1937-04-16'),source('Cultural debates and political struggle in 1923 — research abstract','https://publications.hse.ru/en/articles/374879261','Higher School of Economics','2020')],rows:[
[[2,-1,-1,2,0,1,1,2,1,1,1,2,1,2,-2,-2],'He demands genuine Soviet elections, criticism and accountable workers’ representatives against bureaucratic rule.','He allows Soviet parties rather than unrestricted capitalist restoration and historically excludes exploiting classes; earlier civil-war coercion is retained as counter-evidence.',[1,2,5],{5:'Restoring competing Soviet parties supports opposition within the socialist framework; equal conditions for every anti-socialist party are stronger than the proposal.'}],
[[2,-1,1,1,1,-1,2,1,2,1,1,1,2,2,1,0],'Exile writings defend criticism, cultural freedom and workers’ initiative against police bureaucracy while retaining revolutionary defensive coercion.','His earlier defence of terror and coercive labour cannot be erased; opposition to Stalin’s repression is not a complete liberal rights doctrine.',[1,2,3,5],{16:'Revolutionary security and opposition to arbitrary bureaucratic repression provide conflicting indications.'}],
[[-1,1,-1,2,1,1,-1,-1,0,2,1,1,1,1,2,-1],'International working-class solidarity and national self-determination allow distinct cultures while favouring common socialist civic participation.','Changing inherited life and patriarchal culture qualifies treating every tradition as immune from socialist reform.',[1,2,4],{9:'Common socialist institutions and several national cultures can coexist without a single universal calendar.'}],
[[-1,2,-2,2,2,1,-1,-1,-1,2,-1,-1,2,-2,2,1],'Exile experience and international labour solidarity suggest broad lawful movement and refuge without cultural or class exclusion of workers.','Modern visa and welfare mechanisms are analogical; international revolution does not itself demonstrate abolishing every border institution.',[1,2,4]],
[[1,1,2,2,-1,2,-1,1,1,-2,2,1,1,0,2,1],'He supports defending the workers’ state and revolutionary military capability while opposing imperialist wars and bureaucratic adventurism.','Revolutionary anti-war politics are not pacifism; military force remains a tool under class and defensive purposes.',[1,2,5],{14:'Revolutionary defence and avoiding futile escalation can conflict.'}],
[[-1,1,-1,2,1,1,-2,2,-2,1,-1,2,-1,2,-2,2],'Revolutionary internationalism and a worldwide socialist federation take precedence over isolated national socialism.','Existing bourgeois international bodies are not equivalent to a democratically organised workers’ federation; modern court answers are conditional analogies.',[1,2,5]],
[[-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2],'He defends nationalised production and democratic control by producers and consumers.','He criticised bureaucratic administration and retained accounting rather than calling for capitalist ownership; ownership and managerial initiative are distinct.',[1,2,5]],
[[1,-1,1,-1,2,-1,2,-1,1,-1,1,1,2,-1,2,-1],'A workers’ state protects a planned economy from capitalist restoration while seeking international economic cooperation under socialist transformation.','Internationalism does not imply unrestricted private foreign ownership or an unregulated capitalist trade market.',[1,2,5]],
[[-2,2,-1,2,-1,2,0,2,-2,2,-2,2,1,2,-2,2],'He advocates a democratically revised economic plan with public control of investment and distribution and transparent monetary accounting.','Factory initiative and meaningful accounting qualify rigid bureaucratic schedules for every wage or decision.',[2,5],{7:'Workers’ initiative and coordinated investment conflict under entirely unrestricted industry entry.'}],
[[2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2],'His programme seeks socialist equality and abolition of bureaucratic privilege, while recognising necessary transitional earnings differences.','Ultimate equality is not an assertion that every transitional worker is already paid identically; compensated land redistribution is a milder modern analogue.',[1,2,3]],
[[2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2],'Materialist socialist politics reject clerical control and religious foundations of state policy.','Atheism alone is not the basis for the scores: civil secular institutions and cultural emancipation in the writings supply the context.',[1,3,4]],
[[2,-2,2,-2,1,-2,2,-2,1,-2,1,-2,2,-1,1,-2],'He opposes patriarchal family constraints and Stalin’s rollback of reproductive and social emancipation.','Modern marriage and gender-identity mechanisms were not all explicitly discussed; progressive socialist transformation is contextual evidence rather than a documented contemporary questionnaire.',[1,3,4]],
[[2,-1,2,0,2,-2,2,-1,2,-1,2,1,1,0,2,-1],'Scientific development and deliberate improvement of material life are central to his account of socialist culture.','Actual medical technologies were unknown to him; respect for scientific investigation qualifies reckless adoption without any evidence.',[2,3,4,6],{4:'Scientific caution and transformative ambition conflict under a long-term proof requirement.',14:'Productive improvement and serious ecological uncertainty give opposing considerations.'}],
[[2,1,2,1,2,-1,-1,1,1,2,2,1,1,1,1,2],'Soviet recall and national self-determination coexist with coordinated socialist economic planning.','Local democratic participation differs from autonomous capitalist local policy; world federation need not entail one unaccountable central administration.',[1,2,5]],
[[2,-2,2,1,2,-1,2,-1,1,-1,2,1,2,-2,2,-2],'His new-everyday-life writing emphasises social education, transformed habits and cultural learning alongside material and biological conditions.','Historical materialism is not a quantitative claim about each inherited psychological trait; the record supports qualified estimates, not automatic culture-pole answers.',[3,4,6]]
]});
