import {save,source} from './assessment-helper.mjs';
save({id:'alice-weidel',name:'Alice Weidel',period:'AfD national leadership, 2017–2026',lifespan:'1979–',role:'Co-leader of Alternative for Germany',description:'German opposition politician advocating national sovereignty, immigration restriction and market-oriented economic reform.',religion:{value:'none',refs:[1],reason:'She describes herself as agnostic; her partner’s Christianity does not establish her own faith.'},sources:[source('Alice Weidel — policy and biography','https://en.wikipedia.org/wiki/Alice_Weidel','Wikipedia'),source('Weidel’s objections to social-state reform','https://www.afd.de/alice-weidel-falscher-fokus-bei-sozialstaatsreform-bas-will-pauschale-auszahlungen-und-abschaffung-von-nachweispflichten/','Alternative für Deutschland','2026-01-27'),source('Who is Germany’s AfD leader Alice Weidel?','https://amp.dw.com/en/who-is-germanys-afd-leader-alice-weidel/a-70436714','Deutsche Welle','2024-12-07'),source('Migration costs and pension policy statement','https://www.afd.de/alice-weidel-migrationskosten-explodieren-merz-laesst-buerger-laenger-arbeiten-um-staatsversagen-zu-finanzieren/','Alternative für Deutschland','2026'),source('Musk interviews Weidel on policy','https://www.investing.com/news/world-news/musk-to-host-german-farright-leader-on-x-stirs-angst-about-election-meddling-3804969','Reuters','2025-01-09')],rows:[
[[2,-2,2,1,2,2,1,2,-2,2,1,2,1,1,-2,-2],'She uses competitive elections and advocates referendums, opposing attempts to exclude her party.','Defence of extremist colleagues and praise for Hungary qualify liberal pluralism; democratic procedures are assessed independently of policy content.',[1,3,5]],
[[1,-1,1,-1,-2,-1,-2,1,-1,1,2,-1,1,1,2,-1],'Civil-liberty opposition to pandemic restrictions coexists with strong policing and selective restrictions on Islamic dress.','Defamation litigation and security priorities qualify unconditional speech freedom; earlier March 2020 demands for stronger pandemic measures changed.',[1,3,5]],
[[2,-2,2,-1,2,-1,2,-2,2,-1,2,-2,2,-2,-1,2],'She favours German cultural integration and bans on burqas and headscarves, resisting publicly funded parallel communities.','Her multilingual international life and family do not establish a pluralist public policy; individual lawful assimilation remains possible.',[1,3]],
[[2,-1,2,1,-2,-2,2,2,2,1,1,2,-1,2,-2,-2],'She supports selective skilled migration, tighter asylum and deportation, restricting welfare eligibility for foreign residents.','Skilled lawful entrants distinguish this from a total ban; refugees’ safety and family reunification are qualified estimates rather than universal rejection.',[1,2,4]],
[[-1,2,1,1,1,-1,1,-1,2,-2,1,2,1,1,1,1],'Interest-driven diplomacy, objections to Ukraine assistance and national defence capacity favour restraint with deterrence.','Her support for Israeli self-defence and criticism of Russian NATO-airspace violations qualify alignment with every Russian claim.',[1,5]],
[[2,-2,2,1,2,-1,2,-1,1,-1,2,1,2,1,2,-1],'She wants reduced EU competences and national policy control, allowing exit referendums if reform fails.','She also advocates reform from inside the EU and qualified her earlier demand for euro exit in 2025; cooperation is not wholly rejected.',[1,3,5],{11:'Monetary sovereignty remains an aim even though immediate euro departure was called too late.'}],
[[2,-1,2,-1,1,-1,2,-1,2,-1,2,-1,2,1,2,-2],'Her declared economic liberalism favours privatisation and private enterprise.','National strategic security and public infrastructure give exceptions; state protection of markets is separate from ownership.',[1,3,5]],
[[0,1,1,2,1,1,1,2,1,1,1,1,2,1,2,2],'Market competition and international business coexist with strategic national self-interest.','Opposition to sanctions on Russia is trade openness toward a selected partner, not proof of universal barrier removal.',[1,3,5],{1:'Market liberalism and national industry protection compete.'}],
[[2,-2,2,-1,2,-1,2,-1,2,-1,1,-2,2,-2,2,-2],'Deregulation, tax cuts and opposition to the minimum wage indicate market coordination.','Energy and national-security intervention remain exceptions rather than nationwide compulsory production planning.',[1,3,5]],
[[-1,2,-1,2,-1,2,-2,2,-2,2,1,2,-1,2,-1,2],'She opposes inheritance taxation and favours an activating, tightly conditional safety net over expanded transfers.','Her pensioner and contributory solidarity arguments retain adequate security for eligible citizens; this does not amount to abolishing social insurance.',[1,2,3,4]],
[[2,-1,2,1,1,-1,2,-2,-1,0,-1,2,2,1,1,-1],'Civil constitutional authority coexists with invoking a Christian national tradition against established churches’ political positions.','Agnostic personal identity does not prove secular state preference; Christian cultural recognition does not establish clerical veto.',[1,3],{10:'Cultural church support and criticism of organised churches’ politics compete.'}],
[[-1,2,1,1,-1,1,-1,2,1,1,-2,2,1,2,-2,2],'She opposes same-sex marriage and early sexualisation curricula while accepting civil partnerships and a broader notion of family.','Her stated family-is-where-children-are position and own adopted children qualify copying the party’s most restrictive household model.',[1,3]],
[[1,1,2,1,1,-2,0,1,1,-1,0,1,-1,1,2,1],'Nuclear energy, industrial production and infrastructure are favoured while selected green technologies and medical mandates are opposed.','Climate scepticism and dislike of wind turbines are not blanket opposition to technology; enhancement lacks direct evidence.',[1,3,5],{7:'Market innovation and distrust of unfamiliar food policy compete.',11:'Personal choice and medical-risk caution compete.'}],
[[2,1,-1,1,2,-1,1,1,2,-1,1,0,-1,-1,1,2],'German federal institutions and national sovereignty suggest protected regional functions with strong national border and security policy.','Regional election success does not by itself establish secession rights or rejection of all national standards.',[1,3],{12:'Regional autonomy and common healthcare obligations compete.'}],
[[1,0,-1,1,1,1,1,0,1,1,1,1,1,0,1,1],'Cultural integration and economic incentives explain much of her rhetoric, alongside traditional sex-role assumptions.','Claims about migrant crime and replacement do not establish a documented genetic explanation; individual biology and social conditions remain competing considerations.',[1,2,3],{2:'Inherited national IQ differences are not explicitly established.',8:'Empathy can be regarded as learned and individually predisposed.',14:'Cultural and policy explanations qualify assigning a biological racial-violence theory.'}]
]});
