import {save,source} from './assessment-helper.mjs';
save({id:'friedrich-ebert',name:'Friedrich Ebert',period:'Republican leadership, 1918–1925',lifespan:'1871–1925',role:'President of the Weimar Republic (1919–1925)',description:'German republican leader assessed through parliamentary reform, social compromise and emergency government.',religion:{value:'none',refs:[1],reason:'The biography distinguishes Catholic baptism from his later abandonment of Christian observance and describes his adult atheism.'},sources:[source('Friedrich Ebert — biography','https://en.wikipedia.org/wiki/Friedrich_Ebert','Wikipedia'),source('Friedrich Ebert — parliamentary democracy and social compromise','https://www.fes.de/friedrich-ebert','Friedrich-Ebert-Stiftung'),source('Friedrich Ebert — chronological biography','https://www.dhm.de/lemo/biografie/friedrich-ebert','Deutsches Historisches Museum','2014-09-14'),source('Weimar Germany — introduction','https://germanhistorydocs.org/en/weimar-germany-1918-1933/introduction','German Historical Institute','2026-09-24')],rows:[
[[2,-1,2,2,1,1,1,2,1,1,2,2,2,1,-2,-2],'He secured a competitive constituent assembly, universal adult suffrage and a parliamentary republic while exercising substantial constitutional emergency powers.','His term was extended by parliament, and repression of communist revolt qualifies unrestricted opposition rights. Rejecting military coups is distinct from his alliance with military commanders.',[1,2,3,4]],
[[1,1,-1,-1,1,1,1,2,1,0,2,1,-1,-1,0,1],'Initial republican reforms removed censorship and recognised assembly, while he later endorsed emergency restrictions and violent repression of unrest.','Constitutional liberties and the executive’s emergency practice pull in different directions; modern surveillance and health mechanisms are explicit analogies.',[1,3,4],{10:'Civil expression and state-security oversight conflict for anonymous communications, a technology outside his lifetime.',15:'Constitutional privacy protection and emergency suspension give competing grounds.'}],
[[1,1,1,1,2,0,1,-1,1,1,2,0,1,1,1,1],'He framed himself as president of all Germans, with equal republican citizenship and a shared national community.','The republic reduced religious and class exclusions but historical nation-building is not equivalent to a fully developed contemporary multicultural programme.',[1,2,4],{6:'Equal citizenship offers contextual support for recognition, but specific Indigenous ceremonial policy is outside this European record.',12:'Access and common German administration compete; no modern multilingual-signage position is documented.'}],
[[1,1,-1,1,1,-1,1,1,1,1,0,1,1,0,1,0],'Postwar protection, labour interests and equal citizenship suggest regulated entry rather than either ethnic exclusion or unrestricted residence.','His direct immigration record is limited; these choices are cautious analogies from republican rights and postwar economic pressures, not a modern visa programme.',[1,2,4],{11:'Legal control and equal access do not clearly prescribe compulsory private sponsorship.',14:'A shared civic community and historical national attachment conflict under a broad cultural preference.',16:'Equal citizenship need not make cultural difference alone a reason to raise immigration.'}],
[[-1,2,1,1,1,0,1,-1,2,-1,0,2,0,2,1,1],'He accepted the postwar settlement and defended the republic while retaining a military establishment and opposing armed revolution.','His support for war credits in 1914 is earlier counter-evidence; the postwar period is not assessed as unconditional militarism or absolute pacifism.',[1,3,4],{6:'Military preparedness and demobilisation supply opposing grounds for universal service.',11:'Maintaining a national army does not establish an unrestricted overseas-combat posture.',13:'National defence and preventing renewed war place competing limits on coercive threats.'}],
[[1,1,0,1,1,1,1,1,-1,1,2,1,1,1,1,1],'He pursued Germany’s recovery through a sovereign republic and accepted international settlement under severe constraints.','Acceptance of Versailles is not proof that every imposed term was his ideal; no later supranational institutions are retrospectively attributed to him.',[1,2,3,4],{3:'Constitutional authority and accepted international obligations provide competing aims for conflict cases.'}],
[[1,2,0,1,-1,2,0,1,-1,1,0,1,0,2,-1,1],'His social-democratic compromise retained private enterprise and worker organisation alongside public infrastructure and social responsibilities.','Opposition to Bolshevik seizure does not imply unconditional privatisation; constitutional possibilities for socialisation did not nationalise every business.',[1,2,4],{3:'Workers’ interests and effective private enterprise are both recognised, without a general equal-service ownership tie-break.',7:'Lower cost and labour protections can conflict when outsourcing services.',11:'Security concerns and mixed ownership make this conditional.',13:'Municipal capacity and efficient contracting provide competing grounds.'}],
[[0,1,1,1,1,0,1,1,1,1,0,1,1,1,1,1],'Postwar reconstruction depended on international economic links while retaining room to protect domestic livelihoods.','His presidency does not supply an explicit modern tariff schedule; trade answers are reconstruction-based analogies rather than copied party doctrine.',[1,2,4],{1:'Domestic employment and trade recovery compete under blanket protective tariffs.',6:'Recovery through commerce and negotiating leverage conflict under unilateral reductions.',11:'Retaliation and recovery costs supply opposing considerations.'}],
[[1,-1,1,1,1,1,1,1,0,1,-1,2,2,1,-1,-1],'Reform institutionalised organised labour, social protection and regulated markets rather than Bolshevik economic command.','Emergency economic intervention and wartime controls should not be treated as a permanent plan for all production; modern currency mobility is analogical.',[1,2,4],{9:'Economic stability and freedom of movement conflict during postwar monetary crisis.'}],
[[2,-2,2,-1,2,-1,1,-1,1,-1,2,-1,2,-2,1,-1],'He pursued social reconciliation, worker protection and provision for people harmed by war within a reformist republic.','Compromise with employers and preservation of private enterprise qualify complete income equalisation or uncompensated confiscation.',[1,2,4]],
[[2,-2,2,-1,1,-1,2,-2,-1,0,0,1,2,1,2,-1],'The republic’s civil authority and equality across religious backgrounds support policy without clerical approval.','His atheism is personal; Weimar retained religious education and public religious traditions rather than eliminating every church privilege.',[1,2,4],{10:'Social reconciliation and civil neutrality conflict when public funding is expressly for strengthening belief.',11:'Plural citizenship and inherited public symbols give competing considerations.'}],
[[1,1,1,1,1,2,-1,1,1,1,0,1,1,2,0,1],'He combined women’s political equality and republican social reform with gradualism and preservation of familiar family institutions.','Weimar’s more adventurous cultural movements were not all his personal programme; every contemporary sexuality question is a disclosed analogy.',[1,2,4],{11:'Equal citizenship and conventional historical language give conflicting signals for contemporary identity conventions.',15:'Education and equality are relevant but specific modern curricula are not documented.'}],
[[1,1,2,1,1,-1,0,2,1,1,-1,2,-1,1,2,2],'Reconstruction and improved material living conditions suggest support for useful infrastructure and research, with safeguards around irreversible experimentation.','Modern AI, brain implants and embryo editing are outside his experience and are only cautious contextual estimates.',[1,2,4],{7:'Material improvement and uncertainty about unfamiliar food production give opposing considerations.'}],
[[1,2,-2,2,1,1,-1,1,1,2,-1,1,0,2,1,2],'He defended a federal republic but used national emergency authority, including intervention in Länder, and supported nationwide labour and social rules.','The constitution retained state institutions; national coordination does not mean every local policy was abolished.',[1,3,4],{13:'Equal rights and national constitutional unity compete in an Indigenous self-government analogy outside his domestic record.'}],
[[1,-2,1,1,1,1,2,-1,1,-1,1,1,1,-2,2,-1],'His reformist emphasis on education, social conditions and organised labour gives contextual support to learned habits and opportunity while leaving individual biological variation plausible.','Neither republican suffrage nor socialist affiliation quantifies every psychological causal claim; the biological and social comparisons remain uncertain estimates.',[1,2,4]]
]});
