import {save,source} from './assessment-helper.mjs';
save({id:'adam-bandt',name:'Adam Bandt',period:'Greens leadership, 2020–2025',lifespan:'1972–',role:'Australian Greens leader (2020–2025)',description:'Australian parliamentarian assessed through his civil-rights, public investment and environmental policy programme.',religion:{value:'undisclosed',refs:[1],reason:'The biographical material reviewed does not establish a public adult religious identity. Absence of an explicit declaration is not treated as no religion.'},sources:[source('Adam Bandt — biography and political views','https://en.wikipedia.org/wiki/Adam_Bandt','Wikipedia'),source('National Press Club address','https://greens.org.au/news/speech/adam-bandt-national-press-club','Australian Greens','2023-04-26'),source('Interview on housing tax handouts','https://www.abc.net.au/news/2025-04-15/greens-leader-adam-bandt-speaks-on-ending-housing/105180870','ABC','2025-04-15'),source('Adam Bandt — annual report','https://cdn.greens.org.au/news/annual-report/2024/adam-bandt','Australian Greens','2024')],rows:[
[[2,-1,2,1,2,2,2,2,-2,2,1,2,1,2,-2,-2],'He seeks change through competitive parliamentary elections, referendums and grassroots mobilisation, opposing erosion of basic rights by emergency executive power.','His acceptance of parliamentary leadership and negotiated legislation qualifies treating every decision as a direct public vote.',[1,2]],
[[2,-2,-2,2,-1,-2,1,1,2,2,-1,2,2,2,2,-2],'His legal work and political programme emphasise civil rights, cannabis legalisation, protest and opposition to arbitrary detention.','Public-health protection and restrictions on racial hatred coexist with civil liberties; neither unlimited weapons access nor total freedom from safety regulation follows.',[1,2,4]],
[[-2,2,-1,2,-1,2,-1,-1,-1,2,1,2,-1,2,2,-1],'He supports Indigenous Treaty, Truth and Voice and a plural Australian community with protection from racism.','Shared civic participation remains compatible with distinct cultures; removing the flag from a press conference does not settle all integration duties.',[1,2,4]],
[[-1,2,-2,2,2,1,-1,-1,-1,2,-1,-1,2,-2,2,2],'He opposes mandatory asylum detention and backs humanitarian protection and cultural inclusion.','Ending mandatory detention does not itself repeal every visa or border rule; broad numerical-cap and university-route answers remain qualified contextual inferences.',[1,2]],
[[-2,2,-1,1,2,-2,1,-2,2,-1,-1,2,-1,2,-1,2],'He rejects AUKUS expenditure and prioritises diplomacy and climate security over military escalation.','Criticism of submarines is not a refusal to defend Australia against attack; defensive preparedness qualifies absolute opposition to military spending.',[1,2,4]],
[[-1,1,-1,1,1,2,-1,2,-1,2,1,2,0,2,0,2],'He invokes international climate science, human rights and UN scrutiny while defending an independent Australian republic.','Republican sovereignty does not entail rejection of international obligations; ending AUKUS qualifies unconditional long-term military commitments.',[1,2,4],{13:'Humanitarian responsibility and administrative control of entry coexist; no exclusive allocation of all border authority is documented.',15:'International cooperation is explicit, but joining a political federation is a stronger institutional step.'}],
[[1,2,-1,2,-2,2,-1,1,-2,2,-1,1,-1,2,-2,2],'He explicitly favours public housing, public wealth and government enterprise while leaving space for ordinary private businesses.','Taxing private firms and abolishing fossil subsidies are not the same as nationalising every firm or resource operation.',[1,2,3,4]],
[[1,1,1,1,1,0,1,1,1,1,0,2,2,1,2,1],'His programme prioritises workers, environmental standards and domestic transition investment while retaining international economic cooperation.','Direct tariff evidence is weaker than climate and labour evidence; industrial investment should not be equated automatically with import prohibitions.',[1,2,4],{6:'Trade openness and enforceable social and environmental standards make unconditional unilateral liberalisation a mixed proposition.',11:'Defensive retaliation and the cost to consumers supply competing considerations.'}],
[[1,-1,1,2,1,2,1,1,1,2,-1,2,2,1,-2,0],'He proposes a Green New Deal, rent freezes, public investment and stronger wage protection within a continuing mixed economy.','Strong public planning and selective price controls do not establish ordinary compulsory targets for every private industry.',[1,2,3,4],{16:'Coordinated transition investment and ordinary decentralised production coexist; a blanket national production plan exceeds the documented programme.'}],
[[2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,1,-2],'He favours lifting income support above poverty, taxing large corporate gains and redirecting high-income tax concessions toward households needing support.','His housing programme targets multiple-property concessions rather than removing every owner’s property; broad land redistribution remains an analogy.',[2,3,4]],
[[2,-2,2,-2,2,-2,2,-2,1,-1,1,1,2,-1,2,-2],'His civil-rights and equal-citizenship programme rests on civil institutions rather than religious approval.','No public personal identity is established; retained holidays and charitable activity must be separated from clerical control of law.',[1,2]],
[[2,-2,2,-2,2,-1,2,-2,2,-1,2,-2,2,-1,2,-1],'He supports marriage equality, cannabis reform, sexual and gender equality and Indigenous constitutional change.','Progressive reform does not mean compulsory abandonment of every inherited custom; individual acceptance and institutional reform remain distinct.',[1,2,4]],
[[1,1,-1,2,1,2,1,2,1,2,-1,2,-1,2,1,2],'He promotes clean-energy innovation and necessary housing while prioritising ecological limits and precaution over fossil-fuel expansion.','Backing lithium mining and public housing qualifies an absolute ban on habitat loss; medical enhancement positions are less directly documented.',[1,2,4]],
[[2,-1,1,1,2,-1,1,-1,2,2,1,2,2,1,2,2],'He combines Indigenous self-government and local participation with national welfare, climate and housing coordination.','A federal rent-freeze fund works through state cooperation; nationwide policy goals are not evidence for abolishing state constitutions or local governments.',[1,2,3]],
[[2,-2,2,-1,2,-1,2,-1,1,-1,2,-1,2,-2,2,-2],'His explanations of inequality emphasise institutions, discrimination, social opportunities and learned political identity.','The evidence does not measure the causal weights of every psychological trait, so specific inherited-versus-learned choices remain educated contextual assumptions.',[1,2,4]]
]});
