import {save,source} from './assessment-helper.mjs';
save({id:'titoism',name:'Titoism',catalogue:'ideology',period:'Yugoslav socialist self-management doctrine, 1950–1980',description:'A Yugoslav socialist tradition combining social ownership, worker self-management, federalism and international non-alignment.',phrase:'A society where workers manage socially owned production and diverse national communities cooperate in an independent socialist federation.',religion:{value:'none',refs:[1,2],reason:'The doctrine imposes no faith prerequisite; constitutional civil authority and private worship are distinguished.'},sources:[source('1974 Yugoslav Constitution — English transcription','https://wikisource.org/wiki/User:Glide08/Sandbox/Yugo1974','Wikisource','1974'),source('Titoism — doctrine and variants','https://en.wikipedia.org/wiki/Titoism','Wikipedia'),source('Titoísmo — institutions and economic changes','https://www.enciclopediadelapolitica.org/termino/titoismo/','Enciclopedia de la Política','2018-07-03'),source('Socialist self-management — Kardelj’s published abstract','https://journals.sagepub.com/doi/abs/10.1177/002085237604200201','SAGE','1976-06')],rows:[
[[-1,1,1,1,-2,1,-1,2,1,1,1,2,1,2,-1,-1],'Delegates, worker participation, recall and responsibility coexist with the League of Communists’ leading role.','Doctrinal replaceability and self-government differ from Tito’s personal lifelong presidency; socialist competition is not unrestricted multi-party alternation.',[1,2,3,4]],
[[1,1,1,1,1,1,2,1,1,0,1,1,1,1,1,1],'Declared personal rights and self-management operate within protection of the socialist order.','Actual suppression of dissidents qualifies constitutional liberty promises; doctrine and historical enforcement are both retained.',[1,2,3],{10:'Private communication rights and defence of the socialist order compete.'}],
[[-1,2,-1,2,1,2,-1,-1,0,2,1,2,-1,1,2,-1],'Equal nationalities and languages are constitutive parts of brotherhood and unity.','Shared socialist cooperation limits claims that every separate custom overrides equality or common institutions.',[1,2,3],{9:'Common practical schedules and distinct national calendars coexist.'}],
[[-1,2,-1,2,2,1,-1,-1,-1,2,-1,-1,2,-2,2,1],'International worker solidarity and non-aligned openness favour mobility and protection without cultural hierarchy.','Exact visas and settlement procedures are contextual extensions; collective economic capacity still constrains administration.',[1,2,3]],
[[-1,2,1,1,1,2,1,-1,2,-2,1,2,1,2,1,2],'Peaceful coexistence, general people’s defence and disarmament accompany support for national liberation.','Anti-colonial solidarity permits some force beyond the narrow defensive-only wording; non-alignment is not pacifism.',[1,2,3]],
[[2,-1,1,1,2,1,1,2,2,1,2,2,1,2,2,1],'Independent development rejects bloc domination while favouring international cooperation and negotiated rules.','Non-alignment rejects compulsory common foreign policy, not all collective action or accepted international obligations.',[1,2,3]],
[[-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2,-2,2],'Social ownership with worker control replaces capitalist private ownership of major production.','Public is the bank’s closer collective category; social ownership must not be described as universal central state administration. Personal possessions and limited private activity remain.',[1,2,3,4]],
[[1,1,1,2,1,1,1,1,1,1,0,2,1,2,2,2],'Socially owned enterprises trade internationally and can cooperate with foreign producers under social priorities.','Strategic ownership and development protection qualify completely equal uncontrolled foreign acquisition.',[1,2,3],{11:'Reciprocity and peaceful open exchange compete.'}],
[[2,-1,2,1,2,1,1,1,1,1,-2,1,2,1,1,1],'Associated workers decide enterprise activity within negotiated social development plans.','The 1970s strengthened coordinated planning; neither pure command allocation nor unrestricted private markets captures the doctrine.',[1,2,3,4]],
[[2,-2,2,-2,2,-1,2,-1,1,-2,2,-1,2,-2,1,-2],'Solidarity, equal opportunity and regional development accompany entitlement to the fruits of labour.','Enterprise earnings differences and individual material incentives qualify complete equalisation of every income.',[1,2,3,4]],
[[2,-2,2,-2,2,-2,2,-2,2,-2,2,-1,2,-1,2,-2],'Civil socialist authority and private religious freedom replace religious foundations of national government.','Constitutional worship protections do not make religious doctrine an official legislative source; historical accommodation remains possible.',[1,2,3]],
[[2,-1,2,-1,1,0,2,-1,1,-1,1,-1,2,-1,1,0],'Social emancipation and equal participation favour changing inherited hierarchies.','Constitutional equality does not explicitly settle every contemporary sexual-identity curriculum or inherited custom.',[1,2,3],{6:'Family support and freedom from compulsory family roles coexist.',16:'National cultural inheritance and socialist transformation compete.'}],
[[2,-1,2,1,2,-1,1,1,2,1,1,1,1,1,2,1],'Developing productive forces is explicit, with collective responsibility for public safety and resources.','Modern gene editing and implants are analogies to productive scientific development; long-term harm remains a constraint.',[1,2,3,4]],
[[2,1,1,1,2,-1,1,1,2,1,2,1,1,1,2,2],'Federal national autonomy and municipal self-management coexist with solidarity and nationwide coordination.','Constitutional self-determination includes secession while preserving mutual duties; practice often suppressed separatist mobilisation.',[1,2,3]],
[[2,-2,2,-1,2,-1,2,-1,1,-1,2,0,1,-2,2,-1],'Social institutions and associated work are treated as transformable causes of conduct and opportunity.','Biological individuality need not be denied; exact temperament mechanisms are less specified than rejection of racial hierarchy.',[1,2,3,4],{12:'Personal variation and social formation compete.'}]
]});
