export default {
 'constitutional-monarchism': `E A E A E E D A B B A E A B A A
 C E D E C B D D E D C D E D B A
 C D C E D D C B C D D D C C D C
 C D C E D B C C C D C C E B D C
 C E C D D B D B D B C D C D C D
 D C D E E D C D C D D D D E D D
 E D D B C E D D C D D C D D C E
 B E C E C D C E C D C E D D D E
 E B E C E C E C D C B D E C D B
 C C D C D C C D C C D C D B B D
 D B E D D B E B B C C E D C D B
 C C D C E D C D E C D D D E D E
 D C D D D C C E C D B E B D D E
 D C B D E B C C D D D D C D E E
 D B C D D C D C C C D D C A D B`,
 'cuban-socialism': `B B E D A C B B E B C D C C B B
 B E B C D D D D B B D D C B A D
 D D D D E D D B D D E C D C D D
 D C C D D B D D C D D D D C D C
 C E D E D D D C E A D D D D E D
 E A E D E B E D D B E D E D E D
 C E B D B E C E B E C E B E C E
 D C D D D C D C D C D D D C E D
 C E C E C E C E B E A E D E B E
 D B E C D B C B D B E B D B C B
 E A E B E A E A C B C D E B E B
 D B E B E C D B E C D B E D E C
 D C D D D C C E C D B E B D D E
 B E A E C E B E C E B E C E C E
 D B D C D C D C D C D D D A D B`,
 'cultural-nationalism': `D B D B D D D B B C B D B C B B
 D D D E C B D D D D C D E D C A
 E C D D E E E A D D E C D B D E
 D C C E D B D D C D C C E C D C
 B E B D D B D B E B B E B E C D
 E B E D E B D D D C E D E D E D
 D D D C C D C C C C D C C D C E
 C D D D D C D D D D C D D D D E
 D B D D D C D C D D B C D C D B
 C C D C D C C C C C D C D B C C
 D B E C D B E B C C C D E C D B
 C D D C C D C D C D C D D E C E
 C D B D D D C E B D B E B D C E
 E B D B E B D B D C E C E B E C
 E A D C E B E B D C E C E A E B`,
 'democratic-socialism': `E A E A E E B A B D A E A D A A
 E B E E B A B C E E B B E E C A
 B E B E C E B B B E D D B C E B
 A E A E E E A A A E A B E A E D
 A E B D E A D B E B A E A E B E
 C D C D D E B E C E C E C D C D
 B E B E B E B E A E C E B E B E
 C D D D D C D C D D C D D D E D
 B D B E C E D E B E A E D D B E
 E A E B E B E B E B E B E A C B
 E A E A E A E A D A D C E B E B
 E A E A E B E B E B D A E B E B
 B E C D C E C E B E B E B E D E
 D D C D D B C D D E D E E D D E
 D A E C E C E B D C E D D A E B`,
 'ecosocialism': `E A E A E D D A B D B E A D A A
 D C E E B B D D E D B D E E B A
 B E B E C E B B B E D D B C E B
 B E B E E D B B B D B B E A E D
 A E B D E B D A E B B E B E B E
 B D B D C D B E B E C E C D C D
 A E B E B E B E A E B E B E B E
 D C D C E B D C D C C D D C E D
 B D B E B E C E B E B E D E B E
 E B E B E B D B E B E B E B D B
 E A E A E A E A C B D C E B E B
 E B E B E B D B E B D B E C E B
 B E A E C E C E A E B E B E C E
 E B D C E B C C D D D D E D E D
 D B D C D C D C D C D D D A D B`,
 'environmentalism': `E A E A E D E A B C B E A C A A
 D D E E D B D D E D C D E E B A
 B E B E C E B B B E D D B C E B
 C D C E E C C C C D C B E A D D
 B E C D D B D B E B B E B E C E
 B D B E C E B E B E C E C E C D
 D E C C C E C D C D C D C E C D
 C D C D D C C D C D C D D D D E
 D C D D D D E D C D B D D C C C
 D B D C D C C B D C D C D B C B
 E B E B E B E A C B D D E B E B
 D B D B D C D B D B D C D D D C
 B E A E D E C E A E B E B E C E
 E B C C E B C D D E D D E D E E
 D B C D D C D C C C D D C A D B`,
 'fascism': `A C B E A B A B E A E A E A E D
 A E A A E E E E A A E E A A B E
 E A E B E B E A E A E A E B A E
 E B D C B A E E E C D D C E B B
 E B E E A E A D B A E A E A E A
 E A E C E A E B E A E C E D E C
 E D D C D D D C C D D C D D C E
 E B E C E B E B E B E D E B E C
 C E C E C E C E B E B D C E B E
 B D C D C D C D B D C D D D B D
 C D D D C D E C B D B E D D C D
 B E B E A E A E A E B E B C B E
 D C E C D B C D D C C C B C E C
 A E A E B E A E B E A E B E B E
 D B C D D C D C C D D D C B D C`,
 'islamic-fundamentalism': `B B C C B C B B E B D C B B C B
 A E B C E D D D A B E E C C B D
 E B E C E D E A E B E B E D C E
 D C C E D B C C C D C C E D D B
 D D D E B D B B D A D C D C D C
 C B C D D B C C C B D D C D D D
 D D C C C D C D C D C D C D C D
 D C D D D C D C D C C D D C D D
 D C C D D D C D C D B D D C C C
 D B D B D B D B D B E B D B C B
 A E C E B E B C A E A E D E B E
 A E B E A E A E A E A E C E B E
 C D D D D C C E C D B E A D D E
 C E B E C D C D C D C D C D C E
 D B B D D C D C C D D D C A D B`,
 'islamic-socialism': `D B E D C D C B D C C D C C B B
 C E D D D C D D C C D D D C B B
 D D D D E D D B D D E C D D D D
 D C C E D B C D C D C D E C D C
 D D D E C D C C D A D C D C D D
 E B E D E B D D D C E D E D E D
 C E B E C E C E B E C E C E B E
 D C D D E C D C D C D D D C E D
 C D C E C E C E B E B D D E C E
 D B E B D B D B D B E B D B D B
 B D E D C C D B B C B E E D C C
 C D C D A D B D A D C D D D C D
 D C E D D C C E C D B E B D E D
 D D B D E C C D D E C E C D D E
 D B D C D C D C D C D D D A D B`,
 'islamism': `C B D D A C A B E B D C D B D B
 A E B B E E E E A B E E B B A E
 E B D C E D E A D C E B D D C E
 E C D D D B E E D C D D D D C B
 D D D E B D C C D A E C E C E C
 E A E C E A E C D A E D E D E C
 D E C D C D C E C D C D C E C D
 E C E D E B E C E C D D E C E D
 C D C E C D C E B E A E D E C E
 D B D C D C C D C C D C D B C C
 A E B E B E A E A E A E B E A E
 B E B E A E A E A E A E C E B E
 D C D D D C C E C D B E A E D E
 B E A E C E B E C E B E C E C E
 D B B D D C D C C D D D C A D B`,
 'kantian-republicanism': `C B B B D C C B B B B C B B B A
 E D D E B B D D D D B D E D C A
 C C C D D C C B C D D C C B D C
 D C C D D B C C C D C D D B C C
 A E B D E B D B E B A E A E B E
 D C D E D D C D C D D D D E D D
 E C D B D C D B D C D C D C D C
 B D C E C D C D C D C E C D D E
 E B D C D C E C D C B C D C D B
 B D D D C D B D B D C D D D B D
 E B E B D B E A C B D D E B E B
 B E B E A E A E A D B E B E B E
 D C D D D C C E C D B E A D D E
 C E A E C D C D C D C D B C C E
 C D B D C D D D C D C D C D D D`,
 'left-wing-populism': `E A E A E E D A B D B E A D A A
 D D E E C B D D E D C D E E B A
 B D B E D E C B B E D D B C E B
 B D B E E D C C B D B B E A D D
 B E C D D B D B D B B E B E C D
 D C D D E D C D C D D E C D C D
 D E B D B E C E B E C D C E C E
 C D D D D C D C D D C D D D E D
 D C D E C D D E C E B E D D B D
 E B E B E B D B D B E B E B C B
 E B E B E A E A C B D D E B E B
 E B E B E B D B E B D B E C E B
 C D C D C E C E B D B E B D D E
 E B C D E B C C D E D E E D E D
 E B D C D C E B D C E D D A E B`,
 'liberal-conservatism': `E A E A E D E A B B B E A B A A
 D E C E B B E D E D D D E D D A
 D C D D E D D B D D E C D C D D
 D D D E D B D D C E D D E C D C
 C D D E D B D C D A D D D C E D
 D B D E E C D D C C E D D E D D
 E C E B D D E C E C D C D C D D
 B E B E D D C E C E C E D E D E
 E B E C E C E C D C C D E C E B
 B D D D C D B D B D D D D D B D
 D B E B D B E A C B C E E C D B
 C C D C D D B D D C C D D E C D
 D C E D E C D E D C C E B D E D
 E B B C E B D B E C D D C C E E
 D B C D D C D C C C D D C A D B`,
 'liberal-feminism': `E A E A E E E A B C B E A D A A
 E D E E C B D D E E C D E E B A
 B E B E C E B B B E D D B C E B
 B D B E E D B C B D B B E A E D
 B E B D D A D B E B B E B E B E
 B D B E C E B E B E C E C E C D
 E D C C C D C C C D D C C D C D
 B D C E C D C E C D C E D D D E
 D B D D D D E D D D B E E C C B
 D B E B D B D B D B E B E B C B
 E A E A E A E A D A D C E B E A
 E A E A E B E B E B E A E B E B
 D C C E D D C E B D B E B E D E
 D D C D E B C D D E D E E D D E
 D A E C D C D C D C D D D A E A`,
 'liberalism': `E A E A E E E A A C B E A C A A
 E D D E B B D D E E B D E E C A
 B D B E D E B B B E D D B C E B
 C D C E E C C C C E C B E A D D
 B E C D D B D B D B C E B E C D
 B D B E D E C E B E C E C E C D
 E C D B C D D C D C D C D C D D
 B E B E C D B E C E C E D E D E
 E B E C E C E C E C B D E C D B
 C C D C D C C D C C D C D B C C
 E A E A E A E A D A D C E B E B
 E B E B E C D B E B D B E D E B
 D C D D E C D E C D C E C D D D
 E B C C E B D C D D D D D C E D
 D B D C D C D C D C D D D A D B`
};
