export default {
 'libertarianism': `E A E A E D E A A D A E A D A A
 E B C E A A B D E E B C E E E A
 A B B E B D A B B D D C B C D B
 A E A E E D A A A E B B E A A C
 A E A D E A D B E B A E A E B E
 D A D D E B D B D B D D D E D C
 E A E A E A E A E A E A E A E A
 A E A E A E A E A E A E A E A E
 E A E A E A E A E A E A E A E A
 A E A B A E A B A E B E A E A B
 E A E A E A E A D A D B E A E C
 E B E B E C E D E B D B E C D B
 E B D B E C D C D C E C D C E B
 E A E A E B D B E A E B E B E B
 D B C D D C D C C D D D C A D B`,
 'luxemburgism': `D A B B C E B B D D B D A E A A
 D C E E C B D D E D B D E E C B
 B D B E C E B B B E D D B C E B
 B D B E D D B B B D B B E A D D
 B E B D D D D B E B B E B E C E
 C D C D D C B D C D C E C D C D
 B E B E B E B E A E B E B E B E
 B D C D C C C C C D C D D C E D
 B E B E B E D E B E B E D E B E
 D B E B D B D B D B E B D B B B
 E A E A E A E A C B D C E B E B
 D B E B D C D C D B C B E C D C
 D C D D D C C E C D B E B D D E
 D D B D D C C D D E D E D D D E
 D B D C D C E B D C E D D A E B`,
 'maoism': `B B D D A C A B E B D C D C C B
 B E C D D D D D B B D E C C D D
 E C D C E D E A D C E B D C C E
 D C C D D B D D D D D D E C D B
 D D D E C E C D D A D C D C E C
 E B E D E B E D D B E D E D E D
 B E B D C E C E B E C E C E B E
 E C E C E B E B E C D D E C E D
 B E B E C E C E B E A E D E B E
 D B E B D B D B D B E B D B B B
 E B E A D B E A C C C D E B E B
 D B E B C C D C C C B D D C C C
 D C E D E C C E C D B E B D E D
 B E A E C E C E C E C E C E C E
 E A D C E B E B D C E D D A E B`,
 'marxism': `D B C B C D B B D D B D B E B B
 D D E E C B D D D D C D E E C B
 B D B E C E B B B E D D B C E B
 B D B E D D B C B D B B E A D D
 B E B D D D D B E B B E B E C E
 C D C D D C B D C D C E C D C D
 B E B D B E C E B E C E B E B E
 B D C D C C C C C D C D D C E D
 B D B E B E C E B E B E D E B E
 D B E B D B D B D B E B D B B B
 E A E A E A E A D A D C E B E B
 D B D B D C D C D C C B D C D C
 D C E D D C C E C D B E B D E D
 E B D B E B C C D D E D D C E D
 E A D C E B E B D C E D D A E B`,
 'meritocracy': `D B E B D D D B B C B D B C B A
 D D D E C B D D E D C D E D C A
 B D B E D D B B C D D C B C D B
 D C D E D B D C C E D C E A C C
 B E C D D C D C D B C D C D C D
 D C D D D D C D C D D D D E C D
 E D D B C D D C D C D C D C D D
 B D C E C D C E C D C E D D D E
 E B D D E C E D D D B D E C D B
 C C D D D C D D C C D C D B C C
 E B E B E B E A C B D C E B E B
 D B E B D C D B D B D C E D D C
 D C D D E C D E C D C E B D D D
 D C B C E B D C D D D D C D D E
 C B C D D C D C C D D D C A D B`,
 'militarism': `D B D C D D D B B C C D B C B C
 C E C D D D E E C B E E D B D C
 D C D D E D D B D C E C D B D D
 D C D D C B D D D D D D D C C B
 E B E E A E A D B A E B E B E B
 E B E E E B E C D B E D E D E C
 E D D C D D D D C C C D D E C D
 D D E D E C E C D C D D E D E D
 D D D E D D D E C E B D D D C D
 C D D D C D B D B D D D D D C D
 D B E B D B E B B C C D E C D B
 C D D D C D C D C D C D D E C D
 D B E D E C D D D C C E B D E D
 C E A E C E C D C D C E C D D E
 D B C D D C D C C D D D C A D B`,
 'minarchism': `D B D B D D D B A C A D B C A A
 E D C E A A B D E E B D E E E A
 A B B E B D A B B D D C B C D B
 B E B E D D B B B E B C E A A C
 A E B D E A D B E B A E A E C E
 D B D D E B D B D B D D D E D C
 E A E A E A E A E A E A E A E A
 A E A E A E A E A E A E A E A E
 E A E A E A E A E A E A E A E A
 A E A B A E A B A E B E A E B B
 E A E A E A E A D A D B E A E C
 D B D B D C D D D C C C D C D C
 E B D C E C D D C D D D C D E C
 D B D B D C D B D B D C D B E C
 C B C D D C D C C D D D C A D B`,
 'nationalist-conservatism': `D A D A D D C A B C B D A C A A
 B E C D D C E D C D D E E C D B
 E B E C E D E A E B E B E B B E
 E B D D C A E E E C D D C E B B
 D D D E C D C C D A D C D C E D
 E A E D E A E B E A E C E D E C
 E D D C D D D C C C D D D E C D
 E C E D E B E C E C D D E C E D
 E B D D E C E D D E B D E C D B
 C D D D C D B D B D D D D D B D
 B D E D C D E B B D B E E D C B
 B E B E A E A E A D B E C E B E
 D C E D E C C E D C B E A D E D
 E B A D E B D B E D D D C C E E
 D B B D D C D C C D D D C A D B`,
 'nazism': `A C A E A A A B E A E A E A E D
 A E A A E E E E A A E E A A B E
 E A E A E A E A E A E A E A A E
 E A B B A A E E E B D E A E A A
 E A E E A E A D B A E A E A E A
 E A E B E A E B E A E C E D E B
 D D D C D D D C C D D C D E C E
 E A E B E B E B E B E D E B E B
 C E C E C E C E B E A D C E B E
 B D C D C D C D B D C D C D B D
 C C E C C C E B C C C D E D C C
 B E B E A E A E A E B E A C A E
 D C E C E B C C D C D C D C E C
 A E A E A E A E A E A E A E A E
 B E A E B D C E B D B E C E C D`,
 'neoconservatism': `E A D B E D D A B C B E A C A A
 C E C E C D E E D C E E E C D B
 D C D D E D D B D C E C D C D D
 D D D E D B C D C E D D E C C C
 E C E E B B B C C A E C E C E C
 E B E E E B D C D B E D E E E D
 E C D B D D D C D C D C D C D D
 B E C E D D C E C E C E D E D E
 E B E D E C E D D D B C E C E B
 B D D D C D B D B D D D D D B D
 C C E B D B E B B C C E E C D B
 C D C D B D B D B D C D C E C D
 D C E D E C C E D C C E B D E D
 D C B D D B C C D D D D C C D E
 D B C D D C D C C C D D C A D B`,
 'neoliberalism': `D A E A D D E A B B B E A B A A
 E D C E B B D D E E B D E E D A
 B B B E D D B B C D D C B C D B
 C D C E D B C C C E C C E B B C
 B E C D D B D B D B C E B E C D
 D C D E D C C D C D D D D E D D
 E B E B D C E B E B D C E C D C
 A E B E C E B E B E B E C E D E
 E A E B E B E B E B D B E B E B
 B D C D B E B D B D C E D E B D
 E B E B E A E A C B D D E B E B
 D B D B D C D D D C C C D C D C
 E B D C E C D D D C D D C D E C
 E B D B E B D B E C E C D B E D
 D B C D D C D C C D D D C A D B`,
 'nordic-social-democracy': `E A E A E E D A B C B E A C A A
 D E D E C B E D E D C D E D B A
 C D B E D E C B C E D D C C E B
 D C C E D B C D C D C C E B D C
 C E D E D B D B D A D D C D D D
 C D C E D E C E C E D E C E C D
 E E C C C E C D C E C D C D C E
 B E C E C D C E C E C E D E D E
 E B E D E C E D D D B B E C D B
 E B E B E B D B D B E B E A C B
 E B E B E B E A C B C D E B E B
 E B E B E C E B E B D B E D E B
 D C D E E D D E C D B E B D D E
 E B B C E B C D D E D E D D E E
 D B D C D C D C D C D D D A D B`,
 'objectivism': `D B D B D D E B A B A D B C A A
 E D C E A A B D E E B D E E E A
 A A B E B D A B B D D C B B D B
 B E B E D C B B C E C C E A A B
 D D D E C A C C D A D D D D D C
 E B E D E B D B D B E D E E E D
 E A E A E A E A E A E A E A E A
 A E A E A E A E A E A E A E A E
 E A E A E A E A E A E A E A E A
 A E A B A E A B A E B E A E A B
 E A E A E A E A E A E A E A E B
 D B D D C C E D C C B C D C C B
 E B E C E B D C E B E C D C E C
 D B C C D B D B D B D C C B E C
 D A C C E C E B D B D C D A E B`
};
