export default {
 'postmodernism': `D B D B D D C B B C B D B C B A
 E B E E B A B C E E B C E E C A
 A E B E B E B C B E C D B C E B
 B D B E E D B B B D B B E A D D
 B E B D D B D B E B B E B E B E
 C C C D C D B D C D C D C D C D
 D D C B C D C D C D D C C D C D
 C D C D C C C C C D C D D C D D
 D B C C D C E C C C B D D C C B
 D B D C D C C B D C D C D B C B
 E B E A E A E A C B D C E B E B
 E A E A E B E B E B E A E B E B
 C D C D C D C E B D B E C D C D
 E B D B E B D B D C E C E B E C
 E A E B E B E B D B E C E A E B`,
 'progressive-liberalism': `E A E A E E D A B D B E A D A A
 D D E E C B D D E D C D E E B A
 B D B E D E B B B E D D B C E B
 B D B E E C C C B D B B E A D D
 B E B D D B D B E B B E B E C E
 C D C D C D B E C D C E C D C D
 C E C D C E C E C E C D C E C E
 C D C D C C C D C D C D D D E D
 D C D D D D E D C D B E E C C C
 E B E B E B D B D B E B E B C B
 E A E A E A E A C B D C E B E B
 E B E B E B D B E B D B E C E B
 D C D D E C D E C D B E B D D E
 E B C C E B C C D E D E D D E E
 E A E C E B E B D B E D D A E B`,
 'republicanism': `E A E A E E C A B C B E A C A A
 D D D E C B D D E D C D E E C A
 B D B E D D B B C E D D B C E B
 C D C E D B C C C E C C E B D C
 B E C D D C D B D B C E B E C D
 C D C D D D C D C D C E C D C D
 E D C B C D C D C D D C C D C D
 B D C E C D C E C D C E D D D E
 D B D D D D E D D D B E E C C B
 D B D C D C D B D C D C D B C B
 E B E B E A E A C B D C E B E B
 D B D B D C D B D B D C E D D C
 D C D D D C C E C D B E C D D E
 E B C C E B D C D D D D D C E D
 D B D C D C D C D C D D D A D B`,
 'right-wing-populism': `E A E B E D D A C D B E A C A A
 C E B E B B E D C D E E E C D B
 E B E B E C E A E B E B E B B E
 E A E C A A E E E C E E B E B A
 D C E E C B B C D A E C E C E C
 E A E D E A E C E A E C E D E C
 E B E B E C E B E B D C E C D B
 D D E D D C D D E D D D D D E D
 E B E D E B E C E D B B E C E B
 B E C E B E B E B E C E D E B E
 D B E B D B E A B C C E E C D A
 B E C D B E B E B C A E C E A E
 E B E C E B C D E B D D B C E C
 D C A D E B D B E C D D C C E E
 D B C D D C D C C D D D C A D B`,
 'social-anarchism': `B A D A D D D A A D A D A E A A
 E B E E A A B D E E A B E E D A
 A B B E B E A B B E D C B C E B
 A E A E E D A A A E B B E A B D
 A E A D E A D B E B A E A E B E
 A A B D E A B B D B C D A E D B
 A B B B B B B B A B B B B B B B
 A D A D B D B C B D B D C D B D
 B A B A C B D A B A D B D A B A
 B B B B B B B B B B B B B B B B
 E A E A D A E A D A D B E A E B
 E A E A E B E B E B E A E B E B
 D C C D D D C E B D B E B D D E
 D A E A D A B A D A E A E A E B
 D B D C D C E B D C D D D A D B`,
 'social-liberalism': `E A D A E D C A B C B E A C A A
 D D D E C B D D E D C D E D C A
 B D B E D D C B C D D D B C D B
 C D C E D C C C C D C C E B D C
 B E B D D B D B E B B E B E C D
 C D C D D D C D C D D D D E C D
 E E C C C E C D C D D C C D C E
 B E C E C D C E C D C E D D D E
 E B D D E C E D D D B E E C D B
 D B E B D B D B D B E B E B C B
 E B E B D B E A C B D D E B E B
 D B D B D C D C D C C B D D D C
 D C D D E C C E C D B E C D D D
 E B C C E B C C D D D D C D E D
 D B D C D C D C D C D D D A D B`,
 'socialism': `D B D B D D D B B D B D B D B A
 D D D E C B D D E D C D E E B A
 B D B E D E B B B E D D B C E B
 B D B E D D C C B D B B E A D D
 B E B D D B D B E B B E B E C D
 C D C D D D B E C D C E C D C D
 B D B D B E C D B E C D C E C E
 C D D D D C D C D D C D D D E D
 C C C D C D D D C D B E E D B D
 D B E B D B D B D B E B E B C B
 E B E B E A E A C B D C E B E B
 D B D B D C D B D B D C D D D C
 D C D D D C C E C D B E B D D E
 E B C C E B C C D D D D D D E D
 D B D C D C E B D C D D D A D B`,
 'thatcherism': `E A D A E D C A B B B E A B A A
 C E C E C C E D D C D E E C C B
 D C D D E D D B D C E C D C D D
 D C D E D B D D C D D D E C C B
 D D E E C B C C D A E D D C E D
 E B E E E C D D C C E D E E E D
 E C E B B C E B E B D C E D E C
 B E B E D D C E C E C E D E D E
 E A E B E B E B E B B B E B E B
 B E C E B E B E B E C E D E B E
 C C E C D B E B B C C E D C D B
 C D C D C D B D C D C D D E C E
 D C E D E C C E D C C E B D E D
 C E A E C D C E C E C E C E D E
 D B C D D C D C C C D D C A D B`,
 'third-way': `E A E A E E D A B C B E A C A A
 D E D E C B E D E D C D E D B A
 C D B E D D C B C E D D C C E C
 D D C E D B C D C E C C E B D C
 D D D E C B D B D A D D D C D D
 B D B E D E C E C D D E C E C D
 E D D B C D D C D D D C D C D D
 B E C E C D C E C E C E D E D E
 E B E D E C E D D D B D E C D B
 C C D D D C C D C C D C D B C C
 E B E B E B E A C B C D E B E B
 D B D B D D D C D C D C D D D C
 D C D D E C D E C D C E B D D D
 E B B C E B C D D E D E C D E E
 D B D C D C D C D C D D D A D B`,
 'traditional-conservatism': `D B C B D D D B B B B D B B B A
 B E C D D C D D C C D D E C C B
 E B D C E D E A D C E C D B C E
 D C D E D B D D C D C D E D C B
 B E D D D C D B D B C E B E D D
 E B E D E B D C D B E D E D E C
 E D D B D D D C D C D C D D C E
 C D D D D C D D D D C D D D D D
 D B D C D C D C D C B C D C D B
 C D D D C D B D B D D D D D B D
 C D E D C D E B B D B E D D C D
 B E B D B E A E B D B E C E B E
 C D C D D D C E B D B E B D C E
 E B B C E B D C E D D D C C E D
 C B B D D C D C C D D D C A D B`,
 'trotskyism': `D B C B B D B B D D B D B E B B
 D C E E C B D D E D B D E E D B
 B D B E C E B B B E D D B C E B
 B D B E D D B B B D B B E A D D
 B E B E C D C B D A D D C D D D
 C D C D D C B D C D C E C D C D
 B E B E B E B E A E B E B E B E
 C D D D D C D C D D C D D D E D
 B E B E B E C E B E A E D E B E
 D B E B D B D B D B E B D B B B
 E A E A E A E A C B D C E B E B
 D B D B D C D C D C C B D C D C
 D C E D D C C E C D B E B D D E
 D D B D D C C D D E D E D D D E
 E A D C E B E B D C E D D A E B`,
 'zionism': `C C D B D D D B B B B D B B B A
 D D D E C B D D E D C D E D C A
 D D C E D D D B C D E D D B D D
 C D B E E C C C C D C C E C D B
 B E C D D B D B D B C E B E C D
 E B E D E B D D D C E D E D E D
 D D D D C E D D C D D C C D C D
 C D D E C D C D C D C D D D D E
 D C D E D D D D C D B D D D C D
 D B D C D C C C C C D C D B C C
 E B E B D B E A C B C D E B E B
 C C D C C D C D C C C D D D C D
 D C E D E C C E C D B E B D E D
 C D B D D C C D C D C D C D D E
 D B D C D C D C D C D D D A D B`
};
