// Fresh question-order decisions. A/B/C/D/E = -2/-1/0/+1/+2.
// These are manually assessed against the 240 literal statements, not
// transformations of previous answers or target axis percentages.
export default {
 'alt-lite': `DADA DDD A B D B D A C A A
 B D B D C D D D B C D D D B E B
 E B D C E C D A D B E B D A B D
 E B D D C A E E E C D D C E B A
 D C D D B C B D C A D C D B D B
 E A E C E B E C D B E C E D E C
 E C D B D C D B D B D C D C D B
 D C D D D B D C D C D D D C D D
 D B E C D C E C D D D B E C D B
 B D B E C E B D B D C E B D B D
 C C E C D B E A B C B E E D D B
 B D C D B D B E B D A E C D B E
 D B D C D B D C D C D C B C D C
 D B B D D C D B D C D C C C D D
 C B C D D D C C C D C D C B D C`,
 'american-conservatism': `DADA DDD A C C B E A C A A
 B E C E D D E D C C E E E C E B
 E B E C E D E A E B E B E B C E
 E B E D B A E E E D E E C E B B
 D D E E C B B D D A E C E C E C
 E A E D E B E C D B E D E E E C
 E B E B D C E B E B E D E C E B
 E B E B E B E C E B E D E C E D
 E B E D E C E D D E C B E C E B
 B E B E C E B E B E C E D E B E
 C C E B D B E A B C B E E D D B
 C D C D B E B E B C B D C E B D
 E B E D E B D C E B D C B C E C
 E B A D E B D B E C D D C C D E
 D B C D D C D C C D D D C A D B`,
 'anarcho-capitalism': `BA BA D D D A A D A D A D A A
 E B C E A A B D E E A B E E E A
 A A B E A D A B A C D C B B D B
 A E A E D D A A A E B B E A A C
 A E A D E A D B E B A E A E B D
 B A C D E A B A D B D B A E D B
 E A E A E A E A E A E A E A E A
 A E A E A E A E A E A E A E A E
 E A E A E A E A E A E A E A E A
 A E A B A E A B A E B E A E A B
 E A E A D A E A D A D B E A E B
 D B D B D C D E D B B C D C C B
 E B D B E B D B D C E C C B E B
 D A E A D A B A D A E A D A E B
 C B C D D D D C C D C D C A D B`,
 'authoritarian-capitalism': `B D C E B C A B D B D C D B D B
 B E C C D E E E B B E E D B B D
 D D D D E D D B D D E D D B D D
 D C E D C B D D D E E D C C B B
 C D D E C D C C D A D D D C D C
 E B E D E B D C D B E D E E E D
 E E D D D E D E C D C D D E C D
 C D D E D C D E D D D D D D E D
 D D D E D D D E B E B D D E D D
 C D D D D D B D B D D D D D C D
 D B E B D B E A C B C D E C D B
 C D C D B D B D B D C D C D C D
 E B E D E B D C D C C D B D E D
 B E A E C E B E C E B E C E C E
 D B C D D C D C C C D D C A D B`,
 'christian-accelerationism': `D C D B D D D A B C C D B C B A
 C D C D C D D D B C D D E C E B
 D B D C E D D B D C D C D B C D
 D C E D C B D D D E D D D D C B
 D C E E B C B D C A E C E C E B
 E A E D E B E C D B E D E D E C
 E C E C D D E C D C D D D D D C
 C D D E D C D D D D C D D D E D
 E B E D E C E D D D D B E C E B
 B D C D C E B D B D D E D D B D
 B D E D C D E B B D B E E D C B
 B E B D A E A E A D B E C C B E
 E A E B E B E B E B E C A B E B
 D C B D D C D C D D D D C D D E
 D B B D D C D C C D D D C A D B`,
 'christian-conservatism': `E A D A E D E A B C B E A C A A
 B D C E D C D D B D D D E C E A
 D C D D E D D B D C E C D C C D
 D C D E D B D D D D D D E C C B
 C E D D D C D B D B C D C D D D
 E B E D E B D C D B E D E D E C
 D C D B D D D C D C D C D C D D
 C D C D C C C D C D C D D D D D
 D B D C D C D C D C C C D C D B
 C D D D C D B D B D D D D D B D
 C C E B D B E A B C B E E D D B
 B E B D A E A E A D B E C E B E
 C D C D D D C E B D B D A D D E
 E B B C E B D C E D D D C C E D
 D B B D D C D C C D D D C A D B`,
 'christian-democracy': `E A E A E E E A B B B E A B A A
 B E C E C B E D D D D D E D B A
 D D D E E D C B D D E D D C D D
 D D D E D B D D C E D D E B D C
 C E D E D B D B D A D D C D D D
 B D B E D E C E B E D E C E C E
 E D D B C E D C D C D C D D C E
 B E C E D D C E C E C E D E D E
 E B E D E C E D D D B D E C D B
 C C D D D D C D B D D C D B B D
 D B E C D B E B B C C E E C D B
 C C D B E D B D E C C D D E D D
 D C D E D C C E C D B E A D D E
 E B B C E B D C E D D D D D E D
 D B C D D C D C C C D D C A D B`,
 'christian-social-democracy': `E A E A E E D A B C B E A C A A
 D D D E C B D D E D C D E D B A
 B D B E D E C B B E D D B C E B
 C D B E E D C C B D C B E A E D
 B E C D D B D B D B B E B E C D
 B D B E D E B E B E C E C E C D
 D E C C B E C D B E C D C D C E
 B E C E C D C E C D C E D D D E
 E B D D E C E D D D B C E C D B
 E B E B E B D B D B E B E A C B
 E B E B E B E A C B C D E B E B
 D B D B D C D B D B D C D D D C
 C D C D D D C E B D B E B D D E
 D C B C E B C C D E D D D D D E
 D B D C D C D C D C D D D A D B`,
 'christian-socialism': `E A E A E D D A B D B E A D A A
 D D D E C B D D D D C D E D B A
 B D B E D E C B B E D D B C E B
 B D B E E D B C B D B B E A E D
 B E C D D B D B D B B E B E C D
 B D B D D D B E B D C E C D C D
 B E B D B E B E B E C D B E B E
 C D D D D C D C C D C D D D E D
 C C C E C D D E B E B E D D B D
 E B E B E B D B D B E B E B D B
 C D E B D B E A B C B D E C D B
 D B D B D C C C D C D C D D D C
 C D C D D D C E B D B E B D D E
 D C B D D C C D D E D E D D D E
 D B D C D C D C D C D D D A D B`,
 'classical-liberalism': `D A C A E D E A A B A E A B A A
 E D C E A A D D E E B D E E D A
 B B B E D D B B C D D C B C D B
 B D B E D B B C C E C C E B B C
 B E C D D B D B D B C E B E C D
 D B D D E C D C C D D D D E D D
 E C E B D C D B E B D C D C D C
 A E B E C E B E B E B E C E D E
 E A E B E B E B E B D C E B D B
 B D C D C D B D B D C D D D B D
 E A E B E A E A C B D D E B E B
 D B D B D C D D D C C B D D D C
 D B D D E C D D C D D D C D D D
 D B C C D B D C D C D D C C D D
 D B D C D C D C D C D D D A D B`,
 'communism': `B B D D A C A B E B D C D B D B
 B E B C D E E E B A E E C B A D
 E C D C E D E A D C E C D B C E
 E B E D C A E E E D E E C D B B
 D D E E B D C C D A E C E C E C
 E A E D E B E C E B E D E D E C
 D E C D C E D E C E C D C E C E
 D D E D E C E D E D D E E D E D
 D E D E D E D E B E A E D E D E
 D C D D D D B D B D D D D B B D
 E B E B D B E A C D C D E B E B
 C D D C A D C E A C B D D D B D
 D C E E E C D E D D B E A E E E
 B E A E B E B E C E B E B E C E
 D B D C D C D C D C D D D A D B`,
 'communitarianism': `D B D B D D D B B C B D B C B A
 C E D D D C D D C D D D E C B A
 D D D D D D C B D D E D D B D D
 D C C E D B C D C D C C E B D C
 B E C D D C D B D B C E B E C D
 D C D D D C C D C D D D C D D D
 D D C C C D C D C D C D C D C D
 C D D D D C D D D D C D D D D D
 D B D D D D D D C D B D D D C C
 D B D C D C C D C C D C D B C C
 D B E B D B E B C C C D E C D B
 C D D C D D C D D C C D D D D D
 C D C D C D C E B D B E B D D E
 E B B C E B D C E D D D D C E D
 D B D C D C D C D C D D D A D B`,
 'conservative-centrism': `E A E A E D D A B B B E A B A A
 C E C E C B E D D D D D E D C A
 D D C D D D C B D D E D D C D D
 D C D E D B D D C D D D E B D C
 C E D E D B D B D B D D C D D D
 D C D E D D D D C D D D D E D D
 E D D B C E D C D D D C D D C E
 B E C E C D C E C D C E D D D E
 E B E C E C E C D C B D E C D B
 C C D C D C C D B C D C D B B D
 D B E C D B E B B C C E D C D B
 C C D C D D C D D C C D D E C D
 D C D D D C C E C D B E B D D E
 E B B C E B D C D D D D C C E D
 D B C D D C D C C C D D C A D B`
};
