import fs from 'node:fs';
const dir='profile-audit/reports/main-personalities-2026-10-05';
const src=(title,url,publisher,date='undated')=>({title,url,publisher,date});
function save(id,name,period,cutoff,lifespan,role,category,description,rows,sources){const axes=rows.map(([values,brief,counter,ids='1',gap])=>({values,brief,counter,sources:ids.split(',').map(x=>'source-'+x),...(gap?{gap}:{})}));fs.writeFileSync(`${dir}/${id}-spec.json`,JSON.stringify({id,name,period,cutoff,lifespan,role,category,description,scope:'Public positions and conduct during the specified period; this represents the individual rather than all party members or citizens.',axes,sources:[src(name+' — biographical and policy overview','https://en.wikipedia.org/wiki/'+encodeURIComponent(name.replaceAll(' ','_')),'Wikipedia'),...sources]},null,2));}
save('clement-attlee','Clement Attlee','1945–1951','1951-10-26','1883–1967','Prime Minister of the United Kingdom','Labour / democratic socialism','British prime minister whose government established the NHS and nationalised major industries.',[
['4040443011030100','Attlee governed through Parliament, contested elections and accepted defeat.','Parliamentary sovereignty differs from constitutional judicial review and direct recall.','1,2'],
['1333133311113111','His government used emergency powers and deployed troops during strikes, while retaining parliamentary criticism.','A democratic government can restrict protest; these powers do not establish approval of unlimited detention.','1,3'],
['3133133133133333','Postwar institutions retained a shared British identity while Commonwealth subjects possessed citizenship rights.','Commonwealth legal status does not demonstrate endorsement of every cultural accommodation.','1'],
['1333311113113112','Commonwealth citizens could settle; the government also worried about arrivals and labour conditions.','Legal entry rights coexisted with imperial assumptions and administrative caution.','1'],
['3343101010113113','Attlee supported NATO, nuclear weapons, conscription and Korean War deployment.','Earlier pacifism is outside this premiership; UN security and diplomacy still mattered.','1,3'],
['3113313323133313','He supported the UN and NATO while preserving sterling and British authority.','Alliance membership does not imply accepting every supranational ruling.','1,2'],
['1404131414141404','Utilities, transport and major industries were nationalised; the NHS expanded public provision.','The economy remained mixed rather than universally state owned.','1,2,3'],
['3133133311313313','Import and exchange restrictions protected the balance of payments during reconstruction.','International recovery cooperation and export needs limit a blanket protectionist reading.','1'],
['1414131313131314','Postwar rationing, investment direction and full-employment management shaped economic policy.','Private firms survived; comprehensive routine production targets were not universal.','1,3'],
['4141414131413131','Social insurance and assistance expanded under high postwar taxation.','Benefits were constrained by austerity and contributory eligibility.','1,2'],
['3131333131331311','Civil law prevailed while Anglican establishment, religious education and ceremonies continued.','Personal agnosticism is not evidence for removing established religious institutions.','1'],
['3131131131313133','Welfare and family reforms coexisted with conventional family and sexual norms.','Later support for homosexual law reform in 1958 falls outside this period.','1'],
['3131331311311333','New towns and nuclear development coexisted with national parks and planning controls.','Modern AI and genetic-enhancement questions have no exact period counterpart.','1,2'],
['1414131333131334','National industries and welfare programmes increased central coordination.','Local councils retained service and housing responsibilities.','1,2'],
['3131313131313131','His account of poverty stressed deprivation and social circumstances.','This supports a tentative social explanation, not specific claims about heredity or IQ.','1,3','The precise inherited-versus-social explanation is not documented; social reform is only contextual evidence, so domain-specific estimates remain especially uncertain.']
],[src('History of Clement Attlee','https://www.gov.uk/government/history/past-prime-ministers/clement-attlee','UK Government'),src('Clement Attlee — premiership','https://www.museumofpm.org/prime-ministers/clement-attlee/','Museum of the Prime Minister')] );
save('tony-blair','Tony Blair','1997–2007','2007-06-27','1953–','Prime Minister of the United Kingdom','Labour / Third Way','British prime minister associated with New Labour, devolution, public-service reforms and military intervention.',[
['4040443011030100','Competitive elections, human-rights legislation and parliamentary government framed his tenure.','A strong executive and criticism of scrutiny constrain claims of maximal institutional restraint.','1,2'],
['1333433431013113','Human Rights Act protections coexisted with ID cards, control orders and expanded terrorism powers.','Personal liberty and government secrecy were treated differently across policy areas.','1,2'],
['3133133133133333','Blair combined cultural diversity with integration duties and common citizenship.','Funding tied to integration qualified multicultural accommodation.','1,3'],
['1333311113313113','Labour opened economic migration and EU labour access while tightening asylum enforcement.','Economic openness did not imply permission for all irregular migrants to remain.','1,3'],
['4334101010014113','Kosovo, Sierra Leone, Afghanistan and Iraq demonstrated willingness to intervene abroad.','Northern Ireland diplomacy and negotiation prevent treating every dispute as a military question.','1,2'],
['1333131333331333','Blair favoured EU cooperation, alliances and international institutions.','He retained sterling and acted in Iraq despite disputes over UN authorisation.','1,2'],
['3331333331113334','Market provision and private finance operated alongside public NHS services and rail infrastructure.','Public funding is not the same as private ownership; essential assets were not uniformly privatised.','1,2'],
['1414131313131314','Open European and global trade accompanied business-oriented economic policy.','Strategic regulation and employment safeguards qualify unconditional liberalisation.','1,3'],
['3131313131333111','Market allocation and an independent central bank coexisted with minimum wages and targeted intervention.','Public-service planning and tax credits prevent treating him as laissez-faire.','1,2'],
['3131313131313131','Tax credits and public spending narrowed hardship without repudiating private earnings.','Welfare-to-work conditions and restraint on direct tax rates qualify redistribution.','1'],
['3131333131331331','Government did not require clergy approval, but faith schools and religious establishment remained.','Personal faith is not scored as support for theocracy.','1'],
['4141314131314131','Civil partnerships, adoption equality and changing social norms featured in government policy.','This period predates same-sex marriage legislation; some traditional institutions remained.','1,2'],
['3131331311311333','Modernisation and technological development were pursued alongside regulatory and environmental oversight.','Strong development support does not establish support for risky human enhancement.','1,2'],
['3131333133133313','Scottish and Welsh devolution increased regional authority, while public-service targets stayed central.','Devolution did not confer unilateral secession or unrestricted fiscal sovereignty.','1,2'],
['3131313131313131','Education, opportunity and social exclusion supplied his explanations of disadvantage.','They do not settle biology’s relative influence on stress, attention or temperament.','1','The causal claims are extrapolations from social-policy explanations; no exact personal position on most inherited-versus-social comparisons was located.']
],[src('History of Tony Blair','https://www.gov.uk/government/history/past-prime-ministers/tony-blair','UK Government'),src('The Immigration Legacy of Tony Blair','https://www.migrationpolicy.org/journal/feature/immigration-legacy-tony-blair','Migration Policy Institute','2007-05-10')] );
save('jeremy-corbyn','Jeremy Corbyn','2015–2019 Labour leadership','2019-12-31','1949–','Leader of the UK Labour Party','Labour / democratic socialism','British Labour leader who advocated public ownership, stronger welfare provision and less military intervention.',[
['4040443013030300','Elections, parliamentary scrutiny and a public Brexit vote were central to his political programme.','Specific recall mechanisms and expert-government hypotheticals are analogical estimates.','1'],
['1333131133314110','Civil liberties, peaceful protest and opposition to surveillance framed his programme.','Public safety and regulated firearms still justified state restrictions.','1'],
['1414331414314431','His programme supported multicultural recognition, Indigenous rights and minority protection.','Pluralism did not entail eliminating all shared civic requirements.','1'],
['1334411113114133','Migrant rights, family unity and refugee protection were supported.','Labour’s negotiated migration system was not an unlimited right of settlement.','1'],
['1413114014401414','Corbyn opposed Iraq and nuclear deterrence and prioritised conflict prevention.','Labour’s 2019 manifesto retained NATO and Trident commitments he personally disputed.','1,2'],
['1333131333331333','International solidarity and human-rights cooperation coexisted with longstanding EU scepticism.','The leadership period includes support for Remain and a negotiated Brexit referendum.','1'],
['1414131414141414','Utilities, rail, mail and broadband were proposed for public ownership.','The manifesto did not nationalise every private company or all routine contracting.','1,2,3'],
['3133133311313313','Trade was to protect labour standards and domestic capacity alongside international cooperation.','Worker protections are not evidence for every tariff or strategic ownership restriction.','1,2'],
['3134131314141313','Industrial strategy, wage floors and public investment accompanied continued private enterprise.','Consumer-led production and entrepreneurship remained legitimate.','1,2'],
['4141414141414141','His programme proposed substantial tax-funded redistribution and stronger income support.','Precise mechanisms such as compulsory compensated land redistribution remain inferred.','1,2'],
['4141114131114131','Civil law, religious freedom and opposition to religious discrimination framed his position.','State ceremonies and holidays are not equivalent to clergy control of legislation.','1'],
['4141414131314131','Equal treatment of LGBT people, gender equality and reproductive choice were supported.','All specific school and language policies are not individually documented.','1'],
['1333331313333334','Green industrial development and housing investment coexisted with environmental precaution.','Opposition to ecological harm does not entail opposition to all technical progress.','1,2'],
['3131333133134313','Regional empowerment and community ownership accompanied nationwide welfare standards.','Local participation does not imply unrestricted secession or local tax retention.','1,2'],
['4141314131313141','His explanations of inequality emphasised discrimination, education and social conditions.','Specific comparative genetic explanations remain weakly evidenced.','1','These are provisional causal estimates from social-equality explanations; support for equality alone cannot prove a biological or social theory.']
],[src('Labour Party manifesto 2019','https://general-election-2010.co.uk/2019-general-election-manifestos/Labour-Party-Manifesto-2019.pdf','Labour Party (archived manifesto)','2019-11-21'),src('Labour’s nationalisation policy','https://ifs.org.uk/publications/labours-nationalisation-policy','Institute for Fiscal Studies','2019-12-03')] );
save('joe-biden','Joe Biden','2021–2025 presidency','2025-01-20','1942–','President of the United States','Democratic Party / social liberalism','US president whose administration expanded infrastructure investment, industrial policy and climate spending.',[
['4040444011030300','Competitive elections and constitutional accountability were defended during his presidency.','Executive orders and a familial pardon complicate a maximal accountability reading.','1,3'],
['2333333313313131','Gun regulation and health measures coexisted with protest and constitutional speech protections.','Drug policy and national-security secrecy did not uniformly follow liberty claims.','1,2'],
['1414331414314331','Diversity and minority inclusion accompanied a shared American civic identity.','Recognition of diversity does not mean cultural expectations always override common law.','1,2'],
['3333313133313133','Legalisation and family pathways coexisted with removal and tighter 2024 asylum controls.','Early reform proposals differed from late-term border restrictions.','1,2'],
['3333101010113113','Alliance defence and aid to Ukraine and Israel coexisted with Afghanistan withdrawal.','Avoiding direct war with Russia qualifies military resolve; past Senate votes are outside scope.','1,2'],
['3133313333133313','NATO and Paris cooperation were strengthened while national currency and border authority remained.','US resistance to comprehensive international criminal jurisdiction limits supranationalism.','1,2'],
['3331313311133333','Private enterprise and providers operated alongside public infrastructure and subsidised services.','Industrial subsidies and public funding do not by themselves establish public ownership.','1,2'],
['3133133311313313','Buy American procurement and retained or raised tariffs accompanied allied trade cooperation.','Selective protection differs from comprehensive import exclusion.','1,2'],
['3133131313131311','Private production coexisted with CHIPS investment, wage support and sectoral industrial policy.','Industrial strategy did not create compulsory production targets for most businesses.','1,2'],
['4141313131413131','Expanded child tax credits and progressive tax proposals supported income redistribution.','Temporary benefits and legislative defeat limit claims of permanent universal expansion.','1,2'],
['4141114131114131','Civil institutions and reproductive law were defended independently of Biden’s Catholic belief.','Religious ceremonies and exemptions persisted without clerical legislative vetoes.','1,2'],
['4141414131314131','Marriage recognition, LGBT inclusion and reproductive choice were supported in this presidency.','Earlier DOMA and abortion positions are not silently projected into the scoped period.','1,2'],
['3131331311311333','Infrastructure, clean energy and AI adoption coexisted with safety and reliability safeguards.','A pro-investment policy is not approval of uncertain embryo or brain enhancement.','1,2'],
['3134131333133334','Federal civil-rights standards and national programmes coexisted with constitutional state powers.','States retained constitutions, police and taxation; unilateral secession was not endorsed.','1,2'],
['3131313131313131','His explanations of racial disparities emphasised discrimination and unequal opportunity.','Modern neurobiology comparisons are not established by these explanations.','1,2','Specific claims about IQ, temperament and inherited behaviour remain provisional; anti-discrimination policy is contextual evidence rather than a scientific causal position.']
],[src('The Biden-Harris Administration Record','https://www.presidency.ucsb.edu/documents/administration-fact-sheet-the-biden-harris-administration-record','American Presidency Project (White House primary record)','2025-01-17'),src('Joe Biden: Domestic Affairs','https://millercenter.org/president/biden/domestic-affairs','Miller Center, University of Virginia')] );
save('abraham-lincoln','Abraham Lincoln','1861–1865 presidency','1865-04-15','1809–1865','President of the United States','Republican Party / Unionism','US president during the Civil War who pursued emancipation and preservation of the Union.',[
['4033443011031100','Lincoln maintained wartime elections and representative government but endorsed restricted suffrage.','Black voting proposals remained limited; universal adult suffrage cannot be assumed.','1,3'],
['1333133331111113','Wartime habeas corpus suspension and dissent restrictions expanded executive authority.','The emergency context and eventual constitutional government qualify unlimited peacetime power.','1,2'],
['3133133133133333','He rejected nativism while sustaining a shared national political identity.','Colonisation proposals and Indigenous dispossession constrain modern pluralist analogies.','1,3'],
['1333311113113112','The 1864 immigration law encouraged labour arrivals and opposed nativist exclusion.','A modern refugee and welfare system has no precise period equivalent.','1'],
['3333101010113113','Preserving the Union justified conscription and a large war effort.','His avoidance of overseas escalation differs from expansionist warfare.','1,2'],
['4113113131313111','US sovereignty and Union preservation dominated foreign and constitutional policy.','Diplomacy with European powers mattered without supranational institutions.','1,2'],
['3331313311113332','Private business and railways received public support; land-grant institutions had public roles.','Funding infrastructure did not entail state ownership of most commerce.','1,2'],
['4133133311313313','Protective tariffs and domestic development were key economic priorities.','National development did not require banning every foreign supplier or service.','1,2'],
['3133131311331311','Private enterprise coexisted with public infrastructure, banking legislation and wartime direction.','Modern minimum wages and monetary competition are inferred analogies.','1,2'],
['3131311111313131','Progressive wartime taxation and opportunity were supported without a modern redistributive welfare state.','He resisted sweeping confiscation and redistribution of Southern land.','1'],
['3131333131331311','Civil law operated without clerical approval, while public rhetoric and ceremonies invoked God.','Personal religious uncertainty is separate from institutional religion.','1'],
['3131131131313133','Emancipation challenged an institution while conventional family and sexual customs persisted.','Anti-slavery conviction is not evidence for modern abortion or marriage equality.','1'],
['3131331311311333','Railway development and invention coexisted with the Yosemite preservation grant.','Modern high-risk biotechnology is an uncertain historical analogy.','1,2'],
['1414131333131314','He rejected unilateral secession and used federal authority to preserve the Union.','State constitutions and ordinary local administration continued.','1,2'],
['3131313131313131','Self-improvement and education stressed experience; racial equality views evolved but remained limited.','Emancipation does not prove a modern rejection of all biological group explanations.','1,3','These are especially uncertain historical estimates; neither equal natural rights nor educational opportunity settles modern genetics or inherited group differences.']
],[src('Abraham Lincoln: Domestic Affairs','https://millercenter.org/president/lincoln/domestic-affairs','Miller Center, University of Virginia'),src('Lincoln on Slavery','https://www.nps.gov/liho/learn/historyculture/slavery.htm','US National Park Service')] );
export {save,src};
