import {save,src} from './spec-batch1.mjs';
save('vladimir-lenin','Vladimir Lenin','1917–1924 Soviet leadership','1924-01-21','1870–1924','Revolutionary and Soviet head of government','Bolshevism / Marxism–Leninism','Bolshevik revolutionary whose government established one-party rule and a predominantly state-directed economy.',[
['0301000010010100','Bolshevik authority displaced the Constituent Assembly and excluded rival parties.','Workers’ councils and revolutionary participation were not equal competitive multiparty elections.','1,2,3'],
['0333433431111114','The Cheka, censorship and coercion defended revolutionary authority.','Pre-revolutionary opposition to tsarist repression differs from post-revolutionary governing practice.','1,2'],
['1414331414314331','National self-determination and minority languages challenged imperial assimilation.','Central party power and revolutionary political conformity qualified cultural autonomy.','1,3'],
['1333311113113113','International worker solidarity and revolutionary asylum supply comparatively open context.','Security and wartime controls complicate ordinary immigration analogies.','1,3'],
['4333101010114113','Civil war and revolutionary military organisation involved substantial force.','Brest-Litovsk accepted costly concessions to end war and preserve the revolution.','1,2'],
['3131313131313131','Revolutionary internationalism coexisted with state and party sovereignty.','International class solidarity does not prove acceptance of contemporary interstate courts.','1,3'],
['0404040404040404','Major industry and banking were nationalised.','The New Economic Policy restored limited private production and trade.','1,2'],
['4131131311311311','A state foreign-trade monopoly and national economic control limited independent trade.','Pragmatic foreign deals and NEP were substantial exceptions to autarky.','1'],
['0404040404040404','Central direction and controls predominated while NEP restored market mechanisms.','Period variation is substantial; small producers and trade were not uniformly directed after 1921.','1,2'],
['4141414141414141','Land redistribution and elimination of class privilege pursued material equality.','Confiscation differed from the compensated land transfers in the question.','1,3'],
['4141014140104140','Secular socialist civil authority excluded clerical power.','Anti-religious repression is not synonymous with liberal religious freedom.','1'],
['4131314131313131','Civil divorce, reproductive reform and women’s participation broke with older institutions.','Modern gender identity and same-sex marriage were not established policy endorsements.','1'],
['3131331311311333','Electrification and technical modernisation were revolutionary priorities.','Contemporary biomedical risk questions remain low-confidence translations.','1'],
['1414131333131334','National self-determination coexisted with tightly centralised party authority.','Formal federal rights and opposition to Stalin’s national chauvinism qualify centralism.','1,3'],
['3131313131313131','Class relationships, education and social transformation explained political behaviour.','Historical materialism does not answer every modern psychological genetics comparison.','1,3']
],[src('Vladimir Lenin — historical overview','https://www.history.com/articles/vladimir-lenin','HISTORY'),src('The State and Revolution — Chapter II','https://www.marxists.org/archive/lenin/works/1917/staterev/ch02.htm','Marxists Internet Archive','undated')] );
save('adam-smith','Adam Smith','1759–1790 mature published thought','1790-07-17','1723–1790','Moral philosopher and political economist','Classical liberalism / Scottish Enlightenment','Scottish philosopher and economist associated with commercial liberty, moral sympathy and public institutions.',[
['3030333013031100','Accountable law and criticism of political privilege supply representative-government context.','Modern universal suffrage and referendums are analogies rather than explicit institutional proposals.','1,2'],
['3331331133314330','Natural liberty and protection against arbitrary rule constrained state interference.','Civil justice and public order remained legitimate functions; personal drug policy is inferred.','1,2,3'],
['3133133133133333','Commercial society and criticism of prejudice supply cultural-tolerance context.','Eighteenth-century national and colonial assumptions limit modern multicultural translations.','1,2'],
['1333311113113113','Free labour movement and criticism of settlement restrictions support mobility.','Poor-law settlement criticism does not precisely settle modern refugee or welfare policy.','1,3'],
['1333113013301333','Defence was a legitimate public duty while war and empire imposed heavy costs.','A standing army could be preferable in advanced societies; he was not an absolute pacifist.','1,3'],
['4113313131313113','National justice and defence coexisted with commercial cooperation.','Modern binding international agencies and shared currency lack direct equivalents.','1,3'],
['4031333131113311','Private commercial enterprise was preferred in ordinary production.','Public works and education could be publicly supported where private incentives were inadequate.','1,3'],
['0404040404040404','Criticism of mercantilism favoured open trade and competition.','Defence-related navigation restrictions and strategic retaliation were qualified exceptions.','1,3'],
['4040404040414030','Market prices and decentralised enterprise were preferred.','Banking regulation, public works and education qualify a maximal laissez-faire interpretation.','1,2,3'],
['1313331113131113','Tax fairness and public revenue coexisted with acceptance of commercial income differences.','Some taxes on the rich could exceed simple proportionality; he did not advocate modern comprehensive transfers.','1,3'],
['4141114131114131','Civil authority and competing religious sects limited ecclesiastical domination.','Historical established churches and moral education qualify contemporary complete separation.','1,2,3'],
['1313131313131313','Moral propriety and conventional family expectations reflected eighteenth-century context.','Sympathy and criticism of privilege challenge a blanket endorsement of every inherited custom.','1,2'],
['3131331311311333','Commercial improvement and productive innovation were valued.','Modern neural or embryo enhancement has no direct counterpart.','1,3'],
['3134133131311313','Local financing could suit local public works while national defence and justice remained.','Modern constitutional secession and Indigenous sovereignty are uncertain translations.','1,3'],
['3131333131333133','Habit, education and social interaction shaped conduct alongside natural sympathy and passions.','Universal human dispositions are not evidence of inherited race differences.','1,2,3']
],[src('Adam Smith’s Moral and Political Philosophy','https://plato.stanford.edu/entries/smith-moral-political/','Stanford Encyclopedia of Philosophy'),src('An Inquiry into the Nature and Causes of the Wealth of Nations','https://www.gutenberg.org/files/3300/3300-h/3300-h.htm','Project Gutenberg')] );
save('mary-wollstonecraft','Mary Wollstonecraft','1790–1797 political writing','1797-09-10','1759–1797','Political philosopher and writer','Republican feminism / Enlightenment radicalism','British writer who defended women’s education and challenged hereditary political and social privilege.',[
['4040443013030100','Republican representation and criticism of hereditary authority favoured accountable government.','Exact universal suffrage and modern judicial design remain reconstructed responses.','1,2,3'],
['3331331133314310','Reason, civil liberty and criticism of arbitrary authority favoured personal independence.','Moral duties and modesty do not automatically imply legal prohibition.','1,2,3'],
['3133133133133333','Universal reason and criticism of inherited prejudice support cultural equality.','National education and contemporary European assumptions qualify modern accommodation analogies.','1,2,3'],
['1333311113113113','Universal rights and cosmopolitan revolutionary sympathies supply open-movement context.','No detailed modern numerical, asylum or welfare admissions scheme was established.','1,2'],
['1333113013301333','Criticism of standing military hierarchies and arbitrary power favoured peaceful civic life.','Support for revolutionary reform does not entail pacifism at all costs.','1,3'],
['3131313131313131','Universal human rights and republican solidarity crossed borders.','This is distinct from approval of every contemporary supranational institution.','1,2'],
['3133131313131313','Criticism of unequal property and support for public education limited exclusive private provision.','She did not articulate modern nationalisation across all industries.','1,2,3'],
['1314131313131313','Criticism of aristocratic privilege and commercial dependence supplies tentative open-trade context.','Specific modern tariffs and strategic investment rules remain undocumented.','1,2'],
['3133131313131313','Independent livelihoods coexisted with national educational responsibilities.','No modern comprehensive economic production plan was established.','1,3'],
['3131313131313131','Economic independence and criticism of great inequality support social opportunity.','Modern progressive taxes and compensated land redistribution are analogical estimates.','1,2,3'],
['3131333131331311','Religious moral reasoning coexisted with criticism of ecclesiastical and inherited authority.','Belief in God does not establish clerical approval of civil policy.','1,3'],
['4131111113313131','Women’s education and equal rational capacity challenged prescribed dependency.','Modesty, maternal duties and sexual virtue limit automatic attribution of contemporary sexual liberalism.','1,2,3'],
['3131331311311333','Educational improvement and reason favoured beneficial development.','Modern technology risk thresholds have no direct counterpart.','1,3'],
['3134131333131333','National education coexisted with republican accountability and local participation.','Modern federal and Indigenous jurisdiction questions are especially remote analogies.','1,3'],
['4141313131313141','Gendered education and dependence, rather than inferior rational nature, explained women’s apparent disadvantages.','Reason’s universality does not establish that every temperamental trait is solely social.','1,2,3']
],[src('Mary Wollstonecraft','https://plato.stanford.edu/entries/wollstonecraft/','Stanford Encyclopedia of Philosophy'),src('A Vindication of the Rights of Woman','https://www.gutenberg.org/cache/epub/3420/pg3420.html','Project Gutenberg')] );
save('ayn-rand','Ayn Rand','1957–1982 published Objectivist thought','1982-03-06','1905–1982','Novelist and philosopher','Objectivism / laissez-faire capitalism','Russian-born American writer who defended individual rights, capitalism and secular rationalism.',[
['4030334013030100','Individual rights and constitutional limits constrained majority power.','She rejected unrestricted majority rule; modern recall and referendums were not central proposals.','1,2'],
['4331331133314340','Individual rights and opposition to coercion favoured personal freedom.','Government retained courts, police and defence; moral disapproval differs from criminal prohibition.','1,2'],
['3133133133133333','Individual rather than racial identity opposed collectivist racial judgement.','Her assessments of Indigenous peoples and cultural development qualify broad multicultural endorsement.','1,3'],
['1333311113113113','Individual rights and migration for opportunity supply relatively open entry context.','Tax-funded migrant welfare conflicts with her general rejection of compulsory welfare.','1,2'],
['3333101010113113','National self-defence and support for Israel coexisted with opposition to Vietnam and conscription.','These positions do not imply universal non-intervention or automatic support for every war.','1'],
['4113113131313111','A rights-protecting national government retained authority against international collectivism.','Commercial openness and migration differ from supranational political sovereignty.','1,2'],
['4040444040404040','Laissez-faire capitalism rejected state commercial ownership.','Government’s police, military and courts were distinct from commercial enterprises.','1,2'],
['0404040404040404','Voluntary trade and competition opposed protective restrictions.','Security against aggressive states supplied a possible exception to ordinary commerce.','1,2'],
['4040404040404040','Voluntary prices, wages and investment opposed government economic planning.','Fraud and rights protection remained legitimate legal constraints.','1,2'],
['0404040404040404','Property rights opposed compulsory income and wealth redistribution.','Voluntary charity was permissible; social hardship did not justify coerced transfer in her account.','1,2'],
['4141014140104140','Atheism and rational civil government rejected religious state authority.','Individuals retained rights to religious belief and voluntary institutions.','1,2'],
['3131114131313113','Abortion rights and rejection of enforced convention coexisted with disapproval of homosexuality and conventional femininity.','Legal non-interference does not establish equal social acceptance of same-sex families.','1,2'],
['4131331311311333','Productive invention and human development were valued over restrictions justified by unproven collective fears.','Rights and genuine safety limits qualify every speculative enhancement analogy.','1,2'],
['3134133131310113','Constitutional individual rights and local institutions could constrain national power.','Indigenous collective jurisdiction conflicted with her property account; local power was not unlimited.','1,2'],
['3131333131333133','Volition, conceptual learning and rejection of racial collectivism emphasised chosen conduct.','Free will does not eliminate biological temperament or prove each quantitative heredity comparison.','1,2,3']
],[src('Ayn Rand','https://plato.stanford.edu/entries/ayn-rand/','Stanford Encyclopedia of Philosophy'),src('Racism — collected statements by Ayn Rand','https://aynrandlexicon.com/lexicon/racism.html','Ayn Rand Lexicon')] );
