import {save,src} from './spec-batch1.mjs';
save('emmanuel-macron','Emmanuel Macron','2017–2024 presidency','2024-12-31','1977–','President of France','Renaissance / liberal centrism','French president associated with European integration, market-oriented reform and public investment.',[
['4033334013031100','Competitive elections and constitutional review continued under a strong presidency.','Article 49.3 bypassed a parliamentary vote but remained subject to a no-confidence procedure.','1,3'],
['1333433431113111','Protest policing and counter-terrorism measures emphasised order alongside civil rights.','Constitutional review and freedom of opposition persisted.','1'],
['4131134131331114','Republican integration and secular public institutions favoured a shared civic identity.','Recognition of diverse origins did not grant every religious accommodation.','1'],
['3333311133313111','Managed migration combined work routes with stronger removal powers.','Judicial rejection of some restrictions limits attribution of the entire proposed law.','1,3'],
['3334101010113113','Military capability and intervention accompanied European security cooperation.','Diplomacy and negotiated settlement remained priorities; supporting defence is not unlimited war.','1,2'],
['1314131313331333','European integration and pooled authority qualified national autonomy.','Independent French deterrence and strategic autonomy remained important.','1,2'],
['3331333331133334','Privatisation and business investment coexisted with public health and strategic enterprises.','EDF renationalisation is a substantial strategic exception.','1'],
['1314131313131314','European common trade rules and open investment favoured trade.','European strategic autonomy and safeguards qualified unconditional openness.','1,2'],
['4131431311133311','Market-oriented labour reform coexisted with industrial incentives and a legal wage floor.','France retained substantial public coordination and regulated essential sectors.','1'],
['1313131313131313','Tax and pension reforms prioritised investment and fiscal sustainability.','Benefits and crisis assistance persisted; this is relative preference rather than abolition of welfare.','1,3'],
['4141114131114131','Secular republican civil authority remained the legal foundation.','Religious heritage and holidays persisted without clerical legislative control.','1'],
['4131314131313131','Marriage equality, assisted reproduction and constitutional abortion protection reflected social reform.','Age and consent limits and family preferences qualify every possible extension.','1'],
['3131331311311333','Nuclear power, infrastructure and technical industry were promoted.','Medical and ecosystem risks retained regulation; no exact enhancement response is documented.','1,2'],
['1414131333131334','National institutions directed taxation, education and public policy.','Corsican autonomy discussions and regional government supply counter-evidence.','1'],
['3131333131333133','Education and opportunity policy supply contextual social explanations.','No comprehensive heredity doctrine was located; these comparisons have low confidence.','1']
],[src('European action of the President of the Republic','https://www.elysee.fr/en/emmanuel-macron/bilan-de-laction-europeenne-du-president-de-la-republique.fr','Élysée Palace'),src('France’s constitutional court rejects several measures in controversial immigration law','https://apnews.com/article/83d89fd9578214d3e5c1f38da1bb9bf3','Associated Press','2024-01-25')] );
save('fidel-castro','Fidel Castro','1959–2006 leadership','2006-07-31','1926–2016','Cuban revolutionary and head of government','Communist Party of Cuba / Marxism–Leninism','Cuban revolutionary leader whose government expanded public services and imposed one-party political rule.',[
['0301001010010101','One-party government excluded competitive national opposition.','Organised participation and local selection did not provide equal multiparty national competition.','1,2'],
['0333433431111114','Political detention, censorship and restrictions prioritised revolutionary state authority.','Ordinary welfare provision does not negate repression of political dissent.','1,2'],
['3133133133133333','A common revolutionary Cuban identity coexisted with recognised cultural traditions.','Independent cultural and religious activity faced varying restrictions.','1'],
['4133103333313111','State-controlled movement and settlement provide restrictive admissions context.','Emigration controls differ from immigration rules; modern admissions estimates remain weak.','1'],
['4334101010114113','Military involvement abroad and revolutionary assistance demonstrated interventionist capacity.','International solidarity and resistance to invasion supplied different justifications from territorial conquest.','1,3'],
['4113113131313111','Sovereignty and anti-imperialism coexisted with Soviet alignment and international solidarity.','Solidarity did not mean accepting adverse international legal intervention.','1,3'],
['0404040404040404','Nationalisation established predominantly public ownership.','Small private and tourism-linked exceptions expanded during the 1990s.','1'],
['4131131311311311','State-controlled trade and domestic protection accompanied dependence on external partners.','The US embargo is imposed externally and is not evidence of his desired tariff policy.','1,3'],
['0404040404040404','National plans, price controls and directed production organised the economy.','Limited markets and private activities qualified complete command uniformity.','1'],
['4141414141414141','Land reform, wages and social provision aimed to reduce class inequality.','Transfers in a largely public economy do not map exactly to progressive-tax mechanisms.','1,3'],
['4141114131114131','Civil socialist institutions displaced clerical power.','Religion regained some public space in the 1990s and a papal visit was welcomed.','1'],
['3131334131313113','Women’s employment and legal abortion coexisted with early persecution of sexual minorities.','Later changes qualify early restrictions, but post-2006 regret is outside scope.','1,2'],
['3131331311311333','Biotechnology, education and technical development received state support.','Environmental protection and medical controls qualify assumptions about unrestricted adoption.','1'],
['0414030313130314','National party authority directed major public institutions.','Local popular organisations did not possess independent regional sovereignty.','1,2'],
['3131313131313131','Socialist education and changed social conditions were understood to reshape behaviour.','This does not settle every biological contribution; exact modern comparisons are uncertain.','1,3']
],[src('Cuba: Fidel Castro’s Record of Repression','https://www.hrw.org/news/2016/11/26/cuba-fidel-castros-record-repression','Human Rights Watch','2016-11-26'),src('Speech to the United Nations General Assembly','https://www.walterlippmann.com/fc-09-26-1960.html','Cuban speech archive hosted by Walter Lippmann','1960-09-26')] );
save('lula-da-silva','Luiz Inácio Lula da Silva','2003–2010 presidency','2011-01-01','1945–','President of Brazil','Workers’ Party / social democracy','Brazilian president whose first two terms combined poverty reduction programmes with a mixed, internationally connected economy.',[
['4040444013030100','Competitive elections and constitutional institutions continued through two terms.','Coalition scandals and executive influence qualify claims of flawless accountability.','1'],
['1333333311113111','Civil liberties coexisted with ordinary policing and public-order powers.','Democratic inclusion does not imply rejection of all surveillance or preventive measures.','1'],
['1414331414314331','Recognition of Afro-Brazilian and Indigenous communities supported plural national identity.','Common Portuguese-language institutions and integration remained.','1'],
['1333311113113113','Migrant regularisation and humanitarian inclusion support comparatively open settlement.','National administration and eligibility controls did not disappear.','1'],
['1333113013301333','Diplomacy and non-intervention coexisted with defence investment and the Haiti mission.','Peacekeeping and security capability are exceptions to complete pacifism.','1'],
['3131313131313131','Regional and global cooperation accompanied strategic sovereignty.','South–South cooperation is not endorsement of every binding supranational ruling.','1'],
['3133131413131314','Public banks and strategic enterprises coexisted with private investment.','Neither universal nationalisation nor unrestricted privatisation describes the period.','1'],
['3133133311313313','Export growth and negotiated trade accompanied industrial protection.','National-development priorities qualified universal trade liberalisation.','1'],
['3134131313131313','Markets and fiscal continuity coexisted with public credit and industrial policy.','Directed development is not compulsory targets for every producer.','1,2,3'],
['4141413131414141','Bolsa Família and higher wage floors prioritised poverty reduction.','Targeted conditional transfers and fiscal continuity qualify maximal equalisation.','1,2,3'],
['4141114131114133','Civil constitutional authority coexisted with religious consultation and public traditions.','Personal religion and coalition ties do not establish clerical veto powers.','1'],
['3131313131313131','Social inclusion and women’s participation coexisted with cautious reproductive and family policy.','Later presidencies and court-led reforms are outside this assessment.','1'],
['3131331311311333','Infrastructure and development investment coexisted with environmental programmes.','Biomedical enhancement questions remain uncertain analogies.','1'],
['3134131333131334','Federal institutions combined national social programmes with states and municipalities.','National standards did not extinguish constitutional state autonomy.','1'],
['3131313131313131','Education and poverty reduction emphasised social conditions and opportunity.','These policies do not directly establish exact genetic comparisons.','1,2,3']
],[src('Programa Bolsa Família — policy discussion','https://www.ipea.gov.br/desafios/index.php?id=2945%3Acatid%3D28&option=com_content','Institute for Applied Economic Research, Brazil'),src('From Fome Zero to Bolsa Família: Social Policies and Poverty Alleviation under Lula','https://www.cambridge.org/core/journals/journal-of-latin-american-studies/article/abs/from-fome-zero-to-bolsa-familia-social-policies-and-poverty-alleviation-under-lula/19B18EF8AC1575087A3242C540B08DF1','Cambridge University Press')] );
save('javier-milei','Javier Milei','2023–2024 first presidential year','2024-12-31','1970–','President of Argentina','La Libertad Avanza / libertarian conservatism','Argentine president associated with radical market liberalisation, spending cuts and socially conservative positions.',[
['4033333013031100','Competitive elections and constitutional institutions coexisted with extensive executive decrees.','Congress and courts constrained some proposals; radical policy is not abolition of elections.','1,3'],
['4331331133314341','Economic and personal liberty coexisted with strict controls on obstructive protests.','Restrictions on gatherings and order distinguish practice from maximal libertarian rhetoric.','1,3'],
['3133133133133333','A shared Argentine identity accompanied individual equality rhetoric.','Exact accommodation spending and cultural exceptions are not established.','1,2'],
['1333311113113113','First-year liberal economic rhetoric provides open-movement context.','Later 2025 immigration restrictions are excluded; welfare eligibility analogies remain uncertain.','1,2'],
['3333111010113113','US and Israeli alignment and defence capability coexisted with limited intervention.','Foreign-policy rhetoric does not demonstrate every preventive-war threshold.','1'],
['4113113131313111','National autonomy and rejection of socialist international blocs coexisted with Western alignment.','Proposed dollarisation qualifies the usual nationalist currency preference.','1,2'],
['4040444040404040','Broad privatisation proposals preferred private enterprise and service delivery.','Congressional limits and retained enterprises qualify realised implementation.','1,2,3'],
['0404040404040404','Trade opening and reduced barriers followed free-market arguments.','Implementation was gradual and some taxes and controls remained in 2024.','1,2'],
['4040404040404040','Deregulation, market prices and monetary alternatives were central priorities.','Some controls persisted temporarily; direction is assessed rather than every realised outcome.','1,2'],
['0404040404040404','Austerity and individual property arguments opposed redistribution as a general aim.','Targeted child and food assistance increased, qualifying rejection of every transfer.','1,2,3'],
['3131333131331311','Religious language and conservative values coexisted with civil legislative institutions.','Personal faith does not imply a clerical veto or religious courts.','1,2'],
['1313130313131313','Opposition to abortion and progressive gender policy reflected social conservatism.','Legal non-interference in private relationships differs from social acceptance.','1,2'],
['3131331311311333','Market-led technical development was favoured over precautionary economic restriction.','No exact endorsement of risky embryo or neural enhancement was established.','1,2'],
['3134133131311313','Federal institutions and reduced central spending support some local fiscal responsibility.','Presidential decrees and national enforcement complicate decentralising rhetoric.','1,3'],
['3131333131333133','Individual choice and rejection of structural explanations coexist in his rhetoric.','Market beliefs do not imply biological race explanations; these comparisons are weakly evidenced.','1,2']
],[src('Special address by Javier Milei, President of Argentina','https://www.weforum.org/stories/geo-economics-and-politics/special-address-by-javier-milei-president-of-argentina/','World Economic Forum','2024-01-18'),src('Argentina’s Milei marks one year in office as his shock therapy reshapes the economy','https://apnews.com/article/18efe55d81df459792a038ea9e321800','Associated Press','2024-12-10')] );
