import fs from 'node:fs';
const sources={};
function s(id,title,url,publisher,date='undated'){sources[id]={title,url,publisher,date};}
s('liberalism','Liberalism: classical and egalitarian traditions','https://plato.stanford.edu/entries/liberalism/','Stanford Encyclopedia of Philosophy');
s('mill','On Liberty (1859)','https://www.gutenberg.org/files/34901/34901-h/34901-h.htm','Project Gutenberg');
s('smith','The Wealth of Nations (1776)','https://www.econlib.org/library/Smith/smWN.html','Econlib / Liberty Fund');
s('conservatism','Conservatism: tradition, reform and authority','https://plato.stanford.edu/entries/conservatism/','Stanford Encyclopedia of Philosophy');
s('kirk','Ten Conservative Principles','https://kirkcenter.org/conservatism/ten-conservative-principles/','Russell Kirk Center');
s('burke','Reflections on the Revolution in France (1790), collected works III','https://www.gutenberg.org/files/15679/15679-h/15679-h.htm','Project Gutenberg');
s('herzl','The Jewish State (1896)','https://www.gutenberg.org/files/25282/25282-h/25282-h.htm','Project Gutenberg');
s('zionism-nli','Zionism (indexed excerpt; full page blocked)','https://www.nli.org.il/en/discover/israel/zionism','National Library of Israel');
s('herzl-institute','Theodor Herzl (indexed excerpt)','https://herzlinstitute.org/en/theodor-herzl/','Herzl Institute');
s('mao','On the People’s Democratic Dictatorship (1949)','https://www.marxists.org/reference/archive/mao/selected-works/volume-4/mswv4_65.htm','Marxists Internet Archive','1949-06-30');
s('mao-democracy','On New Democracy (1940)','https://www.marxists.org/reference/archive/mao/selected-works/volume-2/mswv2_26.htm','Marxists Internet Archive');
s('mao-state','Service memorandum on Mao’s New Democracy, including contemporary qualifications','https://history.state.gov/historicaldocuments/frus1944v06/d345','United States Department of State','1944-05-14');
s('mao-peasant','Mao: Report on the Peasant Movement in Hunan (1927)','https://sourcebooks.web.fordham.edu/mod/1927mao.asp','Fordham University');
s('trotsky','The Transitional Program, Part 1 (1938)','https://www.marxists.org/archive/trotsky/1938/tp/tp-text.htm','Marxists Internet Archive');
s('trotsky-democracy','The Transitional Program, Part 2: soviets and workers’ democracy','https://www.marxists.org/archive/trotsky/1938/tp/tp-text2.htm','Marxists Internet Archive');
s('socialism-iep','Socialism: ownership, markets and participatory planning','https://iep.utm.edu/socialis/','Internet Encyclopedia of Philosophy');
s('socialism-sep','Socialism: normative principles and institutional alternatives','https://plato.stanford.edu/entries/socialism/','Stanford Encyclopedia of Philosophy');
s('neoliberalism','Neoliberalism: Hayek, Friedman and Buchanan tradition','https://plato.stanford.edu/entries/neoliberalism/','Stanford Encyclopedia of Philosophy');
s('mps','Statement of Aims','https://montpelerin.org/statement-of-aims/','Mont Pelerin Society','1947-04-08');
s('imf','Neoliberalism: Oversold? (indexed excerpt; full text blocked)','https://www.imf.org/external/pubs/ft/fandd/2016/06/ostry.htm','International Monetary Fund');
s('ecosocialism','An Ecosocialist Manifesto (2001)','https://www.cnsjournal.org/an-ecosocialist-manifesto/','Capitalism Nature Socialism');
s('ecosocialist-programme','Manifesto for an ecosocialist revolution','https://fourth.international/en/node/736','Fourth International');
s('republicanism','Republicanism: non-domination and constitutional government','https://plato.stanford.edu/entries/republicanism/','Stanford Encyclopedia of Philosophy');
s('pettit','Republican freedom, social justice, and democracy (author abstract)','https://collaborate.princeton.edu/en/publications/republican-freedom-social-justice-and-democracy/','Princeton University');
s('rawls','John Rawls: public justification and fair opportunity (comparative context)','https://iep.utm.edu/rawls/','Internet Encyclopedia of Philosophy');
s('alt-adl','From Alt Right to Alt Lite: Naming the Hate','https://www.adl.org/resources/backgrounder/alt-right-alt-lite-naming-hate','Anti-Defamation League');
s('alt-ma','Cindy Ma: What is the lite in alt-lite?','https://journals.sagepub.com/doi/10.1177/20563051211036385','SAGE / Social Media + Society');
s('alt-splc','Investigating pathways to the alt-right (indexed research excerpt; page blocked)','https://www.splcenter.org/resources/reports/mcinnes-molyneux-and-4chan-investigating-pathways-alt-right/','Southern Poverty Law Center');
s('christian-values','Our Vision and Our Values','https://www.christiansontheleft.org.uk/our-vision-values','Christians on the Left');
s('christian-history','Our History: Christian Socialism and common ownership','https://www.christiansontheleft.org.uk/our-history','Christians on the Left');
s('christian-lse','Christian Socialism in British Politics (indexed author excerpt; page challenge)','https://blogs.lse.ac.uk/politicsandpolicy/christian-socialism-in-british-politics/','London School of Economics');
s('christian-victorian','Christian Socialism in Victorian England','https://www.victorianweb.org/victorian/history/socialism/christiansocialism.html','Victorian Web');
s('cuba-constitution','Cuba: 2019 Constitution, official doctrine in translation','https://www.constituteproject.org/constitution/Cuba_2019','Constitute Project');
s('cuba-families','Ley 156/2022: Código de las Familias, reproduced legal text','https://www.cibercuba.com/s/gacetaoficial/ley-156-de-2022-de-asamblea-nacional-del-poder-popular','CiberCuba');
s('cuba-fh','Cuba: Freedom in the World 2025, institutional cross-check','https://freedomhouse.org/country/cuba/freedom-world/2025','Freedom House');
s('faith-solidarity','Vår Politik: social justice, international solidarity and environment','https://trosolidaritet.socialdemokraterna.se/trosolidaritet/var-politik','Social Democrats for Faith and Solidarity');
s('faith-history','Brotherhood movement becomes Social Democrats for Faith and Solidarity (2011)','https://www.mynewsdesk.com/se/trosolidaritet/pressreleases/broderskapsroerelsen-blev-socialdemokrater-foer-tro-och-solidaritet-652241','Social Democrats for Faith and Solidarity');
s('nordic-unions','The Nordic Model','https://nfs.net/en/what-we-do/the-nordic-region/the-nordic-model/','Council of Nordic Trade Unions');
s('nordic-rules','International Strategy: rules-based world order and the Nordic model','https://pub.norden.org/politiknord2023-718/the-rules-based-world-order-and-the-nordic-model.html','Nordic Council');
s('social-democratic-principles','Declaration of Principles (1989)','https://www.socialistinternational.org/about-us/declaration-of-principles/','Socialist International');
s('environment-sep','Environmental Ethics: different grounds for protection','https://plato.stanford.edu/entries/ethics-environmental/','Stanford Encyclopedia of Philosophy');
s('environment-iep','Environmental Ethics: wilderness, biodiversity and obligations','https://iep.utm.edu/envi-eth/','Internet Encyclopedia of Philosophy');
s('rio','Rio Declaration on Environment and Development (indexed primary excerpt)','https://www.un.org/esa/documents/ga/conf151/aconf15126-1.htm','United Nations');
s('mouffe','Chantal Mouffe interview: left populism','https://www.versobooks.com/blogs/news/3341-chantal-mouffe-we-urgently-need-to-promote-a-left-populism','Verso Books');
s('podemos','Reflexive technopopulism: Podemos and the search for a new left-wing hegemony (abstract)','https://www.cambridge.org/core/journals/european-political-science/article/abs/reflexive-technopopulism-podemos-and-the-search-for-a-new-leftwing-hegemony/E790104AE98F40AA8F2DBE1BC06A4F04','Cambridge University Press');
s('podemos-policy','Left populism in office: the policy record of Podemos (indexed research excerpt)','https://www.tandfonline.com/doi/full/10.1080/23745118.2025.2605209','Taylor & Francis');
s('postmodernism','Postmodernism: differences among Lyotard, Foucault and others','https://plato.stanford.edu/entries/postmodernism/','Stanford Encyclopedia of Philosophy');
s('lyotard','The Postmodern Condition (1979), first five chapters','https://www.marxists.org/reference/subject/philosophy/works/fr/lyotard.htm','Marxists Internet Archive');
s('foucault','Michel Foucault: historical production of truth and power','https://iep.utm.edu/foucault/','Internet Encyclopedia of Philosophy');
s('dewey-sep','Dewey’s Political Philosophy','https://plato.stanford.edu/entries/dewey-political/','Stanford Encyclopedia of Philosophy');
s('dewey-iep','John Dewey','https://iep.utm.edu/john-dewey/','Internet Encyclopedia of Philosophy');
s('dewey','Democracy and Education (1916)','https://www.gutenberg.org/files/852/852-h/852-h.htm','Project Gutenberg');
s('communitarianism','Communitarianism: constitutive communities and political limits','https://plato.stanford.edu/entries/communitarianism/','Stanford Encyclopedia of Philosophy');
s('responsive','Responsive Communitarian Platform (1991), reproduced document','https://www.republikanisme.nl/politiek/responsive-community-1991/','Republikanisme');
s('communitarian-study','Masao Kikuchi: American communitarianism, NRAS 41 (2019)','https://rci.nanzan-u.ac.jp/america/ja/journal/item/nras41_04_kikuchi_masao.pdf','Nanzan University');
s('monarchy-ucl','What is constitutional monarchy and what is its role in the UK?','https://www.ucl.ac.uk/social-historical-sciences/constitution-unit/constitution-unit-publications/constitution-unit-briefings/what-constitutional-monarchy-and-what-its-role-uk','University College London');
s('monarchy-ifg','The monarch, royal family and parliament','https://www.instituteforgovernment.org.uk/explainer/monarch-royal-family-and-parliament','Institute for Government');
s('monarchy-canada','Canadian Parliamentary System (indexed institutional excerpt)','https://www.ourcommons.ca/procedure/our-procedure/parliamentaryFramework/c_g_parliamentaryframework-e.html','House of Commons of Canada');
s('ppp','About Us: founding principles (indexed primary excerpt)','https://pppsindh.org/about-us/','Pakistan Peoples Party');
s('islamic-socialism-punjab','Ideological Orientation of Pakistan People’s Party: Evolution, Illusion and Reality','https://pu.edu.pk/images/journal/history/PDF-FILES/13_55_2_18.pdf','University of the Punjab');
s('islamic-socialism-sindh','Islamic Socialism and the Upsurge of Pakistan People’s Party','https://sujo.usindh.edu.pk/index.php/Grassroots/article/view/4268','University of Sindh');
s('qutb','Sayyid Qutb: sovereignty, economics and gender','https://iep.utm.edu/qutb/','Internet Encyclopedia of Philosophy');
s('qutb-brookings','Syed Qutb: John Locke of the Islamic World (counter-interpretation)','https://www.brookings.edu/articles/syed-qutb-john-locke-of-the-islamic-world/','Brookings Institution');
s('qutb-sage','Qutb, Sayyid: Encyclopedia of Global Religion (indexed scholarly excerpt)','https://sk.sagepub.com/ency/edvol/embed/globalreligion/chpt/qutb-sayyid-1906-1966','SAGE Reference');
s('kant','Kant’s Social and Political Philosophy','https://plato.stanford.edu/entries/kant-social-political/','Stanford Encyclopedia of Philosophy');
s('kant-peace','Perpetual Peace (1795)','https://constitution.org/2-Authors/kant/perpeace.htm','Constitution Society');
s('schlegel','Schlegel: critique of Kantian republicanism (1796)','https://germanhistorydocs.org/en/the-holy-roman-empire-1648-1815/friedrich-schlegel-essay-on-the-concept-of-republicanism-occasioned-by-the-kantian-tract-perpetual-peace-1796','German Historical Institute');
s('meritocracy','Meritocracy: governance, distribution and objections','https://plato.stanford.edu/entries/meritocracy/','Stanford Encyclopedia of Philosophy');
s('merit-young','Meredith: Michael Young and Meritocracy in Postwar Britain (indexed research excerpt)','https://onlinelibrary.wiley.com/doi/10.1111/1467-923X.12837','Wiley / Political Quarterly');
s('third-way','Europe: The Third Way / Die Neue Mitte','https://sites.ualberta.ca/~yreshef/orga417/blair/thirdway.html','University of Alberta','1999-06-08');
s('third-way-clinton','Third Way: progressive governance roundtable','https://clintonwhitehouse6.archives.gov/1999/04/1999-04-25-remarks-by-the-president-and-nato-leaders-in-dlc-roundtable.html','United States National Archives','1999-04-25');
s('third-way-critique','Mouzelis: Reflexive Modernization and the Third Way (indexed abstract)','https://journals.sagepub.com/doi/10.1111/1467-954X.00340','SAGE / Sociological Review');
s('authoritarian-law','Authoritarian Legality and State Capitalism in China','https://www.annualreviews.org/content/journals/10.1146/annurev-lawsocsci-111622-063635','Annual Reviews');
s('authoritarian-model','The Singapore model and China’s Neo-Authoritarian Dream (abstract)','https://www.cambridge.org/core/journals/china-quarterly/article/introduction-the-singapore-model-and-chinas-neoauthoritarian-dream/2ED7A22E42E1D9E2CA3A116047C8D58D','Cambridge University Press');
s('lee','Lee Kuan Yew: speech on development and Asian political values','https://www.nas.gov.sg/archivesonline/data/pdfdoc/lky19921120.pdf','National Archives of Singapore','1992-11-20');
s('frc','Family Research Council: FAQs and public policy mission','https://www.frc.org/faqs','Family Research Council');
s('baptist','Baptist Faith and Message 2000: family, religious liberty and social order','https://bfm.sbc.net/bfm2000/','Southern Baptist Convention');
s('christian-pew','Christianity’s place in politics and Christian nationalism','https://www.pewresearch.org/religion/2024/03/15/christianitys-place-in-politics-and-christian-nationalism/','Pew Research Center','2024-03-15');
s('herder','Johann Gottfried von Herder: language, cultural diversity and political thought','https://plato.stanford.edu/entries/herder/','Stanford Encyclopedia of Philosophy');
s('herder-primary','Herder: Materials for the Philosophy of the History of Mankind (1784)','https://sourcebooks.web.fordham.edu/mod/1784herder-mankind.asp','Fordham University');
s('herder-debate','Was Herder a Nationalist? (research abstract)','https://www.cambridge.org/core/journals/review-of-politics/article/abs/was-herder-a-nationalist/D301A3DBC9DAA9C9CCE1DF81060C957D','Cambridge University Press');
s('reform','Our Contract with You (2024), indexed primary excerpts','https://reformuk.org.uk/wp-content/uploads/2024/06/Reform_UK_Our_Contract_with_You.pdf','Reform UK');
s('reform-check','Reform UK 2024 election contract: fact checked','https://fullfact.org/election-2024/reformuk-manifesto/','Full Fact');
s('reform-research','The Grammar of Race: British Fascism, Racial Nationalism and the Rise of Reform UK (indexed research excerpt)','https://onlinelibrary.wiley.com/doi/full/10.1111/1467-923x.70110','Wiley / Political Quarterly');
s('militarism','Eastwood: Rethinking militarism as ideology (abstract)','https://journals.sagepub.com/doi/10.1177/0967010617730949','SAGE / Security Dialogue');
s('militarism-cambridge','War and Militarism (chapter abstract)','https://www.cambridge.org/core/books/abs/cambridge-handbook-of-social-problems/war-and-militarism/40BF435723D73F20814CC8AAAAC8363C','Cambridge University Press');
s('militarism-chicago','Cultures of Militarism: anthropology introduction','https://www.journals.uchicago.edu/doi/full/10.1086/700648','University of Chicago Press');
s('thiel-cato','Peter Thiel: The Education of a Libertarian','https://www.cato-unbound.org/2009/04/13/peter-thiel/education-libertarian/','Cato Unbound','2009-04-13');
s('thiel-faith','Faith & Technology: Q&A with Peter Thiel','https://www.americamagazine.org/all-things/2014/10/01/faith-technology-qa-peter-thiel/','America Magazine','2014-10-01');
s('thiel-hoover','Apocalypse Now? Peter Thiel on Ancient Prophecies and Modern Tech, interview transcript','https://plus.hoover.org/plus/research/apocalypse-now-peter-thiel-ancient-prophecies-and-modern-tech','Hoover Institution');
fs.writeFileSync(new URL('sources.json',import.meta.url),JSON.stringify(sources,null,2)+'\n');
