import fs from 'node:fs';import {validateAudit,similarity} from '../../../frontend/src/profiles/audit.ts';import {latest,bankHash,root} from '../../../frontend/scripts/profiles.ts';
const dir='profile-audit/reports/personality-expansion20-2026-10-05';const ids=JSON.parse(fs.readFileSync(dir+'/subjects.json'));const images=JSON.parse(fs.readFileSync(dir+'/images.json'));const fixes=JSON.parse(fs.readFileSync(dir+'/review-corrections.json'));
const reviewed=[];for(const id of ids){const p=`profile-audit/drafts/personality/${id}.json`;const d=JSON.parse(fs.readFileSync(p));d.metadata.image=images[id];d.metadata.image.alt='Portrait of '+d.metadata.name;if(d.metadata.image.creator==='Unknown author Unknown author')d.metadata.image.creator='Unknown photographer or artist, as recorded on Commons';
 d.review={reviewer:'Codex (GPT-6), distinct same-agent evidence and wording review; no independent human review',reviewedAt:'2026-10-05',notes:'Reviewed all 240 current-bank formulations separately from the initial assessment, including the numeric agreement choice, modern analogies, source scope, counter-evidence and image attribution. All 240 answers are explicitly educated assumptions, not verified personal questionnaire responses. Contemporary biological comparisons and historical translations have particularly weak evidence. Literal wording corrections distinguish mixed ownership, public hospitals, state constitutions, ordinary policing, voluntary federation and a coercive state. Historical suffrage exclusions, Bakunin’s discriminatory primary text and scoped rather than later positions were reviewed. Detailed question IDs, evidence limits and similarity decisions are recorded in profile-audit/reports/personality-expansion20-2026-10-05/'+id+'-review.md. No answers were changed to target scores or reduce similarity.',similarity:[]};
 const r=validateAudit(d,bankHash);if(r.errors.length)throw Error(id+' '+r.errors.join(';'));reviewed.push({d,p,profile:r.profile,warnings:r.warnings});}
const old=latest(root).filter(x=>x.audit.catalogue==='personality').map(x=>({d:x.audit,profile:validateAudit(x.audit,bankHash).profile}));const pairs=[];
for(const entry of reviewed){for(const peer of [...new Map([...old,...reviewed].map(p=>[p.d.id+':'+p.d.revision,p])).values()]){if(peer.d.id===entry.d.id||!peer.profile)continue;const n=similarity(entry.profile.scores,peer.profile.scores);if(n<95)continue;
 const differences=entry.profile.scores.map((x,i)=>({axis:x.axisId,difference:x.leftPercent-peer.profile.scores[i].leftPercent})).filter(x=>x.difference!==0).sort((a,b)=>Math.abs(b.difference)-Math.abs(a.difference)).slice(0,3);
 const reasons=differences.map(x=>{const a=entry.d.axes.find(y=>y.axisId===x.axis),b=peer.d.axes.find(y=>y.axisId===x.axis);return x.axis+': '+entry.d.metadata.name+' — '+a.brief+' '+peer.d.metadata.name+' — '+b.brief;}).join(' ');
 const reason=`Retain distinct named individuals and periods (${entry.d.metadata.period}; ${peer.d.metadata.period}). Diagnostic equal-axis resemblance (${n.toFixed(2)}%) does not establish interchangeable evidence or a user match. Review of the largest calculated differences: ${reasons} Both records include substantial inferred modern and behavioural-causation responses, which can compress differences. No answer adjusted to separate these neighbours.`;
 entry.d.review.similarity.push({id:peer.d.id,revision:peer.d.revision,reason});pairs.push({id:entry.d.id,neighbour:peer.d.id,revision:peer.d.revision,similarity:n,reason});}
 fs.writeFileSync(entry.p,JSON.stringify(entry.d,null,2)+'\n');
 const d=entry.d;const all=d.axes.flatMap(a=>a.answers);let report=`# ${d.metadata.name}: separate evidence review\n\nReviewer: ${d.review.reviewer}\nDate: ${d.review.reviewedAt}\nScope: ${d.metadata.period}. ${d.metadata.scope}\n\n240/240 numeric answers; revision ${d.revision}. All 240 responses are inferred educated assumptions. They estimate a most-likely personal response from public context and must not be represented as documented answers. No unknown or null response remains; Neutral expresses a mixed proposition rather than missing evidence.\n\n## Evidence and wording review\n\n`;
 for(const a of d.axes)report+=`### ${a.axisId}\n\nEvidence: ${a.brief}\n\nCounter-evidence/qualification: ${a.counterEvidence}\n\nAnswers were reviewed in bank order: ${a.answers.map(x=>x.questionId+'='+x.value).join(', ')}.\n\n`;
 report+='## Corrections and limitations\n\n'+fixes.filter(x=>x.id===d.id).map(x=>`- ${x.axis}, question ${x.question}: ${x.reason}`).join('\n')+'\n\nFor every subject, public commitments, coalition implementation and modern analogies were distinguished. Sources were checked against at least three publisher organisations, although Wikipedia synthesises some of the same underlying material and is not independent confirmation of every claim. Some accessible search excerpts and official biographical pages are only contextual, and a third publisher is not independent verification of all answers. Every Culture vs Nature comparison and modern enhancement, AI or admissions mechanism should receive particular human scrutiny. A social reform record is contextual evidence, not a biological doctrine.\n\n## Similarity review\n\n'+(d.review.similarity.map(x=>`- ${x.id}, revision ${x.revision}: ${x.reason}`).join('\n')||'No peer at or above the 95% diagnostic threshold.')+'\n\n## Educated-assumption question IDs\n\n'+all.map(x=>'- '+x.questionId).join('\n')+'\n\n## Source record\n\n'+d.sources.map(s=>`- ${s.id}: [${s.title}](${s.url}); ${s.publisher}; publication ${s.date}; accessed ${s.accessed}.`).join('\n')+'\n\n## Image\n\n'+JSON.stringify(d.metadata.image,null,2)+'\n';
 fs.writeFileSync(dir+'/'+d.id+'-review.md',report);}
fs.writeFileSync(dir+'/similarity-review.json',JSON.stringify(pairs,null,2));console.log('Prepared',reviewed.length,'reviews;',pairs.length,'directed similarity decisions.');
const creditPath='frontend/src/profiles/personalityImageCredits.ts';let credits=fs.readFileSync(creditPath,'utf8');const entries=reviewed.filter(x=>!credits.includes(x.d.metadata.image.sourceUrl)).map(x=>({name:x.d.metadata.name+' (revision 1)',...Object.fromEntries(['sourceUrl','creator','license','licenseUrl'].map(k=>[k,x.d.metadata.image[k]])),modifications:'Resized to at most 800 pixels and JPEG compressed; no additional crop. Earlier cropping or restoration is recorded on the Commons source page.'}));if(entries.length)credits=credits.replace(/\n\] as const;/,',\n'+entries.map(x=>JSON.stringify(x,null,2)).join(',\n')+'\n] as const;');fs.writeFileSync(creditPath,credits);
