import {save,source as S} from './spec-helper.mjs';
save('george-w-bush','George W. Bush','Presidency, 2001–2009','2009-01-20','1946–present','43rd president of the United States','Politician','US president whose record combines private enterprise, social conservatism and expansive national-security powers.',[
['4040334031030100','Competitive presidential elections, congressional legislation and constitutional judicial review remained his claimed framework.','Signing statements and executive-power claims strained checks; habeas-corpus rulings contradicted detention policy. No military replacement of civilian elections.','1,2'],
['1313323311332114','PATRIOT surveillance, preventive national-security detention and interrogation accompanied formal free-speech and warrant protections.','Court-authorised surveillance is narrower than warrantless collection; court review of terrorism detention was contested. Drug liberalisation was not his policy.','1,2'],
['3133333133333133','Bush emphasised English, citizenship and a shared American identity while recognising religious and ethnic inclusion.','Opposition to anti-Muslim prejudice and immigration reform qualify assimilation; shared national norms do not erase minority identity.','1,3'],
['2313313323213132','Proposed guest-worker routes and earned legal status together with strengthened border control, family immigration and deportation enforcement.','A pathway conditional on work, fines and checks differs from allowing every unauthorised migrant to remain; no blanket cultural exclusion.','1,2'],
['4144131110414131','Afghanistan and the preventive Iraq invasion, military superiority and expeditionary operations anchor a willingness to use force.','Volunteer forces, multilateral diplomacy and eventual negotiation qualify this; autonomous targeting without human approval is only a cautious analogy.','1'],
['4143414131434343','National sovereignty and rejection of some external constraints coexisted with NATO, trade agreements and international aid.','International cooperation is not delegation of final authority; binding external criminal jurisdiction and shared currency were not embraced.','1'],
['4131313121313131','Ownership society and private providers were preferred, with public education, infrastructure and Medicare financing retained.','2008 emergency bank rescues and conservatorships were exceptional; nationalisation was not an ordinary competitive-industry model.','1,2,3'],
['1313131313311333','Negotiated free-trade agreements and generally defended open international commerce.','Steel tariffs and agricultural subsidies show sectoral protection; strategic security exceptions remain plausible.','1,2'],
['4141414133123131','Private production and prices were normally preferred, alongside targeted incentives and a statutory minimum wage.','TARP crisis intervention, farm subsidies and housing policy limit laissez-faire; independent monetary institutions were retained.','1,2'],
['1313131313133113','Tax cuts and an ownership agenda prioritised retaining income; expanded targeted health assistance and rebates provided a safety net.','Medicare Part D and the earned-income tax credit do not imply broad wealth equalisation; inheritance and high-earner tax cuts point the other way.','1,2,3'],
['3131333123133331','Faith-based initiatives, public religious language and assistance to religious charities gave faith a public role.','He described government as unable to inspire faith and did not endorse clerical approval of civil law; personal Christianity alone proves no theocracy.','1,3'],
['1313031313131313','Defended traditional marriage and abortion restrictions, family values and parental influence.','Women in senior office and plural religious society qualify inherited gender roles; support for adoption and sexual-identity language are estimates.','1,2'],
['3133331321331333','Promoted technological and energy development and commercial innovation while restricting embryonic-stem-cell funding.','Biomedical moral limits and public-health safety review qualify rapid adoption; support for space and energy research is not evidence on brain implants.','1,2'],
['3301333133131334','Federalism and state authority were affirmed while national security, education standards and emergencies drew federal direction.','No Child Left Behind and federal civil-rights constraints mean decentralisation was selective; state secession was not accepted.','1,2'],
['3131313131313131','Education reform and opportunity rhetoric locate many outcomes in schools, family and social experience.','The record does not settle comparative genetic causation of temperament, stress, attention or attraction; modest estimates are deliberately uncertain. Racial heredity claims are not inferred from party identity.','1,2']
],[S('George W. Bush: domestic affairs','https://millercenter.org/president/gwbush/domestic-affairs','Miller Center'),S('President discusses compassionate conservatism','https://georgewbush-whitehouse.archives.gov/news/releases/2002/04/20020430-5.html','US National Archives / White House','2002-04-30')]);
save('hillary-clinton','Hillary Clinton','Secretary of state and presidential candidacy, 2009–2016','2016-11-08','1947–present','Former US secretary of state and 2016 presidential candidate','Politician','US political leader assessed through her foreign-policy record and 2016 presidential programme.',[
['4040444032040300','Competitive elections, universal adult suffrage, congressional accountability and independent courts underpin her institutional programme.','Representative constitutional politics does not establish endorsement of universal binding referendums or recall votes; these are qualified estimates.','1,2'],
['2314313313324311','Supported civil rights and judicial safeguards alongside intelligence surveillance and counterterrorism powers.','Gun restrictions, security interventions and the prosecution of classified leaks qualify a simple liberty label; exact modern policing cases require inference.','1,2'],
['1434342134331341','Celebrated a diverse American national community with minority inclusion and anti-discrimination measures.','Shared civic integration and national institutions remained important; distinct cultural expectations were not granted unlimited priority over common rights.','1,2'],
['1314432123124133','Favoured immigration reform, family unity, refugee protection and a pathway to citizenship for many undocumented residents.','Screening and lawful-entry enforcement remained; automatic permanent settlement or welfare eligibility for all noncitizens is broader than her programme.','1,2'],
['3334131110413233','Alliances, military capability and selective interventions including Libya accompanied diplomacy, arms-control negotiations and development.','Her 2016 speech defended the Iran agreement and cautioned against unnecessary war; force only after an attack and avoiding war at all costs are both too restrictive.','1,3'],
['3234323333433333','Strong alliances, international climate cooperation and trade rules were endorsed within continued US sovereignty.','Allied cooperation does not establish an international political federation, shared monetary authority or unconditional outside legal supremacy.','1,3'],
['3331333233212233','Regulated private enterprise, public services and infrastructure investment shaped her economic programme.','Public financing and a public insurance option do not mean most hospitals or competitive firms should be state-owned; national security retained mixed ownership.','1,2'],
['2333233323312333','Supported international commerce and opposed a trade war while seeking stronger labour protections and rejecting the proposed TPP in 2016.','Earlier promotion of trade negotiations and later opposition require a mixed period-specific estimate, rather than uniformly free-trade or protectionist answers.','1,3'],
['4133313333133131','Private production and market prices were normal, alongside minimum wages, industrial investment and financial regulation.','Infrastructure and clean-energy incentives steer development without compulsory economy-wide production targets; private competing currencies lack direct endorsement.','1,2'],
['4131333131414131','Proposed higher taxes on high earners, stronger income support, paid leave and help for low-paid workers.','A regulated market and targeted fiscal programme differed from equalising all incomes; compensated land redistribution is speculative and only weakly supported.','1,2'],
['4141314131314331','Civil government, plural religion and policy independent of clerical veto were supported.','Methodist belief, religious holidays and religious charitable exemptions were retained; these do not establish religious legislation as a foundation of the state.','1,2'],
['4141414131314132','Supported same-sex marriage by 2013, reproductive rights, women’s opportunities and LGBT equality in the scoped years.','Earlier marriage positions precede or sit early in this period; parental involvement and gradual institutional change qualify unbounded rejection of tradition.','1,2'],
['3133311323311333','Innovation, clean energy and infrastructure investment were priorities alongside environmental and biomedical safeguards.','Scientific investment alone cannot settle enhancement, cultivated meat or autonomous diagnosis; these are cautious question-specific analogies.','1,2,3'],
['3301333133132314','Federal constitutional states retained powers, with national civil-rights, education and healthcare goals.','No right of unilateral secession or unrestricted local obstruction follows; the national health programme was compatible with state delivery.','1,2'],
['4141314131314131','Educational access, discrimination and social barriers were central explanations for unequal opportunity.','This is contextual evidence for social influence, not a quoted claim that biology has no role in stress, temperament or cognition.','1,2']
],[S('Remarks at Ohio State University, Columbus','https://www.presidency.ucsb.edu/documents/remarks-ohio-state-university-columbus','American Presidency Project','2016-10-10'),S('Remarks in San Diego, California','https://www.presidency.ucsb.edu/documents/remarks-san-diego-california-0','American Presidency Project','2016-06-02'),S('Speech attacking Trump’s economic policies — contextual report','https://time.com/4378959/hillary-clinton-raleigh-speech-economy/','TIME','2016-06-22')]);
save('rishi-sunak','Rishi Sunak','Premiership, 2022–2024','2024-07-05','1980–present','Former prime minister of the United Kingdom','Politician','British prime minister assessed through the 2022–2024 government and 2024 election programme.',[
['4040444031030100','Parliamentary elections and constitutional executive accountability were retained, including conceding the 2024 election.','The Rwanda legislation overrode a court’s factual assessment through parliamentary statute, not an unlimited personal executive veto. Binding recall and referendums are qualified.','1,2'],
['1313323311334212','Expanded protest restrictions, policing and border enforcement alongside civil criticism and judicial safeguards.','Security emphasis does not abolish warrants or every court review; moral censorship and bulk movement records are modern estimates.','1'],
['3133333133333333','Shared British civic identity, English integration and common institutions were emphasised alongside recognition of minority communities.','His Hindu identity and participation in plural celebrations do not imply clerical government or rejection of a shared national culture.','1,2'],
['4133104431233121','Reducing net migration, tighter dependent visas and the Rwanda asylum scheme prioritised control and eligibility.','Legal family and skilled routes and some refugee schemes remained; broad permanent refugee admission regardless of compatibility is qualified downward.','1'],
['3334131110413232','Supported Ukraine militarily, NATO, defence spending and deterrence, with professional armed forces.','2024 national-service proposal included civilian options; neither universal male military conscription nor autonomous lethal AI was established.','1'],
['4133313131334333','Post-Brexit national policy, border and monetary control coexisted with NATO, trade agreements and treaty cooperation.','Continued European human-rights commitments qualify blanket external-jurisdiction rejection; voluntary alliances differ from political federation.','1'],
['4131313121213131','Private enterprise and private service provision were favoured while the NHS, BBC and public infrastructure were retained.','No wholesale privatisation of hospitals or rail infrastructure was his programme; emergency/public banks do not imply a general state commercial sector.','1,3'],
['1313131313311333','Post-Brexit trade agreements and open investment were promoted.','Food security, strategic ownership screening and subsidy responses create exceptions; imports were not to be protected across the whole economy.','1,3'],
['4141314133133131','Market allocation and business investment were normal, with minimum-wage rules, targeted support and industrial priorities.','The energy crisis and strategic sectors prompted subsidy and intervention; an independent central bank remained part of the framework.','1,3'],
['1313331313133133','Tax reductions, welfare conditionality and targeting benefits were emphasised.','Progressive income-tax rates and the safety net remained; not every wealth or inheritance tax was abolished and tax cuts were fiscally constrained.','1,3'],
['4131314131313331','Civil policy without religious approval, plural faith recognition and state courts were supported.','Established church, religious holidays, faith schools and bishops in the Lords were not wholly removed; personal Hindu belief is not the axis itself.','1,2'],
['2323331313133333','Traditional family, sex-based institutional safeguards and parental influence received emphasis.','Same-sex marriage was legal and accepted, women’s careers were normal and tradition was not an all-purpose veto on reform.','1'],
['3133311321331333','AI investment, infrastructure and technological solutions were promoted alongside an AI safety summit and existing clinical safeguards.','Net-zero delays and energy development do not establish support for unchecked brain implants or embryo enhancement.','1'],
['2303331313331334','Devolved administrations and local delivery persisted within parliamentary sovereignty and a unified national framework.','Opposed a further Scottish independence referendum; devolution does not mean regional constitutions or councils can alter powers unilaterally.','1'],
['3131313131313131','Schooling, skills and opportunity were emphasised as ways to improve outcomes.','Policy emphasis is weak evidence on comparative biological causation; no racial IQ or violence explanation is attributed without a direct statement.','1']
],[S('Rishi Sunak — former prime minister biography and term','https://www.gov.uk/government/people/rishi-sunak','UK Government'),S('General election 2024 manifesto analysis presentations','https://ifs.org.uk/publications/general-election-2024-manifesto-analysis-presentations','Institute for Fiscal Studies')]);
save('keir-starmer','Keir Starmer','Labour leadership and election programme, 2020–2024','2024-07-05','1962–present','UK Labour leader and incoming prime minister at the cutoff','Politician','British Labour leader assessed through the programme preceding his July 2024 premiership.',[
['4040444031030100','Parliamentary elections, universal suffrage, legal accountability and independent courts formed the reform programme.','Labour discipline and limited referendums differ from excluding other parties; binding nationwide recalls were not a central programme.','1,2'],
['2313323311334311','Civil liberties and rule of law accompanied stronger policing, security and public-order commitments.','Former prosecution work does not automatically settle drug use, moral censorship or surveillance retention; these are modest contextual estimates.','1,2'],
['2334332134333332','Equal citizenship, minority inclusion and common British civic institutions were combined.','Patriotic rhetoric and integration do not negate accommodation; distinct traditions were not granted unlimited priority over common obligations.','1,2'],
['3333313333233122','Promised lower net migration, stronger border security and skills policy while retaining lawful work, family and asylum routes.','Rejected the Rwanda scheme; compassion and legal asylum obligations do not mean open entry or automatic permission for all unauthorised arrivals.','1,2'],
['3334131110413232','NATO, nuclear deterrence, defence spending and military support for Ukraine were endorsed.','Diplomacy remained important; no general male conscription or unrestricted autonomous lethal AI commitment is established.','1,2'],
['3234333333433333','International cooperation and alliances alongside refusal to rejoin the EU, single market or customs union defined the 2024 programme.','Shared currency and political federation were not proposed; accepting legal treaties is narrower than every binding institutional decision.','1,2'],
['3333332333212234','Public rail services and a publicly owned clean-energy company were promised within a private-business economy and public NHS.','Passenger rail services are distinct from infrastructure; water nationalisation and state ownership of most firms were not programme commitments.','1,2,3'],
['1313332313312333','Closer trade relations, negotiated standards and business investment were promoted without general tariff protection.','Security, procurement and agricultural exceptions remained; avoiding a customs union does not itself imply protectionist tariffs.','1,2'],
['4133313333133131','Business investment, market production, a strengthened minimum wage and mission-led industrial strategy were combined.','Selective public coordination and planning reform differ from compulsory national production quotas or government wage schedules for all jobs.','1,2'],
['3131333131314132','Strengthening workers’ incomes and public services accompanied targeted tax changes and fiscal restraint.','Declined broad income-tax increases and major wealth-tax commitments; redistribution estimates should be modest rather than inferred from Labour identity alone.','1,2,3'],
['4131314131313331','Civil law and plural faith, without clerical policy approval, were supported.','Established institutions, religious holidays and faith schools were not fully abolished; personal atheism is not sufficient evidence for all secular answers.','1,2'],
['3131413131314132','LGBT equality, women’s opportunities and changing social recognition accompanied caution on contested institutional details.','Some sex-based safeguards and gradual reform were retained; this is the 2020–2024 record, not any later policy.','1,2'],
['3133311323311333','Clean power, infrastructure, research and planning reform were development priorities with environmental safeguards.','Promise of innovation does not settle speculative biomedical enhancement or unsupervised clinical AI; these answers are qualified.','1,2'],
['2303331313332334','Promised devolution to mayors and regions while maintaining UK unity and national service standards.','Opposed a further Scottish referendum in the programme; local power is limited by national law rather than unrestricted fiscal or constitutional independence.','1,2'],
['3131313131314131','Opportunity, school access and discrimination were framed as social barriers capable of change.','No precise inherited-versus-social model of empathy, stress or IQ is established; weak estimates reflect programme context and uncertainty.','1,2']
],[S('Change: Labour manifesto 2024','https://labour.org.uk/wp-content/uploads/2024/06/Change-Labour-manifesto-2024-screen-reader.pdf','Labour Party','2024-06-13'),S('General election 2024 manifesto analysis presentations','https://ifs.org.uk/publications/general-election-2024-manifesto-analysis-presentations','Institute for Fiscal Studies')]);
