import {save,source as S} from './spec-helper.mjs';
save('jacinda-ardern','Jacinda Ardern','Premiership, 2017–2023','2023-01-25','1980–present','Former prime minister of New Zealand','Politician','New Zealand prime minister assessed through her government’s social, economic and foreign-policy record.',[
['4040444031030300','Competitive parliamentary elections, expanded voting participation and constitutional accountability were central; she voluntarily left office.','Referendums and recalls are not interchangeable with parliamentary government; no evidence supports a personal lawmaking veto over parliament.','1,2'],
['3314323311334301','Supported civil rights and criticism while imposing COVID restrictions, public-health measures and gun controls.','The cannabis referendum’s failure and targeted counterterrorism policy do not establish complete drug freedom or unlimited detention without review.','1'],
['1434342134331341','Māori recognition, multicultural inclusion and Muslim community solidarity followed the Christchurch attacks.','Shared citizenship and civic rights still matter; distinct customs need not trump common laws, and face-covering exceptions remain an uncertain analogy.','1'],
['3334433323124133','Promoted more refugee intake while initially proposing lower ordinary migration to address infrastructure and skills pressures.','COVID border closures were emergency health measures, not evidence of permanent ethnic exclusion; ordinary skilled and family admission remained conditional.','1'],
['1433133110413133','Multilateral diplomacy, a nuclear-free stance and avoiding unnecessary conflict accompanied defence and military aid for Ukraine.','Cooperation with Western security partners in 2022 qualifies pacifism; refusal of all force even for an attacked ally is not implied.','1,3'],
['3234333333433333','UN cooperation, climate action and negotiated trade agreements were priorities, with national borders and currency retained.','The Christchurch Call was non-binding; consensus initiatives do not by themselves support unconditional supranational rule.','1,3'],
['3433332333212234','Public healthcare, housing and infrastructure coexisted with private businesses and providers.','Self-description as socialist is not proof of nationalising most businesses; the actual programme retained a market economy and mixed delivery.','1'],
['1313131313311333','Negotiated UK and EU trade deals and upgraded trade with China, preferring outward economic engagement.','Strategic investment screening and product standards can still apply; free-trade diplomacy is not a promise to remove all protections unilaterally.','1,3'],
['4133313333133131','Private production and market prices combined with minimum-wage rises, public investment and targeted development support.','COVID coordination was exceptional; no ordinary economy-wide compulsory output quotas or government wage schedules were established.','1'],
['3131333131314131','Child poverty, family support, minimum incomes and wage assistance were major priorities.','Rejected a proposed capital-gains tax and retained targeted benefits; this warrants moderate rather than maximal wealth-tax estimates.','1'],
['4141314131314331','Civil government and plural faith without religious veto were maintained.','Public remembrance and culturally religious holidays remained; agnosticism does not prove rejection of every ceremonial religious practice.','1'],
['4141414131314131','Same-sex marriage, abortion-law reform and women’s participation supported changes in social norms.','Some family traditions and gradual reform remained compatible with equality; exact identity-language and enhancement questions require contextual inference.','1'],
['3133311323311333','Climate measures, public science and infrastructure were combined with environmental review and health safeguards.','Climate leadership is not a stance on gene enhancement or implants; uncertain long-term biomedical risks are estimated cautiously.','1'],
['2303331313333334','Local government and Māori institutions were recognised, alongside nationwide health and water reform.','New Zealand remained a unitary state; recognition of Māori communities differs from unlimited regional secession or independent regional constitutions.','1'],
['4141314131314131','Child poverty, education and social barriers were framed as changeable conditions shaping people’s opportunities.','Policy concern is contextual evidence, not a precise comparative theory of genetics, stress or empathy; no racial biological explanation is attributed.','1']
],[S('Prime minister Jacinda Ardern announces resignation','https://www.beehive.govt.nz/release/prime-minister-jacinda-ardern-announces-resignation','New Zealand Government','2023-01-19'),S('Geoffrey Miller: Jacinda Ardern’s foreign-policy legacy','https://www.rnz.co.nz/news/political/482782/geoffrey-miller-jacinda-ardern-s-outsized-new-zealand-foreign-policy-legacy','RNZ / Democracy Project','2023-01-20')]);
save('justin-trudeau','Justin Trudeau','Premiership, 2015–2025','2025-03-14','1971–present','Former prime minister of Canada','Politician','Canadian prime minister assessed through federal social policy, trade, multiculturalism and late-term migration changes.',[
['4040444031030100','Competitive parliamentary elections, universal suffrage and judicial checks were retained.','Ethics controversies and emergency powers require scrutiny but do not establish support for banning elections; referendum and recall support is only qualified.','1'],
['4314323311334301','Legalised recreational cannabis, protected civil equality and retained constitutional liberties with policing safeguards.','The 2022 Emergencies Act, COVID mandates and firearms restrictions qualify expansive liberty; emergency detention cannot be assumed to lack court review.','1'],
['1434342134331341','Official multiculturalism, French and English language recognition and Indigenous reconciliation were central.','Shared constitutional rights and integration remained; bilingual national languages are not identical to unlimited foreign-language spending or all cultural exceptions.','1'],
['3334433323124133','Expanded immigration and Syrian refugee resettlement, then reduced targets in 2024 amid housing and service pressures.','The later reduction must be included; employer demand did not override every capacity limit, and illegal arrival did not automatically establish permanent permission.','1,2,3'],
['2433133110413133','Supported NATO, military assistance to Ukraine and diplomatic international action.','Reduced appetite for military intervention does not imply abandoning attacked allies or forbidding all preventive action.','1'],
['3234333333433333','Trade agreements, Paris climate cooperation and international institutions were supported within continued Canadian sovereignty.','National currency, border authority and domestic constitutional institutions persisted; cooperation differs from international federation.','1'],
['3433332333222234','Public healthcare financing, public broadcasting and infrastructure coexisted with private firms and many private healthcare providers.','Purchase of the Trans Mountain pipeline was a specific strategic intervention; not an argument for national ownership of all resources or businesses.','1'],
['1313131313311333','CUSMA and CPTPP supported trade and investment openness.','Agricultural supply management and strategic ownership review were substantial exceptions; trade deals are not unconditional unilateral liberalisation.','1'],
['4133313333133131','Market production, a federal minimum wage, industrial support and climate pricing shaped economic policy.','Subsidies and public projects steered investment without normal compulsory output quotas; emergency pandemic programmes are not the ordinary planning model.','1'],
['3131333131314131','Canada Child Benefit, expanded pensions, pandemic income support and aid to lower-income households increased transfers.','Targeted benefits and mixed taxation did not seek complete equalisation; speculative wealth and land redistribution are weak, qualified analogies.','1'],
['4141314131314331','Civil legislation and religious pluralism were retained without clerical approval requirements.','Catholic personal belief, religious holidays and charitable exemptions do not by themselves establish a religious state.','1'],
['4141414131314131','Abortion rights, conversion-therapy prohibition, gender equality and LGBT recognition supported changing social norms.','Some inherited customs and family institutions remained; exact educational and language trade-offs are estimates.','1'],
['3133311323311333','Clean technology, research and infrastructure investment coexisted with environmental assessments.','Pipeline support qualifies preservation; speculative enhancement and unsupervised clinical AI are not established by general innovation policy.','1'],
['3301333133133334','Constitutional provinces and Indigenous institutions retained powers alongside national programmes and federal emergency authority.','National standards and taxation constrained provincial autonomy; support for a clear constitutional separation process is not unconditional secession on any majority referendum.','1'],
['4141314131314131','Education, reconciliation, discrimination and economic opportunity treated many inequalities as socially shaped.','The sources do not settle biology-versus-experience rankings for specific psychological traits; contextual estimates remain uncertain.','1']
],[S('Government of Canada reduces immigration','https://www.canada.ca/en/immigration-refugees-citizenship/news/2024/10/government-of-canada-reduces-immigration.html','Government of Canada','2024-10-24'),S('Canada reduces immigration targets amid capacity concerns — report','https://apnews.com/article/dabd4a6248929285f90a5e95aeb06763','Associated Press','2024-10-24')]);
save('indira-gandhi','Indira Gandhi','Premierships, 1966–1977 and 1980–1984','1984-10-31','1917–1984','Former prime minister of India','Politician','Indian prime minister whose elected governments combined state-led development with centralisation and the 1975–1977 Emergency.',[
['3233223131133121','Won elections and returned after defeat, but the Emergency curtailed opposition, delayed elections and sought to limit judicial constraints.','She called and lost the 1977 election rather than holding permanent unelected rule; the period should not be reduced to its most coercive 21 months.','1,3'],
['1312324311332114','Emergency censorship, preventive detention and coercive population policy show willingness to subordinate liberties to state objectives.','Ordinary constitutional rights existed outside the Emergency; exact modern surveillance, drug and home-search questions are cautious analogies.','1,3'],
['3133333133333133','National unity and Indian civic identity coexisted with a multilingual, religiously diverse constitutional state.','Confrontations with Sikh separatism and the Punjab crisis must not be confused with rejection of every Sikh cultural practice.','1'],
['3333313333233132','Territorial security and managed movement coexisted with shelter for refugees from East Pakistan and regional humanitarian obligations.','Refugee admission during the Bangladesh crisis is not permanent open residence for all migrants; modern quotas and welfare eligibility lack exact evidence.','1'],
['3334131110413232','Bangladesh war, nuclear capability and strengthened forces supported strategic use of military power.','Non-alignment and diplomacy remained important; military development does not establish support for autonomous lethal weapons without human approval.','1'],
['4143314131334343','National sovereignty, non-alignment and independent strategic choices were prioritised alongside the UN and treaty cooperation.','The Soviet friendship treaty and international aid did not transfer final national policymaking, border or currency authority.','1'],
['1434341344341344','Bank and industrial nationalisation, state-led strategic sectors and public broadcasting expanded ownership.','Private industry and agriculture remained substantial; nationalisation was selective rather than abolition of all private business.','1'],
['4141414131414141','Import substitution, licensing and protection of domestic capacity shaped industrial development.','Some foreign capital and pragmatic liberalisation in the early 1980s qualify maximal restrictions; security-sensitive sectors were more protected.','1'],
['1314141414141314','Five-Year Plans, industrial licensing, state banking and administered priorities directed production and investment.','The mixed economy preserved private firms and some market pricing; early-1980s relaxation prevents treating every industry as a compulsory quota sector.','1'],
['4131333131413131','Anti-poverty programmes, progressive taxation and land-reform aims prioritised material support and reduced concentration.','Political patronage and uneven implementation mean rhetoric is not complete equalisation; compensation and administrative limits qualify land redistribution.','1'],
['4141314131313332','The constitution was explicitly secular and civil government did not require clerical approval.','Religious symbolism and separate personal-law systems remained; secular constitutional language is not rejection of religious family-law recognition.','1,3'],
['3132322322323133','Women’s political participation and reforms were combined with family-centred social norms.','A woman prime minister does not automatically imply modern same-sex marriage or identity policies; abortion legislation and opportunity reform qualify tradition.','1'],
['3133311321331333','Green Revolution agriculture, nuclear research and infrastructure reflected development and scientific modernisation.','Environmental protections and moral/clinical safeguards qualify rapid adoption; coercive sterilisation is not evidence for enhancement gene editing.','1'],
['1304331314331314','Central planning and intervention in state governments, including dismissal powers and national security responses, favoured central authority.','Constitutional states and regional languages survived; centralisation did not wholly abolish federal tax, police or regional institutions.','1'],
['3131313131313131','Education, poverty and social reform were treated as routes to human development; she described an egalitarian childhood.','This contextual record does not determine the comparative genetics of individual psychological traits; gender tradition is not automatically biological causation.','1']
],[S('Smt. Indira Gandhi — biography','https://www.pmindia.gov.in/en/former_pm/smt-indira-gandhi-2/','Prime Minister’s Office, India'),S('The Indian Emergency in historical perspective','https://academic.oup.com/book/56192/chapter/443483153','Oxford University Press')]);
