import fs from 'node:fs';const dir='profile-audit/reports/personality-expansion20-2026-10-05';const changes=[];
function fix(id,axis,question,value,reason){const p=`profile-audit/drafts/personality/${id}.json`,d=JSON.parse(fs.readFileSync(p)),a=d.axes.find(x=>x.axisId===axis),ans=a.answers[question-1];changes.push({id,axis,question,from:ans.value,to:value,reason});ans.value=value;const labels={'-2':'Strongly disagree','-1':'Disagree','0':'Neutral','1':'Agree','2':'Strongly agree'};const q=JSON.parse(fs.readFileSync('frontend/src/data/questions.v1.json')).questions.find(x=>x.id===ans.questionId);ans.rationale=`Educated assumption: ${labels[value]} is the most likely response by ${d.metadata.name} during ${d.metadata.period} to “${q.text}”. ${reason} Context: ${a.brief} Qualification: ${a.counterEvidence} The cited record does not establish a personal answer to this exact wording; this uncertain historical or policy analogy is not a documented position.`;fs.writeFileSync(p,JSON.stringify(d,null,2)+'\n');}
for(const id of ['george-washington','thomas-jefferson','theodore-roosevelt'])fix(id,'democracy-autocracy',3,-1,'The word every includes women and other adults excluded by the scoped electoral order. Republican elections alone cannot establish universal adult suffrage, and later positions outside the cutoff are excluded.');
for(const id of ['george-washington','thomas-jefferson','theodore-roosevelt','lyndon-b-johnson','jimmy-carter','george-w-bush','hillary-clinton']){fix(id,'central-local',3,-1,'Preservation of the federal union is more consistent with requiring broader constitutional authority than with an unrestricted right to leave on a regional majority vote. Stronger national programmes do not determine this answer by themselves.');fix(id,'central-local',5,2,'Constitutional states retained their own governmental constitutions. The question expressly preserves national constitutional rights, so federal programme supremacy does not contradict this protected state role.');fix(id,'central-local',6,-1,'Ordinary US policing remained divided among state and local authorities despite federal law-enforcement agencies. A single national directing authority is a broader centralisation than the scoped record supports.');}
for(const id of ['rishi-sunak','keir-starmer','jacinda-ardern'])fix(id,'public-private',5,-1,'The scoped NHS or New Zealand public hospital system relied substantially on publicly owned healthcare facilities. Public funding is distinct from private ownership, and contracting some services does not imply that facilities should generally be privately owned.');
fix('jean-jacques-rousseau','democracy-autocracy',3,-1,'Citizenship in his civic model did not include modern equal political rights for women. Popular sovereignty must not be translated into a claim that every adult was eligible irrespective of all exclusions.');
fix('mikhail-bakunin','democracy-autocracy',8,-1,'A national government chosen by union leaders reproduces an executive ruling structure. Voluntary worker associations are not authorisation for trade union officials to replace the general electorate in choosing a state government.');
fix('mikhail-bakunin','nationalism-internationalism',2,-1,'An international institution enforcing decisions against the freely associated community would reproduce coercive state domination. His international federation was voluntary; internationalist association does not establish unconditional binding bureaucratic authority.');
fix('mikhail-bakunin','nationalism-internationalism',6,-1,'A coercive international court with overriding state-like power conflicts with free federation and rejection of imposed authority. Voluntary arbitration would be different from the question’s binding institutional jurisdiction.');
fix('mikhail-bakunin','high-redistribution-low-redistribution',2,-1,'He opposed coercive state taxation, but also the claim that reducing income differences has no justification. His collective-property programme makes an outright anti-equality rationale less plausible; the rejection is qualified because the question specifically names taxation.');
fix('mikhail-bakunin','high-redistribution-low-redistribution',6,-1,'Retaining individual earnings in a capitalist distributive order despite substantial inequality conflicts with collective economic emancipation. Opposition to state tax does not establish acceptance of entrenched income differences.');
fix('mikhail-bakunin','high-redistribution-low-redistribution',9,0,'He endorsed material equalisation and opposed concentrated wealth while rejecting a coercive state tax-and-transfer apparatus. The proposition combines an endorsed aim with a contested means; Neutral is a substantive mixed response rather than a substitute for missing evidence.');
fix('mikhail-bakunin','culture-nature',14,0,'The 1871 letter includes discriminatory collective-character stereotypes, while other writings emphasise socially produced domination and emancipation. Those stereotypes are serious counter-evidence but do not directly document a biological explanation of per-capita violent acts; the competing indications make a mixed response most plausible and especially uncertain.');
fix('thomas-jefferson','culture-nature',14,0,'His prejudiced racial conjectures concerned capacities and character while admitting limits of knowledge and effects of slavery. They do not directly settle the specific comparative explanation of violent acts. A mixed response recognises the contradictory indications without inventing an exact biological-violence claim.');
fix('theodore-roosevelt','innovation-caution',3,1,'The presidency supported the Panama Canal and major public infrastructure while protecting forests and public lands. Substantial public benefits could outweigh habitat loss in some cases, so conservation is not a blanket veto on development.');
fix('jimmy-carter','progressive-traditionalist',7,-1,'His presidential-period abortion stance was personally restrictive and opposed federal financing beyond limited exceptions. Later public statements are outside the cutoff; ERA support does not settle social acceptance of early abortion.');
// Make already-mixed choices explicit instead of attributing uncertainty to an automatic Neutral.
const reasons={
'george-washington':{'democracy-autocracy-09':'His condemnation of factions and disruptive political societies weighs against unrestricted party activity, but he did not establish executive exclusion of parties from national elections. A mixed response is more likely than either general authority to ban positions or unconditional party neutrality.'},
'ruhollah-khomeini':{'innovation-caution-01':'Technical progress could be useful for national development, but religious and public safeguards constrained its acceptable application; substantial benefits alone would not settle every technology. This is a mixed judgment about benefits and ethical limits.'},
'mikhail-bakunin':{'public-private':'Worker and community ownership were endorsed while both capitalist control and ownership by a coercive state were rejected. This specific public-body wording conflates arrangements he would distinguish; the mixed choice does not represent missing evidence.'}};
for(const id of JSON.parse(fs.readFileSync(dir+'/subjects.json'))){const p=`profile-audit/drafts/personality/${id}.json`,d=JSON.parse(fs.readFileSync(p));for(const a of d.axes)for(const ans of a.answers){if(ans.value!==0)continue;const note=reasons[id]?.[ans.questionId]??reasons[id]?.[a.axisId]??`This proposition combines an institutional aim supported in some circumstances with a mechanism or scope limited elsewhere in the period. The axis evidence and counter-evidence pull in different directions; the most likely response is conditional rather than an unqualified endorsement or rejection. In particular, the context is ${a.brief} The countervailing limit is ${a.counterEvidence}`;ans.rationale+=' Separate wording review: '+note;}fs.writeFileSync(p,JSON.stringify(d,null,2)+'\n');}
fs.writeFileSync(dir+'/review-corrections.json',JSON.stringify(changes,null,2));console.log(changes.length,'literal wording corrections, with rationales.');
